### ISSUE TITLE
MD: Change data source to bulk data

### ISSUE THREAD

**Issue by showerst** [openstates/issues#1002]
Maryland has started publishing some really good looking bulk data for bills:

https://mgaleg.maryland.gov/2023rs/misc/billsmasterlist/legislation.json

We should move the scraper over to use that.

**Comment by rkiddy** [comment]
Is anyone working on this yet? I thought it would be a good thing to start on. It should not interfere with anyone else and it would acquaint me with the storage and such.

**Comment by rkiddy** [comment]
Just an initial check here. See attached, just looking at one bill.

It seems that the MD bulk data has a complete view of some of the bill data, but it does not seem to include anything in "versions", "documents" or "sources".

It is very possible that the bulk data may allow the elimination of some but perhaps not all of the scraping.

**Comment by rkiddy** [comment]
[md_scrape_compare.txt](https://github.com/openstates/issues/files/11445554/md_scrape_compare.txt)

**Comment by showerst** [comment]
I wonder if we could work backwards from the "BillVersion" key to get version names/urls. It looks like it's using a standard dictionary since i only see a few unique values. 

Sources is usually a link back to the bill page, which we can build in the code since MD has predictable bill urls -- eg https://mgaleg.maryland.gov/mgawebsite/Legislation/Details/hb0001

**Comment by showerst** [comment]
Following up on my last comment, it does look like you can sub in the letter into a bill url --

https://mgaleg.maryland.gov/2023RS/bills/hb/hb0001T.pdf

can swap T for F and get a working url --
https://mgaleg.maryland.gov/2023RS/bills/hb/hb0001F.pdf

So if you can work out the sequence we can loop through them for each bill.

Annoyingly I don't see anything for documents though.

**Comment by rkiddy** [comment]
I find myself with a question. Given that the dump does not give as much information as is obtained from the scraping that is done now, and that integrating in the information the scraping does give may be complicated, is there enough reason to do it?

We can ask the MD people why they do not put information on all the versions and all the documents into the dump. It seems reasonable that they should.

But until the dump is more complete, it may not be worth the bother of using it. No?

**Comment by rkiddy** [comment]
@showerst ?

**Comment by showerst** [comment]
Yeah if we can't match the current scrapers data-wise then it's not worth the trouble; since we'd still have to do all those requests to each page anyway. Shame, though if you wanna shoot the MD legislative people an email asking about it that would be great!

**Comment by showerst** [comment]
I rechecked this today, we still need to get the individual bill pages for actions and votes so switching to the JSON wouldn't save any requests, or reduce load on the state's server.

The bulk data does include additional legal citations though, so i'll add that as a separate PR.

@jessemortenson FYI.
