### ISSUE TITLE
FL Senate Out of Date

### ISSUE THREAD

**Issue by egrosshans** [openstates/issues#1003]
Open States is still showing Annette Taddeo, Democratic, District 40, Senate and Jeff Brandes, Republican, District 24, Senate but they are no longer senators and should be replaced by Bobby Powell, Democrat, District 24, Senate and Ana Maria Rodriguez, Republican, District 40, Senate. 

https://openstates.org/fl/legislators/?chamber=upper

**Comment by egrosshans** [comment]
*Bobby Powell, Democrat, District **40**, Senate

**Comment by NewAgeAirbender** [comment]
This has been updated, thank you for raising this issue!
