### ISSUE TITLE
Missing legislators for a bill (NY) and missing information for legislators (NM)

### ISSUE THREAD

**Issue by tuanpham96** [openstates/issues#1024]
**Issue Description:** Some states have legislator information missing, either missing sponsors or their metadata/

**URL where this issue may be seen (API or OpenStates.org):** both

**Source URL of correct data if applicable:** 

- This [NY-A3593](https://openstates.org/ny/bills/2023-2024/A3593/) is reported on the site to have only 1 sponsor, but based on the [state assembly site](https://www.nysenate.gov/legislation/bills/2023/A3593), there should be a total of 5 (1 primary + 4 co-sponsors)
- For NM legislators, metadata about them seem to be missing, e.g. `person.party` and `current_role`. Particularly [NM-HM75](https://openstates.org/nm/bills/2023/HM75/) and [NM-SM63](https://openstates.org/nm/bills/2023/SM63/). The state site contains information about them, e.g: for [NM-HM75](https://www.nmlegis.gov/Legislation/Legislation?chamber=H&legType=M&legNo=75&year=23) the sponsor is `Representative Stefani Lord - (R)`.

Thanks!

**Comment by showerst** [comment]
I have a patch in testing for the NY cosponsor issue, i'll update this bug when it's merged. 

https://github.com/openstates/openstates-scrapers/pull/4621

**Comment by tuanpham96** [comment]
@NewAgeAirbender @showerst 
Has the issue for NM legislators' metadata been addressed?

Thanks for addressing the NY issue by the way.
