### ISSUE TITLE
Daniel Bonham shown as Rep and Sen, as well as incorrect Rep district

### ISSUE THREAD

**Issue by eoghan87** [openstates/issues#1033]
**Issue Description:**
Daniel Bonham in Oregon is appearing as both a Sen and Rep

**URL where this issue may be seen (API or OpenStates.org):**
[https://openstates.org/search/?query=daniel+bonham](https://openstates.org/search/?query=daniel+bonham)

**Source URL of correct data if applicable:**
[https://www.oregonlegislature.gov/bonham](https://www.oregonlegislature.gov/bonham) shows him as a Sen
also shows vikki breese-iverson for [district 59](https://www.oregonlegislature.gov/breese-iverson/) instead of [district 55](https://openstates.org/person/vikki-breese-iverson-4xiuWKeMWTH9RhFMxAHmdB/)

**Comment by NewAgeAirbender** [comment]
He has been a Representative in the past, but is now accurately a Senator. Vikki Breese-Iverson is also updated.
