### ISSUE TITLE
CA Assembymember shows partially incorrect website information

### ISSUE THREAD

**Issue by mjbalbontin** [openstates/issues#1041]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Profile for California Assemblymember Tasha Boerner Horvath shows two websites, the first of which is incorrect (https://a76.asmdc.org/).

![image](https://github.com/openstates/issues/assets/20426393/3460e93b-1f0f-491b-b83c-351ab86865bc)

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/tasha-boerner-horvath-4ouybAAhbHOxQ8noMjFzRq/

**Source URL of correct data if applicable:**

**Comment by NewAgeAirbender** [comment]
Will be fixed with this [PR](https://github.com/openstates/people/pull/1112)
