### ISSUE TITLE
WA: current progress status conflict for HB1442 between openstates and state's official site

### ISSUE THREAD

**Issue by tuanpham96** [openstates/issues#1055]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
The progress of bill WA-HB1442 seems to have conflict between the [openstates](https://openstates.org/wa/bills/2023-2024/HB1442/) compared to the [state official tracker](https://app.leg.wa.gov/billsummary?BillNumber=1442&Year=2023). The former says it has "Passed Housed" but the official site didn't say it "Passed Chamber" yet. 

**URL where this issue may be seen (API or OpenStates.org):**
- site: https://openstates.org/wa/bills/2023-2024/HB1442/

**Source URL of correct data if applicable:**
- https://app.leg.wa.gov/billsummary?BillNumber=1442&Year=2023

**Comment by showerst** [comment]
Thanks, the "DO Pass" on the substitute was getting picked up as "passed the chamber" instead of "the motion to substitute passed". I'll push a fix for that shortly, and it should update in the coming days.

**Comment by tuanpham96** [comment]
Seems this is now fixed. I'll close this issue.
