### ISSUE TITLE
NJ S 3902 Scrape info failing

### ISSUE THREAD

**Issue by mwhipple20** [openstates/issues#1059]
Hello,

I am trying to pull info for NJ S 2902 but there is no information from this session pulling.

**Comment by showerst** [comment]
NJ posts a lot of test and non-functional bills, so in that state we don't add bills until they have either a version or an action added. 

The companion bill, [A5448](https://openstates.org/nj/bills/220/A5448/) is available. S3902 will load when it's introduced or any versions are published.

**Comment by NewAgeAirbender** [comment]
The info for that bill is now available
