### ISSUE TITLE
MA bill scraper jobs timing out

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#107]
**Issue Description:** Looks like the MA bill scraper job is[ timing out 5 of the last 6 days](https://bobsled.openstates.org/task/MA-scrape). 

Does this mean the task isn't exactly failing, but is exceeding a max execution time defined in the task runner? Guessing it might be going over 24 hours based on how long some recent runs have been.

**URL where this issue may be seen (API or OpenStates.org):** https://bobsled.openstates.org/task/MA-scrape

**Comment by jamesturk** [comment]
Thanks for catching this, I hadn't been monitoring too closely and thought
all were OK.

I'll up the timeout to 30 hours & see how we're doing.

**Comment by jessemortenson** [comment]
Guessing MA is just so slow based on sheer number of requests (lots of bills, requests per bill). Does the scrape job insert new data into the OS database (that powers the DB) as it yields each bill, or all at the end of the job as a batch?

**Comment by showerst** [comment]
Yeah the way MA's site is built, it requires an obnoxious number of requests per bill because _everything_ is a separate endpoint and paginated.

**Comment by jamesturk** [comment]
All scrapers import at the end of the job (for now at least), and yeah MA
is a complete pain & always has been-  always a little hopeful at a new
session that they'll unveil some new site or bulk data offering.

**Comment by jessemortenson** [comment]
Looks like we need to re-open this as tasks have continued to either error (most recently on `Max retries exceeded with url: /Bills/191/S78/CoSponsor`) or more often time out. 

Would it be worth considering a second MA scrape job that attempts to scrape a limited subset of bills starting with the most recently added bills? Looks like it would require a code change to allow a flag that tells the task to stop scraping after a certain quantity of bills, but imagining something like:

```
ma bills --scrape sort=latest limit=500
```
That way, every day, a task is run that is lower risk of failing (due to sheer # of requests and probability of retries exceeded on any given request) and run faster. You get *most* of the new data.

Meanwhile the full scrape could still run every day, or every few days, presuming it can be fixed.
