### ISSUE TITLE
Arizona House of Representatives dataset out of date

### ISSUE THREAD

**Issue by michaelnewmode** [openstates/issues#1078]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
State house info out of date. Some examples: 
LD13, Julie Willoughby - House (replaced Liz Harris, LD13).
LD26, Quantá Crews (alongside Cesar Aguilar)

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/az/legislators/?chamber=lower

**Source URL of correct data if applicable:**
https://www.azleg.gov/memberroster/

**Comment by NewAgeAirbender** [comment]
This has been updated. Thank you for raising this issue
