### ISSUE TITLE
Missing Legislators in Massachusetts 

### ISSUE THREAD

**Issue by JonathanCohn** [openstates/issues#108]
**Issue Description:**

Massachusetts had several special elections this spring; however, the new legislators' names do not appear. 

The new legislators' names are John Velis, Susan Moran, Carol Doherty, and Danillo Sena. 

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/john-c-velis-4yTcELJ9n51Q00xvB5PSFp/ -- This rep is now a senator. 

**Source URL of correct data if applicable:**
John Velis: https://malegislature.gov/Legislators/Profile/JCV0
Susan Moran: https://malegislature.gov/Legislators/Profile/SLM0
Carol Doherty: https://malegislature.gov/Legislators/Profile/CAD1
Danillo Sena: https://malegislature.gov/Legislators/Profile/CAD1

**Comment by jamesturk** [comment]
rolling into #160
