### ISSUE TITLE
Sarahana Shrestha being shown representing wrong party

### ISSUE THREAD

**Issue by eoghan87** [openstates/issues#1081]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Sarahana Shrestha being reported as Republic but google shows she is Democrat

**URL where this issue may be seen (API or OpenStates.org):**
[https://openstates.org/person/sarahana-shrestha-3kPujVOM87hIIHUXsAxi1/](https://openstates.org/person/sarahana-shrestha-3kPujVOM87hIIHUXsAxi1/)

**Source URL of correct data if applicable:**
Her campaign site had her for Democratic Nominee, and 
[https://sarahanaforassembly.com/](https://sarahanaforassembly.com/)

**Comment by NewAgeAirbender** [comment]
Thank you for flagging this, this has been fixed
