### ISSUE TITLE
New York Assembly Party Designation

### ISSUE THREAD

**Issue by eatmorebacon** [openstates/issues#1089]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
All but two Assemblymembers are shown as Republican.  

**URL where this issue may be seen (API or OpenStates.org):**
https://open.pluralpolicy.com/ny/legislators/?chamber=lower

**Source URL of correct data if applicable:**
It is obviously wrong, but correct data can be seen at Ballotpedia https://ballotpedia.org/New_York_State_Assembly.  The specific issue reported to us was NY-135 Jen Lunsford shown as Republican, where she is a Democrat but there is a much bigger issue with the data here.

**Comment by NewAgeAirbender** [comment]
Thank you for flagging this, working on getting them updated.

**Comment by NewAgeAirbender** [comment]
This should be remedied! Thanks again
