### ISSUE TITLE
Data Questions

### ISSUE THREAD

**Issue by ayazdin** [openstates/issues#1102]
### Discussed in https://github.com/openstates/issues/discussions/826

Hi there, thanks for the awesome API, i have been using it for sometime now. Recently i got reported that representative in 9th Suffolk WA has been released and another representative joined. The data don't seemed to be updated, on some research i found that the data is managed in https://github.com/openstates/people/tree/main/data, not sure if i should delete the older and add a newer one. Please provide some guidance on this, thanks.

**Comment by NewAgeAirbender** [comment]
Hello, here's documentation around [updating people data](https://docs.openstates.org/contributing/people/) & you'll probably have to run the state scraper to get the new legislator's file first but make sure to follow the Retiring a Legislator steps. Let me know if you have questions or need help.

**Comment by ayazdin** [comment]
Thanks @NewAgeAirbender i ll check this

**Comment by ayazdin** [comment]
Hi again @NewAgeAirbender i am not a python dev and not sure about the steps of setting up the code base to scrape and it is not working for me. I have seen 2 of the representative changed in MA(Massachusetts) state that needs to be changed. Can you help to fix this? 
Thanks

**Comment by NewAgeAirbender** [comment]
Yeah, I can check on those today. Will let you know when those are updated.

**Comment by NewAgeAirbender** [comment]
Those positions have been updated

**Comment by ayazdin** [comment]
Hi @NewAgeAirbender, that was such a quick response, thanks i just checked that the new peoples are already in position. Thanks again for the quick response and updates
