### ISSUE TITLE
Ohio Lower Chamber Vote Data Missing

### ISSUE THREAD

**Issue by SusanOhio** [openstates/issues#111]
When viewing an Ohio State Representative's record, recently sponsored bills are shown but recent votes are not.

Example: The last vote that OpenStates shows for Rep. Mark Fraizer was on 02/05/20. I have personal knowledge that he has voted on numerous bills and resolutions since then. https://openstates.org/person/mark-fraizer-3WMMqxYgr03bMWx25AgcXG/

**Comment by jamesturk** [comment]
@SusanOhio if you see this, do you have any bills that you know have a vote that we can investigate more closely

**Comment by SusanOhio** [comment]
I’d sent that message back in the spring or summer and don’t specifically recall which bills I was looking at, but probably some of the ones having to do with the primary election.

I looked at the bills I’m tracking in the end of session and those do appear to be correctly updating now. 

Thanks, and if I do come across one that isn’t updating, I’ll message you directly. Thanks.

**Comment by jamesturk** [comment]
great to hear, sorry for the delay and get in touch if anything is wrong later
