### ISSUE TITLE
Nebraska governor is Jim Pillen

### ISSUE THREAD

**Issue by jbothma** [openstates/issues#1110]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**

Currently the people repo only has the exit of the previous governor. Currently the governor is Jim Pillen.

**URL where this issue may be seen (API or OpenStates.org):**

https://github.com/openstates/people/tree/main/data/ne/executive

**Source URL of correct data if applicable:**

https://governor.nebraska.gov/
https://www.wikidata.org/wiki/Q111961602

**Comment by NewAgeAirbender** [comment]
We don't have scrapers for Executive branches of government and so rely on user-submitted files for those positions, but thank you for flagging this

**Comment by alexobaseki** [comment]
Resolved.
