### ISSUE TITLE
Virginia State Assembly & Senate OOD

### ISSUE THREAD

**Issue by michaelnewmode** [openstates/issues#1134]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Both the Senate and Assembly are OOD on your system since the November election took place (see here for reference: https://www.nytimes.com/interactive/2023/11/07/us/elections/results-virginia-state-legislature.html).

**URL where this issue may be seen (API or OpenStates.org):**
Assembly (wrong): https://open.pluralpolicy.com/va/legislators/?chamber=lower
Senate (wrong): https://open.pluralpolicy.com/va/legislators/?chamber=upper

**Source URL of correct data if applicable:**
Assembly (correct): https://virginiageneralassembly.gov/house/members/members.php?name=&gender=&party=
Senate (correct): https://apps.senate.virginia.gov/Senator/index.php

**Comment by NewAgeAirbender** [comment]
This is fixed now! Thank you for raising this issue, had to wait until the data was posted on the site.
