### ISSUE TITLE
OK: fix vote scraping logic

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1136]
The OK bill scraper has been failing to return votes since 2019. We don't have vote data since then. The goal is to get a full dataset of [Vote Events](https://github.com/openstates/openstates-core/blob/80ce66047a061a653bc9a2355945bacf70d6e9ec/openstates/scrape/vote_event.py#L9) for OK in both House and Senate, including [classification](https://github.com/openstates/openstates-core/blob/c6e034093dafd2604af2f310bd1d80ad11e3ca32/openstates/data/common.py#L139), motion text, the result of the vote (eg total number of votes, pass vs. fail) and also the yes/no vote of each member who voted.

The [OK Bills scraper has logic that attempts to scrape votes for a bill](https://github.com/openstates/openstates-scrapers/blob/f66529f43425d5c7ea8a3c5edf1af489d51625c8/scrapers/ok/bills.py#L241). The `scrape_votes()` method does get called, but the xpath logic used to try to select data on the votes page does not find any matches:

```
        re_ns = "http://exslt.org/regular-expressions"
        path = r"//p[re:test(text(), 'OKLAHOMA\s+(HOUSE|STATE\s+SENATE)')]"
        for header in page.xpath(path, namespaces={"re": re_ns}):
```

Most likely the structure of the votes page has changed since that code was written, or possibly there is a text labeling change so that the regex match is no longer working.

Context for debugging:

* [Generate a list of all OK bills](http://webserver1.lsb.state.ok.us/WebApplication3/WebForm1.aspx) by selecting all bill types and searching
* Example of a bill with votes: [SB4](http://www.oklegislature.gov/BillInfo.aspx?Bill=SB4&session=2400) (see Votes tab)
* Find more examples of bills that passed at least one chamber [in Plural](https://pluralpolicy.com/app/legislative-tracking?chamber=both&includeTrackedBills=1&jurisdictions=ok&legislativeType=bill&legislativeType=resolution&legislativeType=joint%20resolution&legislativeType=concurrent%20resolution&legislativeType=proclamation&legislativeType=proposed%20bill&legislativeType=appropriation&legislativeType=appointment&legislativeType=other&onlyShowMomentumBills=0&order=alphanumerical&page=13&sessions=Current%20Sessions&status=passed_upper&status=passed&status=passed_lower)

**Comment by braykuka** [comment]
@jessemortenson I am not sure about motion text. Could you please explain about it?

http://webserver1.lsb.state.ok.us/cf/2023-24%20SUPPORT%20DOCUMENTS/votes/House/SB4_VOTES.HTM
http://webserver1.lsb.state.ok.us/cf/2023-24%20SUPPORT%20DOCUMENTS/votes/Senate/SB4_VOTES.HTM

In my code review, the house vote's motion text should be "DO PASS" and senate's motion text should be empty.
When the motion text is empty, should we skip such votes?
