### ISSUE TITLE
Third Party Logins not working

### ISSUE THREAD

**Issue by 5044Joker** [openstates/issues#1137]
This is the right template to select if you're reporting an issue with the functionality of OpenStates.org.
If this is a data issue, please select data issue instead!

Example URL: [https://openstates.org/<path-to-page>](https://open.pluralpolicy.com/accounts/login/?next=/accounts/profile/#apikey)
Browser: Edge and Firefox

Please describe the issue: When you click any of the third party links to login it just takes you to a page that says continue. There's no way to login. Screenshot attached. 

<img width="912" alt="Screenshot 2023-12-22 000512" src="https://github.com/openstates/issues/assets/154586853/916e5dad-538d-4a60-96a5-08a9969239f0">

Please let me know when I can login to request an API Key

Please attach a screenshot if applicable!

**Comment by NewAgeAirbender** [comment]
Thank you for bringing this to our attention. You can actually click "Continue" to continue signing in with Google, it's just an automatic template so we haven't been able to make the word a button or more clear to the user that that's what needs to be clicked.

**Comment by 5044Joker** [comment]
Thanks for getting back to me. It's a good test :-) to see who will reach out. It worked great. Thank you. I wasn't able to get the github account to work to provide access but my google account did work. Cheers.
