### ISSUE TITLE
MO: scrape events for MO House from XML source

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1139]
We need to update the [MO Event scraper](https://github.com/openstates/openstates-scrapers/blob/71297919999afd380b232b4e9475c897db1e255d/scrapers/mo/events.py#L161C9-L161C21)’s scrape_lower to pull from this [XML page](https://documents.house.mo.gov/xml/241-UpcomingHearingList.XML). It’s a list of upcoming events but can sometimes be empty when nothings' scheduled, but there is documentation on the expected [XML structure](https://documents.house.mo.gov/XMLHearingExports.html) of each element.

MO House normal website is now blocking bots generally, having provided this XML data source as an alternative. Right now the MO events scraper fails because it cannot reach the conventional MO House website. We can re-enable it once the data source is changed to the XML source above.

**Comment by braykuka** [comment]
[#4792](https://github.com/openstates/openstates-scrapers/pull/4792)
