### ISSUE TITLE
HI needs fixes to Bill and Event scrapers

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1140]
The [bill](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/hi/bills.py) & [event](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/hi/events.py) scrapers for HI fail out trying to get the list of sessions. We need to see if that function just needs to be updated or the rest of the scrapers also need to be rewritten.

`openstates.exceptions.CommandError: no sessions from Hawaii.get_session_list()`

Checking the Network tab on page load shows that Cloudflare has been added to the HI site. There’s a bill list page that I’ve gotten to load successfully in Postman

* Senate: `GET https://www.capitol.hawaii.gov/advreports/advreport.aspx?year=2024&report=deadline&active=false&rpt_type=&measuretype=sb&title=2023%20and%202024%20Senate%20Bills`
* House: `GET https://www.capitol.hawaii.gov/advreports/advreport.aspx?year=2024&report=deadline&active=false&rpt_type=&measuretype=hb&title=2023%20and%202024%20House%20Bills`

So maybe with the right browser agent, request to hit those pages could work. There’s also an export to csv option on that page that we also may be able to use for scraping. 

That said, we may need to use a library or service to get around Cloudflare to get those pages if the request headers/browser agent approach doesn’t work.

**Comment by showerst** [comment]
FYI we've got the Cloudscraper library included in the pyproject already for use in OH and MP, so I'd check to see if that fixes it. Import the lib, then set 
```python
scraper = cloudscraper.create_scraper()
```
