### ISSUE TITLE
NE: Voter & Vote Count Fix

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1168]
Looks like the selectors on the [Vote detail](https://github.com/openstates/openstates-scrapers/blob/9fdf516e34176b16a67d3d0fcbf642d335c477c9/scrapers/ne/bills.py#L275) page are broken so it misses vote counts & voters but still scrapes a vote event for that bill locally so at least the link to the vote detail page is correct. Need to pull the proper yes/no/etc counts & the legislators that voted each way. Here's an example of the vote detail page for bill [LB908](https://nebraskalegislature.gov/bills/view_votes.php?KeyID=9989)

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it.
