### ISSUE TITLE
AL: Add Bills to Events

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1169]
On the AL legislative site, you can see upcoming events and the bills on their agendas on this [page](https://alison.legislature.state.al.us/todays-schedule). We’d expect bills that show up on agendas to have an event created for that bill in Open States.

The request that that page makes is below & does return the Bill Ids as `InstrumentNbr` so should be able to attach them to Events as related bills.

`{
    "query": "{hearingsMeetingsDetails(eventType:\"meeting\", body:\"\", keyword:\"\", toDate:\"3000-03-04\", fromDate:\"2024-03-04\", sortTime:\"\", direction:\"ASC\", orderBy:\"SortTime\", ){EventDt,EventTm,Location,EventTitle,EventDesc,Body,DeadlineDt,PublicHearing,LiveStream,Committee,AgendaUrl,SortTime,OidMeeting, Sponsor, InstrumentNbr, ShortTitle, OidInstrument, SessionType, SessionYear}}",
    "operationName": "",
    "variables": []
}`

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it.
