### ISSUE TITLE
USA: Roll Call 

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1170]
We scrape [Senate](https://www.senate.gov/) & [House](https://clerk.house.gov/) sites separately & both [scrapers](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/usa/votes.py) seem a little out of date. Investigated & we can rewrite the scraper to process votes in the Bill scrape: 

HB 2882 has this [XML data page](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr2882.xml) that we scrape for the Bill data already & looks like `actions` have items that include `recordedVotes` objects that contain a `url` that is the correct link to an XML page with the rollcall on it (ex. [Roll 32](https://clerk.house.gov/evs/2024/roll032.xml) on 2/5). Pretty sure we can add a `scrape_votes` function in & call it if there are `recordedVotes` objects when [the scraper](https://github.com/openstates/openstates-scrapers/blob/ce19d9ae3cd30ae341bd175df178671708530405/scrapers/usa/bills.py#L232) is in scrape_actions. Need the vote type counts & how each legislator voted.

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it.
