### ISSUE TITLE
NY: Vote Roll Call

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1172]
Assembly votes for NY are missing the names attached to the vote, for example A9166 on the [site](https://nyassembly.gov/leg/?default_fld=&leg_video=&bn=A09166&term=2023&Floor%26nbspVotes=Y) vs [Open States](https://open.pluralpolicy.com/vote/dd20716d-9bef-40b6-8f00-e91d9c2aae4e/). Pretty sure the [vote parsing](https://github.com/openstates/openstates-scrapers/blob/cf7824f909473bd42e00276699c03d5fd960c59a/scrapers/ny/bills.py#L491) on the Bill scraper needs an update. Note, we do use the NY API to get access to the legislative data so you will need to request an [API key](https://legislation.nysenate.gov/public) to set in the environment prior to scraping, [docs for reference](https://docs.openstates.org/contributing/state-specific/#state-api-keys)

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it.
