### ISSUE TITLE
Kansas House Legislator Out of Date (District 39 should be Angela Stiens)

### ISSUE THREAD

**Issue by mjbalbontin** [openstates/issues#1177]
**Issue Description:**
The Kansas House Legislator for district 39 was recently changed from Owen Donohoe to Angela Stiens, needs to be updated here.

**URL where this issue may be seen (API or OpenStates.org):**
- Kansas Legislators - House: https://open.pluralpolicy.com/ks/legislators/?chamber=lower
- Kansas Legislators - Both Chambers: https://open.pluralpolicy.com/ks/legislators/

**Source URL of correct data if applicable:**
http://kslegislature.org/li/b2023_24/members/rep_stiens_angela_1/

**Comment by NewAgeAirbender** [comment]
Thank you for flagging this, I'll take a look

**Comment by NewAgeAirbender** [comment]
This has been fixed!

**Comment by mjbalbontin** [comment]
Amazing, thank you for the fast turnaround!
