### ISSUE TITLE
Incorrect email address associated with Maryland Delegate Joe Vogel

### ISSUE THREAD

**Issue by michaelnewmode** [openstates/issues#1182]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Joe Vogel's email address is **joe.vogel@house.state.md.us**, rather than joseph.vogel@house.state.md.us 

**URL where this issue may be seen (API or OpenStates.org):**
https://open.pluralpolicy.com/person/joe-vogel-FGyydcFil5X3QQGNlxBvR/

**Source URL of correct data if applicable:**
https://mgaleg.maryland.gov/mgawebsite/Members/Details/vogel01

**Comment by NewAgeAirbender** [comment]
Thank you for raising this, it has been fixed
