### ISSUE TITLE
IL: Vote Scraper Fragility

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1185]
Started adding [Votes back](https://github.com/openstates/openstates-scrapers/pull/4914) in with the Bill scraper, but ran into issues with getting the full scrape working. There's an issue with the pdf parsing matching up with the participants, as shown on the logs for HB 42 below. The goal is to get to full scrape with vote data successfully, making it less fragile.
![Screenshot 2024-04-10 at 2 53 50 PM](https://github.com/openstates/issues/assets/34139325/e9fd24aa-1529-423f-a4d4-3dcdd76be853)

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it

**Comment by braykuka** [comment]
@NewAgeAirbender please check it.
