### ISSUE TITLE
USA: Add Events to Action Parsing

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1186]
We scrape the bulk data pages for Bill data, for example [HR 6854](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr6854.xml). On the congress website, Actions are listed in [this table](https://www.congress.gov/bill/118th-congress/house-bill/6854/all-actions?s=2&r=2&q=%7B%22search%22%3A%22latestMajorActionCode%3A4100%22%7D) and we want to capture the Hearings listed in the Actions. If there's an Action item with 'Sub|Committee Hearing Held' with the date we want to capture that as an Event. There is a Committee or Subcommittee name on that Action item to serve as participants & should have the Bill as a related entity, the location can just be set as `Washington, DC 20004`. 

Another example bill is [S 382](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/s/BILLSTATUS-118s382.xml), the 'Committee on Indian Affairs. Hearings held.` would be the Event name.

**Comment by braykuka** [comment]
@NewAgeAirbender, Do you want to add an event for such activity? If then, there should be a location name for it.

Or just you want to add it as an activity named "Hearing by"  instead of the original activity text? In this case, how can we add a bill and committee names? 

Thanks.

**Comment by NewAgeAirbender** [comment]
Updated the description to reflect your questions. We've changed the scope to only scrape from the Actions section & included a default location to set for the Event. If there's anything else, let me know!
