### ISSUE TITLE
Arizona State House OOD

### ISSUE THREAD

**Issue by michaelnewmode** [openstates/issues#1188]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
[Marcelino Quiñonez] is no longer in office and is listed on your site. I believe may have been replaced by Junelle Cavero. 

**URL where this issue may be seen (API or OpenStates.org):**
https://open.pluralpolicy.com/az/legislators/?chamber=lower

**Source URL of correct data if applicable:**
https://www.azleg.gov/memberroster/?body=H

**Comment by NewAgeAirbender** [comment]
Thank you for flagging this, will have that fixed today

**Comment by NewAgeAirbender** [comment]
This has been fixed, thank you!
