### ISSUE TITLE
WV: House Vote Fix

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1189]
We're getting Senate votes in just fine, but need to update the House PDF scraper to get Votes for WV. For example, [HB 5237](https://www.wvlegislature.gov/Bill_Status/Bills_history.cfm?input=5237&year=2024&sessiontype=RS&btype=bill) has 3 vote roll call links, while we only get one on the [OS Bill](https://open.pluralpolicy.com/wv/bills/2024/HB5237/) & on local scrape. We need to update the [scrape_house_vote](https://github.com/openstates/openstates-scrapers/blob/a2116945133d896cf5560131b4d563b672ea9d6b/scrapers/wv/bills.py#L267) function updated so that it works, the [senate vote](https://github.com/openstates/openstates-scrapers/blob/a2116945133d896cf5560131b4d563b672ea9d6b/scrapers/wv/bills.py#L366) function is pretty similar so may be helpful. Need the vote counts & names of votees.

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on this.
