### ISSUE TITLE
Governor not appearing in in the following states:  Alabama, Arizona, Arkansas, Hawaii, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Mississippi, Nebraska, Nevada, New Jersey, Oklahoma, Oregon, Pennsylvania, Tennessee, Vermont, Wyoming

### ISSUE THREAD

**Issue by katgreg** [openstates/issues#1196]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**

**URL where this issue may be seen (API or OpenStates.org):**

**Source URL of correct data if applicable:**

**Comment by NewAgeAirbender** [comment]
We don't scrape for Executive branches & rely on users to submit files for people in those positions, but thank you for submitting

**Comment by alexobaseki** [comment]
Resolved
