### ISSUE TITLE
IN bills scraper rewrite 2025 - Indiana will need a new scraper this summer

### ISSUE THREAD

**Issue by showerst** [openstates/issues#1207]
Received this email from the state:

We are happy to announce the release of our new and improved Indiana General Assembly API! Please see the new [documentation](https://docs.beta-api.iga.in.gov/) to get started using the Beta Indiana General Assembly API 2.0.

The Beta API 2.0 can be accessed at https://beta-api.iga.in.gov/. Once the API 2.0 goes live on October 1, 2024, it will replace the current API and use the original URL of https://api.iga.in.gov/.

Scope of this ticket is to rewrite https://github.com/openstates/openstates-scrapers/blob/main/scrapers/in/bills.py - resulting scraper should return equivalent or better/more-complete data compared to existing scraper.

**Comment by braykuka** [comment]
I will work on it.
