### ISSUE TITLE
PR Missing 300+ bills

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#121]
**Issue Description:** Looks like Open States state for PR in the 2017-2020 session is missing about 330 bills. A couple examples:

[RS 1356](https://sutra.oslpr.org/osl/esutra/MedidaReg.aspx?rid=135628)
[RCC 668](https://sutra.oslpr.org/osl/esutra/MedidaReg.aspx?rid=135666)

I'm not seeing a distinct pattern. Looks like all resolutions. Bill numbers like:

* RCC
* RKC
* RS

Full list of believed to be missing bills:

    RCC 660
    RCC 661
    RCC 662
    RCC 663
    RCC 664
    RCC 665
    RCC 666
    RCC 667
    RCC 668
    RCC 669
    RCC 670
    RCC 671
    RCC 672
    RCC 673
    RCC 674
    RCC 675
    RCC 676
    RCC 677
    RCC 678
    RCC 679
    RCC 680
    RCC 681
    RCC 682
    RCC 683
    RCC 684
    RCC 685
    RCC 686
    RCC 687
    RCC 688
    RCC 689
    RCC 690
    RCC 691
    RCC 692
    RCC 693
    RCC 694
    RCC 695
    RCC 696
    RCC 697
    RCC 698
    RCC 699
    RCC 700
    RCC 701
    RCC 702
    RCC 703
    RCC 704
    RCC 705
    RCC 706
    RCC 707
    RCC 708
    RCC 709
    RCC 710
    RCC 711
    RCC 712
    RCC 713
    RCC 714
    RCC 715
    RCC 716
    RCC 717
    RCC 718
    RCC 719
    RCC 720
    RCC 721
    RCC 722
    RCC 723
    RCC 724
    RCC 725
    RCC 726
    RCC 727
    RCC 728
    RCC 729
    RCC 730
    RCC 731
    RCC 732
    RCC 733
    RCC 734
    RCC 735
    RCC 736
    RCC 737
    RCC 738
    RCC 739
    RCC 740
    RCC 741
    RCC 742
    RCC 743
    RCC 744
    RCC 745
    RCC 746
    RCC 747
    RCC 748
    RCC 749
    RCC 750
    RCC 751
    RCC 752
    RCC 753
    RCC 754
    RCC 755
    RCC 756
    RCC 757
    RCC 758
    RCC 759
    RCC 760
    RCC 761
    RCC 762
    RCC 763
    RCC 764
    RCC 765
    RCC 766
    RCC 767
    RCC 768
    RCC 769
    RKC 100
    RKC 101
    RKC 102
    RKC 108
    RKC 109
    RKC 110
    RKC 111
    RKC 112
    RKC 113
    RKC 114
    RKC 115
    RKC 116
    RKC 117
    RKC 118
    RKC 119
    RKC 120
    RKC 121
    RKC 122
    RKC 123
    RKC 124
    RKC 125
    RKC 126
    RKC 127
    RKC 91
    RKC 92
    RKC 93
    RKC 94
    RKC 95
    RKC 96
    RKC 97
    RKC 98
    RKC 99
    RS 1190
    RS 1191
    RS 1192
    RS 1193
    RS 1194
    RS 1195
    RS 1196
    RS 1197
    RS 1198
    RS 1199
    RS 1200
    RS 1201
    RS 1202
    RS 1203
    RS 1204
    RS 1205
    RS 1206
    RS 1207
    RS 1208
    RS 1209
    RS 1210
    RS 1211
    RS 1212
    RS 1213
    RS 1214
    RS 1215
    RS 1216
    RS 1217
    RS 1218
    RS 1219
    RS 1220
    RS 1221
    RS 1222
    RS 1223
    RS 1224
    RS 1225
    RS 1226
    RS 1227
    RS 1228
    RS 1229
    RS 1230
    RS 1231
    RS 1232
    RS 1233
    RS 1234
    RS 1235
    RS 1236
    RS 1237
    RS 1238
    RS 1239
    RS 1240
    RS 1241
    RS 1242
    RS 1243
    RS 1244
    RS 1245
    RS 1246
    RS 1247
    RS 1248
    RS 1249
    RS 1250
    RS 1251
    RS 1252
    RS 1253
    RS 1254
    RS 1255
    RS 1256
    RS 1257
    RS 1258
    RS 1259
    RS 1260
    RS 1261
    RS 1262
    RS 1263
    RS 1264
    RS 1265
    RS 1266
    RS 1267
    RS 1268
    RS 1269
    RS 1270
    RS 1271
    RS 1272
    RS 1273
    RS 1274
    RS 1275
    RS 1276
    RS 1277
    RS 1278
    RS 1279
    RS 1280
    RS 1281
    RS 1282
    RS 1283
    RS 1284
    RS 1285
    RS 1286
    RS 1287
    RS 1288
    RS 1289
    RS 1290
    RS 1291
    RS 1292
    RS 1293
    RS 1294
    RS 1295
    RS 1296
    RS 1297
    RS 1298
    RS 1299
    RS 1300
    RS 1301
    RS 1302
    RS 1303
    RS 1304
    RS 1305
    RS 1306
    RS 1307
    RS 1308
    RS 1309
    RS 1310
    RS 1311
    RS 1312
    RS 1313
    RS 1314
    RS 1315
    RS 1316
    RS 1317
    RS 1318
    RS 1319
    RS 1320
    RS 1321
    RS 1322
    RS 1323
    RS 1324
    RS 1325
    RS 1326
    RS 1327
    RS 1328
    RS 1329
    RS 1330
    RS 1331
    RS 1332
    RS 1333
    RS 1334
    RS 1335
    RS 1336
    RS 1337
    RS 1338
    RS 1339
    RS 1340
    RS 1341
    RS 1342
    RS 1343
    RS 1344
    RS 1345
    RS 1346
    RS 1347
    RS 1348
    RS 1349
    RS 1350
    RS 1351
    RS 1352
    RS 1353
    RS 1354
    RS 1355
    RS 1356
    RS 1357
    RS 1358
    RS 1359
    RS 1360
    RS 1361
    RS 1362
    RS 1363
    RS 1364
    RS 1365
    RS 1366
    RS 1367
    RS 1368
    RS 1369
    RS 1370
    RS 1371
    RS 1372
    RS 1373
    RS 1374
    RS 1375
    RS 1376
    RS 1377
    RS 1651

**Comment by jamesturk** [comment]
running an one-off, I'll close this when it finishes and the bill count matches again

heads up @showerst you may want to do the same
