### ISSUE TITLE
IL: Sponsorship Cleanup

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1213]
There are times in IL where a legislator is changed from a “co-sponsor” to a “chief sponsor” in the Actions of the Bill. Ex: SB 3727 ([OS](https://open.pluralpolicy.com/il/bills/103rd/SB3727/), [Source](https://ilga.gov/legislation/BillStatus.asp?DocNum=3727&GAID=17&DocTypeID=SB&LegId=153792&SessionID=112&GA=103)). When this happens we’d expect that person to move in OS from co-sponsor to primary sponsor. 

Another example of sponsorships being added/removed during a bill’s life is [sb 1779](https://open.pluralpolicy.com/il/bills/103rd/SB1779/) vs [source](https://ilga.gov/legislation/BillStatus.asp?DocNum=1779&GAID=17&DocTypeID=SB&LegId=146600&SessionID=112&GA=103). We need the scraper to parse through the actions to update sponsorship levels, there's already part of the code that tries to [reform sponsorship types](https://github.com/openstates/openstates-scrapers/blob/3841707f163702f8e0dad66a0b0453aa2d2d6d46/scrapers/il/bills.py#L97) so that may just need some tweaking.

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it.
