### ISSUE TITLE
SD: Add Room to Location

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1214]
Most events on the [SD API](https://sdlegislature.gov/api/Documents/Schedule) have a `Room` value that we should be adding to the `event` `location` that we set on [line 187](https://github.com/openstates/openstates-scrapers/blob/d332298bf2108604d434dc55de54af60153c03a9/scrapers/sd/events.py#L187) in the scraper. Should also just check that it is a `Room \d+` to append, if it's something like `David Lust Accelerator Building; Rapid City, SD` we should just have that be the event's location instead of adding it to the capitol building string.

**Comment by braykuka** [comment]
@NewAgeAirbender I will work it.

**Comment by braykuka** [comment]
@NewAgeAirbender I've fixed this issue. Please review it.
