### ISSUE TITLE
WA: Tweak EmptyScrape Exception on Events

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1223]
We need to update the check `raise EmptyScrape` on [WA Events](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/wa/events.py) if there aren't events to scrape like there is right now, the logic just needs reworking. May need to add an event counter like in [CA](https://github.com/openstates/openstates-scrapers/blob/7a01f2072477346f85fca10c711a0dd1b3718c2d/scrapers/ca/events.py#L41) or can just go based off the page response like [DE](https://github.com/openstates/openstates-scrapers/blob/7a01f2072477346f85fca10c711a0dd1b3718c2d/scrapers/de/events.py#L71)

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it
