### ISSUE TITLE
DE: Fix Request Permissions issue

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1224]
Right now the DE scrapers are returning with 403 errors on the [get_session_list](https://github.com/openstates/openstates-scrapers/blob/7a01f2072477346f85fca10c711a0dd1b3718c2d/scrapers/de/__init__.py#L139) function because they've updated the website & looks like have added cookies, so may just need to set a cookie & some request headers like in [PR](https://github.com/openstates/openstates-scrapers/blob/7a01f2072477346f85fca10c711a0dd1b3718c2d/scrapers/pr/__init__.py#L55)

**Comment by braykuka** [comment]
@NewAgeAirbender I will work on it

**Comment by showerst** [comment]
We didn't see that you were working on it, we have a fix for this.
