### ISSUE TITLE
AR: Split Sponsors by Entity Type & Chamber

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1231]
In AR we currently add any name that exists in the [Sponsor](https://www.arkleg.state.ar.us/Bills/Detail?id=SB2&ddBienniumSession=2023%2F2024S2) areas on the page and sometimes this is a committee. There should be an added check that `Joint|Senate|House` exists in the sponsor name & if it does, the use of `add_sponsorship` should include the `entity_type="organization"` as well as the proper `chamber`, `upper` for Senate, `lower` for House, and `legislature` for Joint. The check should be in the Primary check on [line 120](https://github.com/openstates/openstates-scrapers/blob/6830b5c7507f3cc20bcb41f636e099e19ee014c7/scrapers/ar/bills.py#L120)

**Comment by braykuka** [comment]
@NewAgeAirbender I will check it.

**Comment by braykuka** [comment]
@NewAgeAirbender I need this environment value to work on this issue. 
AR_FTP_USER, AR_FTP_PASSWORD

**Comment by austinhouck** [comment]
@NewAgeAirbender @jessemortenson this can probably be closed
