### ISSUE TITLE
AK: Split Sponsorship by Chamber

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#1232]
In AK, we already have a [check that](https://github.com/openstates/openstates-scrapers/blob/9acb7e8362211c8b8efc206fde208478060448c4/scrapers/ak/bills.py#L101) `SENATORS|REPRESENTATIVE` exist on a paragraph of Sponsors (ex [HB 3](https://www.akleg.gov/basis/Bill/Detail/33?Root=HB%20%20%203)), & we'd like to update the `add_sponsorship`s on line 107 & 121 include the correct `chamber` like in [ME](https://github.com/openstates/openstates-scrapers/blob/9acb7e8362211c8b8efc206fde208478060448c4/scrapers/me/bills.py#L174), `upper` for the list of Senators & `lower` for Representatives. As with the example bill, sometimes there can be both sponsors from both chambers so it may need to switch which chamber is being added as the sponsors are parsed.

**Comment by braykuka** [comment]
@NewAgeAirbender I will check it.

**Comment by austinhouck** [comment]
@NewAgeAirbender @jessemortenson  this can probably be closed
