### ISSUE TITLE
We will need a new VA scraper in the fall.

### ISSUE THREAD

**Issue by showerst** [openstates/issues#1235]
I received this email from VA, doesn't look like there's any action to take yet until things go live:

Dear SFTP User of the Legislative Information System:

The Division of Legislative Automated Systems (DLAS) has been working with the Senate and House Clerk’s Offices for over 5 years on the replacement of the current Legislative Information System (LIS) that was originally written in 1994. House and Senate Clerk’s Office staff have worked with DLAS to ensure that the data dependencies between our internal legislative processes and LIS remain functional while also verifying all information remains accurate.

We are pleased to inform you that the new and improved LIS will go live on Monday, September 23, 2024.  When accessing the site for the first time, you will see a new homepage, which will be your starting point to explore all the capabilities that “New LIS” has to offer. The 2025 Session will operate in the new platform. Please note that past sessions will continue to operate in the “Legacy LIS” platform, which will be accessible from “New LIS.”  Previous session data (1994 through 2024 Special Session 1) will be moved to “New LIS” in the Spring of 2025, and at that time, “Legacy LIS” will no longer be available.

The implementation of this new version of LIS begins Friday, September 20th at 6:00 p.m. and continues until 7:00 a.m. Monday, September 23rd, during which time LIS will be unavailable. We apologize for any inconvenience this may cause.

 

 

·         You are currently using a Secure FTP process to download LIS data. We are excited to share that the new LIS provides data sharing via modern, programmatic interfaces allowing registered users to securely download publicly available legislative data. We encourage you to obtain data from new LIS via the APIs instead of using the Secure FTP process. You may register for your own LIS API Key by completing the registration information using the link below beginning October 28, 2024. This link will also be available on new LIS.
[LIS API Key Registration](https://lis.virginia.gov/apiregistration)  (prior to 10/28/2024 this link may display an error)
DLAS will monitor and control all activity.

(The CSV export function remains available to all LIS users after new LIS goes live.)

 

 

Getting Started Using the New LIS Website

 

1.    The LIS site URL remains the same: https://lis.virginia.gov/
You will find navigation on the new LIS site has changed. While navigation is very intuitive if you have questions, the HELP/FAQ pages should answer them: http://help.lis.virginia.gov/

2.    If you are an existing Lobbyist-in-a-Box (LIAB) user your settings have been migrated to the new LIS site. Your login credentials have changed:

§  When you log in on new LIS for the first time you will use the e-mail address you registered with instead of your UserID with the password you have been previously using.

You will then be redirected to create a new password.

New passwords must meet the following criteria:

o   10-256 characters

o   Must contain at least three of the following four types of characters:

·         at least 1 lower case letter

·         at least 1 upper case letter

·         at least 1 number

·         at least 1 special character

·         at least 1 upper case letter

3.    If you do not have a LIAB account, click here to establish access and learn more about the benefits of Lobbyist-in-a-Box:
[LIAB Benefits + Registration](https://lis.virginia.gov/register-account) (prior to 09/23/2024 this link may display an error)

4.    If you do not know the e-mail address you originally used to register for Lobbyist-in-a-Box or if you have other questions, you can contact the LIS Help Desk:

§  Phone: (804) 786-9631

§  E-Mail: [LIS@dlas.virginia.gov](mailto:LIS@dlas.virginia.gov)

 

 

Just A Few of the Key Benefits of New LIS

 

The DLAS team has worked diligently to create a new, modernized, more secure, and overall improved LIS experience. Input received from staff of the House and the Senate, and other LIS users, was important during the product development process. Some new and updated features that will save you time, add increased security and improve your overall experience are:

 

·         Advanced Search Capability. New LIS includes many categories and filters within its advanced search function. Within searches you are now able to:

§  Search across a current session using new search criteria within one simplified page.

§  Search for multiple bills at the same time vs. one bill at a time.

§  Search for bills within a status, either in the current session or within a date range across the current session.

·         Cloud Architecture. New LIS leverages cloud architecture technologies, ensuring the site is:

§  Reliable.

§  Flexible.

§  Secure.

·         Enhanced System Security & Safeguards. The new LIS takes advantage of the latest standards and best practices, significantly reducing the risk of system errors and increasing the detection of malicious intrusion.

§  Real-time monitoring and response to ensure optimal system performance.

§  Intrusion detection to prevent unauthorized access to systems and data.

·         User Friendly. The new LIS site is easier for you to find the information you need quickly and easily on any device. What does that mean for you?

§  Mobile Compatibility provides access to the site from anywhere, anytime, on any device.

§  Intuitive Design makes site navigation easy.

§  Well-formatted content.

§  Data loads quickly.

·         Increased Process Automation. Previously required manual entry is reduced in new LIS. Many data transfers and updates have been automated with significant benefits.

§  Reduces and in some cases removes tasks that previously required manual intervention.

§  Saves time.

§  Standardized processes within new LIS reduce the chance for mistakes.

If you should receive multiple communications regarding new LIS, please accept our apologies and thank you for your understanding.

**Comment by austinhouck** [comment]
I've got this one, just received an API key

**Comment by showerst** [comment]
@austinhouck thanks but we already have a working PR for it, just waiting on some infrastructure updates elsewhere. 

If you're interested in contributing, shoot me an email at tim.showers@govhawk.com and I'll copy in @jessemortenson and we can suggest some places where we need the help.

Thanks!
-Tim

**Comment by showerst** [comment]
PR https://github.com/openstates/openstates-scrapers/pull/5051

**Comment by austinhouck** [comment]
Thanks for letting me know, I'll send an email shortly
