### ISSUE TITLE
PA events scraper rewrite 2025

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1239]
Pennsylvania Legislature has a new website up at https://www.palegis.us/ (not sure if URL is temporary) and notes that the old website will only be up until the end of 2024. That means we need a rewrite of the bills scraper.

Scope of this ticket is to re-write https://github.com/openstates/openstates-scrapers/blob/main/scrapers/pa/events.py to target the new site. The scraper should output equivalent (or better/more complete) data than the existing events scraper.

**Comment by braykuka** [comment]
I will work on it.

**Comment by austinhouck** [comment]
@braykuka I already have a PR up for this

**Comment by austinhouck** [comment]
@jessemortenson @showerst this can probably be closed

**Comment by jessemortenson** [comment]
Yup, good point - thanks!
