### ISSUE TITLE
v3 API include params is confusing

### ISSUE THREAD

**Issue by donaldwasserman** [openstates/issues#124]
**Is your feature request related to a problem? Please describe.**
I was playing around with the v3 api, and was looking at the includes here: https://github.com/openstates/api-v3/blob/main/api/bills.py#L173

I was originally trying to access the api using a query param like `includes=votes,documents`, which isn't valid (see the tests here). 

The issue here is that it's not really what you'd expect accessing it, and it would be pretty difficult to construct that url using common http fetching libraries. 

I'm not sure if this is a pydantic issue or an underlying python enum issue or what. I'd be happy to explore this a bit more unless this is the designed behavior

**Comment by jamesturk** [comment]
Thanks for the feedback!

These days  most server side libraries, including FastAPI prefer the
multiple parameters format- i can see why you ike the comma separated list
format but i’m curious about you mentioning the difficulty in sending the
multi parameter request. It’s widely supported from what I’ve seen but if
you can point me at some client libraries that don’t support it i’ll look
into alternatives for those for sure :)

**Comment by donaldwasserman** [comment]
So I guess I am totally out of the loop! I didn't realize (in requests, which is what i'm most familiar with), that it automatically worked that way under the hood, i thought it still serialized `{includes: ['foo', 'bar']}` etc as a comma separated list. 

My apologies!
