### ISSUE TITLE
ND scrape how legislators voted

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1242]
Currently, the ND scraper for votes does not scrape data on how individual legislators voted ([see todo note](https://github.com/openstates/openstates-scrapers/blob/a2b6f8a7febfe03891e8cadaaf75729b442fa1f2/scrapers/nd/votes.py#L10)). Our goal here is to ensure that VoteEvent objects get individual votes added via the `vote()` or `yes()`/`no()` methods on that class.

But it looks like ND does have Roll Call views that list legislators' votes. See for example the [Actions tab for HB 1547](https://ndlegis.gov/assembly/68-2023/special/bill-actions/ba1547.html?bill_year=2023ss&bill_number=1547) and click the links for the two votes:

- 80-12-2
- 34-13-0

Clicking one of those triggers an overlay to display that lists how each legislator voted.

**Comment by braykuka** [comment]
I am working on it.
