### ISSUE TITLE
opencivicdata_bill.locked_fields does not exist

### ISSUE THREAD

**Issue by azban** [openstates/issues#125]
i haven't had a chance to dig into this yet, but in case this minimal amount of info is helpful, we started seeing this randomly for certain queries. if needed, I can try to reproduce the query and the full response.

```
LINE 1: ...ill"."updated_at", "opencivicdata_bill"."extras", "opencivic... ^ : {"response":{"errors":[{"message":"column opencivicdata_bill.locked_fields does not exist\nLINE 1: ...ill\".\"updated_at\", \"opencivicdata_bill\".\"extras\", \"opencivic...\n ^\n","locations":[{"line":3,"column":9}],"path":["bills"]}],"data":{"bills":null},"status":200},"request":{"query":"\n {\n bills(last: 1, jurisdiction: \"New York\", session: \"2019-2020\") {\n pageInfo {\n hasNextPage\n hasPreviousPage\n endCursor\n startCursor\n }\n totalCount\n }\n }\n "}}
```

**Comment by jamesturk** [comment]
This should have been an intermittent issue during a migration that took about 7 minutes- let me know if you can reproduce now. Sorry for the unexpected downtime.

**Comment by azban** [comment]
no worries. just making sure it wasn't something persistent. will re-open this if i see it again. thanks.
