### ISSUE TITLE
AR bills scraper missing bills

### ISSUE THREAD

**Issue by showerst** [openstates/issues#1276]
AR is not currently getting all bills, it's missing a few of the newest ones.

I've tracked this down to the fact that [get_utf_16_ftp_content](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/ar/bills.py#L503C9-L503C31) in the scraper is truncating the file LegislativeMeasures.txt.

I have a branch going that saves that file to disk instead of deleting it, and prints it, and everything i can do in python truncates it, whereas if i 'cat' it from the command line or open it in vscode it looks fine.

Opening it in https://hexed.it/ I don't see any weird bytes there. I'm stumped. @jessemortenson any ideas? 

My debug branch:
https://github.com/openstates/openstates-scrapers/pull/5146/files

**Comment by jessemortenson** [comment]
Huh, very weird. Good job catching it. I haven't had a chance to look hands on yet (made a quick attempt to connect to their FTP and keep getting timeouts, have you seen that?). I forget, is the file format CSV? Might be a dumb suggestion if there is a low-level file reading problem, but I've enjoyed using DuckDB (which has a python library) for reading flatfiles lately

**Comment by jessemortenson** [comment]
Should be fixed per Bray's PR, see notes there
