### ISSUE TITLE
v3 /jurisdictions failing for "New York"

### ISSUE THREAD

**Issue by azban** [openstates/issues#136]
not sure what's going on, but using the name, rather than the abbreviation for New York is failing.

https://v3.openstates.org/jurisdictions/New%20York?include=legislative_sessions -> 500
https://v3.openstates.org/jurisdictions/ny?include=legislative_sessions -> 200

doesn't seem to be a general encoding issue because 'Puerto Rico' is working fine.

**Comment by jamesturk** [comment]
ah, I think I know what's going on- I need to enforce that the name-only lookup specifies state-jurisdictions only.  thanks for the heads up

**Comment by azban** [comment]
sounds good. adding a classification flag and an error indicating that we need to pass the classification to disambiguate also works, if you think it would be better to be more explicit.

**Comment by jamesturk** [comment]
deployed the fix
