### ISSUE TITLE
Turn off Indiana Scraper Oct 7-9

### ISSUE THREAD

**Issue by showerst** [openstates/issues#138]
I just received this email from the Indiana Legislative Services team, and wanted to be sure you saw it @jamesturk 

----
The Indiana General Assembly will be conducting an information system test between October 7th and October 9th, 2020.   During this exercise, we will create test data in the production system.  Only test data will be entered during that timeframe, and any of the test data you may pull from our API during these three days should be discarded.

....

------

So we should disable scrapes for the next few days.

**Comment by jamesturk** [comment]
👍 leaving this open to turn back on next week
