### ISSUE TITLE
Inventory extras

### ISSUE THREAD

**Issue by showerst** [openstates/issues#14]
We should grep through the codebase for any place we're adding 'extras' to an object, and see if that deserves a better structure, or is best left as an extra.

I can take this on in the coming weeks.

**Comment by jamesturk** [comment]
# Bill Extras

- CA: impact_clause, tags, vote.threshold
- DC: lawNumber
- DE: amendment, substitute
- FL: places
- GA: guid, action.code, action.guid
- KS: status
- KY: BDR (bill draft request)
- MD: date_effective
- ME: ld_number
- MS: summary
- MT: many including: chapter, drafter, fiscal note, bill draft number, by request of
- NH: sponsor codes
- NV: BDR, NV_ID
- UT: _vote_id
- WI: status
- WY: billInformationId, enrolled_number, chapter, effective_date, wy_bill_id

**Comment by jamesturk** [comment]
People: occupation should probably be promoted, most other extras are obsolete or really unique (e.g. children)

**Comment by jamesturk** [comment]
re: bills, At the moment not particularly motivated to promote any of these, @showerst let me know if there are any you have in mind.

I'm undecided on Person.occupation, but leaning no for now as well as I think it is fine in extras, but I'm about 50/50 on it and could easily be swayed

**Comment by showerst** [comment]
I think they're all fine as is. I think i have another bug open about potential citations / law citations that i'd like to revisit, but I don't see my team getting to that before the new sessions, so no rush.

**Comment by jamesturk** [comment]
Alright, closing for now in favor of handling these as needed - definitely up to adjust the schema for law citations when you all are ready
