### ISSUE TITLE
Alabama 2021 Session

### ISSUE THREAD

**Issue by jchapman146** [openstates/issues#142]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:** There is a second Alabama 2020 session listed, but this is really the 2021 session. While the links look correct the data being displayed says 2020 Regular Session 

**URL where this issue may be seen (API or OpenStates.org):** https://openstates.org/al/bills/?session=2021rs

**Source URL of correct data if applicable:** https://openstates.org/al/bills/2021rs/HB2/ 
![image](https://user-images.githubusercontent.com/65787165/95484956-f56eba00-0945-11eb-8ece-17ac50dce749.png)

**Comment by showerst** [comment]
This is a scraper bug in scrapers/al/__init__.py -- the 2021 session has the wrong name. Probably a cut & paste error by yours truly.

@jamesturk not sure if just updating the scraper will fix this or if you need to change the DB entry, i'll hold off on a patch until you clear it to make sure it wouldn't generate dupes.

**Comment by jchapman146** [comment]
Thanks for responding so quickly. I will keep an eye out for the fix.

Thanks!

**Comment by jamesturk** [comment]
Updating the name should be fine, thanks for catching this!

**Comment by jamesturk** [comment]
looks good now!
