### ISSUE TITLE
LA 2020s2 bills missing, change scrape task config

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#145]
**Issue Description:** Query for Louisiana 2020s2 returns no bills, yet some [appear to be filed](https://legis.la.gov/legis/BillSearch.aspx?sid=LAST) 

Looks like the scrape task is configured to always run `2020` even though the scraper is configured with `2020s2` as the most recent session. Changing config should do the trick. (I don't think regular session 2020 is open any longer)

**URL where this issue may be seen (API or OpenStates.org):** https://openstates.org/la/bills/

**Source URL of correct data if applicable:** https://legis.la.gov/legis/BillSearch.aspx?sid=LAST

**Comment by jamesturk** [comment]
these are live now
