### ISSUE TITLE
VA FTP scraping is flaky 

### ISSUE THREAD

**Issue by mollycode** [openstates/issues#149]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Sometimes VA ftp appears to be down causing the scraper to fail ~2-3 times a week lately.

Related discussion [here](https://github.com/openstates/openstates-scrapers/pull/3449) and change to cron frequency PR [here](https://github.com/openstates/task-definitions/commit/7047de601fa4be7cc8976d60ddc91402fbd3ebec) 

Filing issue just to follow up and make sure VA is now stable.

**Comment by jamesturk** [comment]
looks like altering the times/etc. fixed this, no failures in the last few weeks: https://bobsled.openstates.org/task/VA-scrape

**Comment by jamesturk** [comment]
marking this as resolved, we can re-open as needed if it gets bad again
