### ISSUE TITLE
Changes to the version/document data model

### ISSUE THREAD

**Issue by showerst** [openstates/issues#15]
I propose we add an enum to versions and documents to clearly identify some common version/document types --

Versions: amendment, substitute, enrolled, "final one that became law"
Documents: fiscal note, committee report, synopsis

**Comment by jamesturk** [comment]
if this is still of interest & you all have cycles to collaborate on this I'd be glad to pick it up

**Comment by showerst** [comment]
Sure, what would be most helpful? I may be too busy this week to PR the change but happy to provide some ideas for the types.

**Comment by jamesturk** [comment]
Yeah, ideas for the types would be great- I'm not in a big rush to get this
in but trying to move on a few of these schema-type things that were harder
to do before the move to openstates-core

**Comment by showerst** [comment]
I went through all the scrapers and our data and took a look --

For bills --

### Versions:

- prefiled [1]
- introduced
- amendment [2]
- substituted
- enrolled
- became-law

[1] - Maybe this should be filed to match the status.

[2] - I'm thinking of amendment not as 'amended version of the bill' which is most versions, but cases where they _only_ publish amendment instructions.

For my cases the biggies there are:

substitutes, amendments, and became-law -- those fit the common use cases of 'i need to see (or filter out) recent amendments', 'oh was this bill substituted with something totally different' and 'what was the final final text of this'

There's substantial overlap here with action classes, but I figure having the extra metadata on the versions is also pretty useful.

### Documents:

- fiscal-note
- committee-report
- summary
- digest
- veto-message
- analysis
- law

If you're in the mood to mess with events too -

### Documents

- agenda
- minutes
- witness-list

Code wise I was envisioning something simple --

```py
bill.add_version_link(
    name="HB 123 ENR",
    url="https://google.com/enr.pdf",
    media_type='application/pdf'
    classification='enrolled',
)
```

**Comment by jamesturk** [comment]
this behavior was added in openstates-core 5.1.0 and is now available
