### ISSUE TITLE
CT State Official data out of date

### ISSUE THREAD

**Issue by kaddae** [openstates/issues#157]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

Phone number OOD for --> https://openstates.org/person/roland-j-lemar-1C3JFNLDqyjQOC9sEj5NLm/

assume this is the case for other state officials. 

Updated data -> https://www.housedems.ct.gov/Lemar

Can be pulled from - https://www.housedems.ct.gov/find

**Comment by jamesturk** [comment]
rolling into #160
