### ISSUE TITLE
Bill updated_at timestamps are in the future (UTC +6?)

### ISSUE THREAD

**Issue by azban** [openstates/issues#168]
i'm seeing updated_at timestamps in the future consistently on bills in v2 and v3. it seems like i need to shift the timestamp by -6 hours for all updated_at's to be before the time of the query. can provide more historical data on this, if helpful.

running this query at `16:53:53+00:00`:
```gql
{
  bills(first: 2) {
    edges {
      node {
        updatedAt
      }
    }
  }
}
```
returns:
```json
{
  "data": {
    "bills": {
      "edges": [
        {
          "node": {
            "updatedAt": "2020-11-19 20:16:21.905422+00:00"
          }
        },
        {
          "node": {
            "updatedAt": "2020-11-19 20:16:21.801885+00:00"
          }
        }
      ]
    }
  }
}
```

**Comment by jamesturk** [comment]
can confirm this is the case in the database as well, definitely a TZ issue on save

**Comment by jamesturk** [comment]
fix incoming, i'll check dates tomorrow and see if they look correct

**Comment by jamesturk** [comment]
This looks like it is fixed-- there was an ECS infrastructure issue last night so minimal updates but a manual CO run today has the correct timestamp on the updated bills.  If any others resurface let's reopen as needed.
