### ISSUE TITLE
MA: House districts should be abbreviated

### ISSUE THREAD

**Issue by bhrutledge** [openstates/issues#170]
**Issue Description:** In [the Massachusetts `people` scraper](https://github.com/openstates/openstates-scrapers/blob/870bf5283ac650c98252a574f439c8e66bb5eb6e/scrapers/ma/people.py#L6), there's a `clean_district` function that turns things like "27th" into "Twenty-Seventh". However, that changes the canonical name of the House districts (which are abbreviated), which makes them harder to distinguish from Senate districts (which are not abbreviated), and to join with external data sources.

**URL where this issue may be seen (API or OpenStates.org):**

- https://openstates.org/ma/legislators/?chamber=lower
- https://openstates.org/person/denise-provost-6aaS5O4fAbRvIqGh8XntjW/

**Source URL of correct data if applicable:**

- https://malegislature.gov/Legislators/Members/House
- https://malegislature.gov/Legislators/Profile/D_P1/District
- https://en.wikipedia.org/wiki/Massachusetts_House_of_Representatives%27_27th_Middlesex_district
- https://docs.digital.mass.gov/dataset/massgis-data-massachusetts-house-legislative-districts

**Comment by jamesturk** [comment]
Thanks, this is enlightening -- I don't recall how this decision was initially made, I assume it was to be consistent but it does look like the state sources you provided are pretty consistent in treating them this way.  We'll need to adjust the people data accordingly, which might take a little while as I don't want to break the find your legislator tool/etc. for that, so I'll need to double check special cases/etc. that might exist.

**Comment by bhrutledge** [comment]
@jamesturk Thanks for considering this. Is there anything I can do to facilitate?

I know of at least one project that could by affected: https://scorecard.progressivemass.com/. Poking through their [source code](https://github.com/ProgressiveMass/legislator-scorecard/) makes me optimistic that they're just passing API value through to the frontend, so hopefully this would not be a breaking change.

Also, FWIW, I have a personal project that probably would be using your API, but IIRC the district mismatch prompted me to roll my own scraping: https://github.com/bhrutledge/ma-bill-sponsors.

**Comment by bhrutledge** [comment]
On a whim, I opened https://github.com/openstates/openstates-scrapers/pull/3476.

Also, could the investigation part of this be rolled into #160?
