### ISSUE TITLE
updated_at shouldn't update if data hasn't changed

### ISSUE THREAD

**Issue by jamesturk** [openstates/issues#171]
As discussed between myself, @azban and @showerst -- scraped data should be consistent between runs.  To start with this, we'll figure out places that ordering isn't preserved but sorting would fix them.  @azban has some examples that could get us started.

**Comment by jamesturk** [comment]
Virginia currently exhibits the issue of 75 bills out of 1743 on every scrape (~5% churn), and is a good candidate to figure out where that is happening.  

Current lead is pointing towards issues with actions.order -- it seems like ordering of classifications isn't causing these.


ordering of classifications might also be an issue, will need to try other states and possibly randomizing PYTHONHASHSEED

**Comment by azban** [comment]
here are some of the various places i found where we were not sorting but had enough info to sort to address the issue: https://gist.github.com/azban/a11d9ae8776d3feb779e681d0dbaaacf

this worked for a lot of the bills, but there was a tail end of issues specific to jurisdictions (like AZ), that needed to be covered.

```
actions:
  - classification
  - order
votes:
  - voter_name
  - count
  - (sometimes needs source_url, in the case of AZ)
sources:
  - url
versions:
  - date
  - note
```

do you have intuition on where this would be better addressed on the scraping side, the post-processing side, or some combo (like AZ could have a custom votes sorter)?

**Comment by jamesturk** [comment]
https://bobsled.openstates.org/run/24fe4a753d334b60bfca4748ec7a6ee5 shows VA running with all no-op bills, the issue is fixed for VA & other states experiencing this problem 🎉 

will revisit after another day's worth of scrapes to judge severity of remaining problem

**Comment by jamesturk** [comment]
@azban I haven't tackled the sorting issue yet, in most cases it isn't used to set updated_at in the import code so i think a lot of these might be other issues.  Where it is the sort order, I think it'll be doable mostly within the core import code.

**Comment by jamesturk** [comment]
judging by my SQL query we're in better shape today but there are still a few outstanding issues

yesterday 49 jurisdictions had updates within the last 24 hours, today it is down to 32 (of course no way of knowing how many should, but this seems sane)

2 states (OK, TN) still basically having every bill update while a few others (MT, WA, ND) look pretty high.  Whatever is causing complete churn in Oklahoma & Tennessee is today's focus

**Comment by jamesturk** [comment]
A huge % of what remains does appear to be the sorting of classifications, after a bit of experimentation sorting is now done before writing JSON (turns out we already had a cleanup list that was used in the right places, so a really easy fix)

I think with that a huge # of false positives will be resolved, going to table this over the weekend and check on Monday (thought being that very few real updates should have happened Sunday, so false positives will stand out a bit more)

**Comment by jamesturk** [comment]
For future reference, there are 4 different concepts when things exhibit the updated_at churn behavior:
- updates with --import: these are bills that import funny, even identical JSON the state sees updates
- updates with --fast: even with the same HTML, the state sees updates
- updates when not --fast: subtle changes in site/html/etc. create updates, hard to track down but can compare JSON between two scrapes and see changes that don't need to be reflected
- non-reproducible updates: likely upstream?  not reproducible on a regular basis

After fixing classification sorting issue the top suspects for updated_at churn are:

- Virginia	1934  (100%)
- West Virginia	1180 (100%)
- Washington	720 (~66%)
- Florida	243
- Nevada	178
- North Dakota	55

Possibilities that some of these are valid, but every other state is below 25 updates right now, which seems pretty valid.  

Virginia is non-reproducibly updating 100% of it's bills.  This could actually be a source issue since it isn't consistent between our scrapes.  Two scrapes a few hours apart resulted in 38 bills updated, followed by 1934 bills updated.  The 38 of course seems valid, but I don't yet have full data on what happened when 1934 were, added more local instrumentation to better capture differences.

Washington has 91 that are stuck as updating on --import.
Another ~600 that are churning with --fast.

**Comment by jamesturk** [comment]
Washington was probably 100% subject ordering, fixed in 5.5.2

**Comment by jamesturk** [comment]
note: subject ordering will result in an increased updated_at this one time (likely changing a bunch of states that were stable but unsorted to sorted order). 

looking into remaining churn from Sunday, but will have to next check numbers in ~24 hours after each state has run at least twice

**Comment by jamesturk** [comment]
As of today, no state has updated more than 10%* of it's bills in the last 24 hours.  This seems right for this point in the session, and rules out a fourth systemic issue of the size of the three already fixed.  I'm going to mark this as resolved, and we'll open more detailed issues if/when we find state specific or more narrow causes.

(Of what's left, Indiana is highest at 12%, but it runs more slowly and with lots of failures in between runs so I think it looks valid.  Florida and NY are around 10%, which could point to state-specific issues that could be investigated further if they continue to cause issues, but I think that there is no longer a system-wide cause of this churn.)

I also took a look at Votes, but they do not seem to be having this issue, at least not right now (possibly that the issue is small due to the low number of overall votes, but it doesn't look systemic even in that case).

For future reference the three major issues affecting 30%+ of bills collectively:
- bills with identically-named actions were churning because of an ordering bug
- all classifications (Bill, VoteEvent, BillAction) were in non-determinate order, now sorted in JSON
- subjects were in indeterminate order, now sorted in JSON
