### ISSUE TITLE
North Carolina senator/representative image links not working

### ISSUE THREAD

**Issue by benbadio** [openstates/issues#174]
**Issue Description:** 
Image links currently in use for North Carolina senators and representatives are invalid. The problem is that the provided links are structured incorrectly. 

Take for example, NC State Representative Allen McNeill. This is the link provided for his image:

http://www.ncleg.net/House/pictures/hiRes/635.jpg

The link should actually be the following:

https://www.ncleg.gov/Members/MemberImage/H/635/High

The same is true for NC state senators, and may also be true for other NC "people", though I have not checked.

**URL where this issue may be seen (API or OpenStates.org):**

https://v3.openstates.org/people?jurisdiction=ocd-jurisdiction%2Fcountry%3Aus%2Fstate%3Anc%2Fgovernment&page=1&per_page=10

Note: This url represents a sampling of api results with this issue. I'm fairly certain this affects the people response objects of all NC senators and representatives.

**Source URL of correct data if applicable:**
Here's how links should be structured, using State Rep Allen McNeill and State Senator Andy Wells. Just replace the 3 digit number with the number corresponding to the senator/representative:

For representatives - https://www.ncleg.gov/Members/MemberImage/H/635/High

For senators - https://www.ncleg.gov/Members/MemberImage/S/388/High

**Comment by jamesturk** [comment]
Thanks for reporting this, should be a fairly low-hanging fix to the data in openstates/people for someone if they have a chance before a core team member gets to it.

**Comment by jamesturk** [comment]
this is now fixed in source data
