### ISSUE TITLE
Add 'related' as a new bill relation type

### ISSUE THREAD

**Issue by showerst** [openstates/issues#181]
This is mostly as a reminder to me -- some times we run across bills that have related bills, but they don't fit the enum in 
https://github.com/openstates/openstates-core/blob/082210489693b31e6534bd8328bfb895427e9eed/openstates/data/common.py#L93

So maybe add either a catch-all "related" or enrich that enum a bit.

**Comment by jamesturk** [comment]
to mirror what we do with other places where we can't classify (e.g. actions or vote types) would it work for you to allow an empty classification?  I can do that in core next time I'm digging around in there

I'm also up for adding any new classifications if we know what they are

**Comment by showerst** [comment]
That seems like a good solution to me, this bug was specifically in response to the federal bill xml where they list 'related' bills that are usually on a similar subject matter, but they're not like companions or anything.

So no rush on it from my end but if you knock it out incidentally that would be great, I imagine there's a state or two where that applies as well.

**Comment by jamesturk** [comment]
I was wrong about how this worked, it is already a single-value relationship so I added "related" as a catch-all for now

**Comment by showerst** [comment]
thanks!
