### ISSUE TITLE
import/export tool to empower non-technical volunteers to update openstates/people data

### ISSUE THREAD

**Issue by beatthat** [openstates/issues#188]
**Is your feature request related to a problem? Please describe.**

There are many politically engaged but non-technical volunteers who would contribute their time to make openstates people data as accurate as possible, but we can't ask them to fork a git repo, create a branch, edit yaml, run scripts, do a pull request, etc. 

We can, however, give them a link to an online [airtable](https://airtable.com/)<sup>1</sup>--prepopulated with some subset of OS people data--and ask them to check and update contact details, etc. for existing openstates `person` records.

This issue proposes a new airtable import/export tool that will allow for airtable-based workflows where non-technical volunteers can edit the details of existing `people`, e.g. update the contact info or end of term for an openstates `person` who has just been reelected to their office.

**Describe the solution you'd like**

1. technical person
    - forks [openstates/people](https://github.com/openstates/people) and creates a branch
    - runs a `airtable-create-from-clone`<sup>2</sup> script that creates an airtable populated with [some subset of] openstates `people` from the cloned branch
    - provides volunteers with link to the airtable and instructions on editting
1. volunteers make edits via airtable to contact details, etc. for people
1. technical person
    - runs `airtable-sync-to-clone` script to sync vounteer-updated data from airtable back to the cloned branch
    - checks diff to ensure changes look valid
    - commits + pushes changes
    - creates a PR back to openstates

NOTES:

1. assumption here is that scenarios described could fit within the limits of a free-tier airtable account that any person or org could create as needed.
2. `airtable-create-from-clone` would take args like `--state=ca --branch=municipalities`

**Describe alternatives you've considered**

Have considered doing all of the above and hosting the scripts in an external (non OS) repository, but it seems like the scripts would work more naturally if they lived beside other import/export tool scripts in the [openstates/people](https://github.com/openstates/people) repo. Also, would be useful to get feedback from core openstates maintainers on the proposal before I put work into it.

**Additional context**

I'm offering to write the proposed import/export scripts, associated tests, and documentation in a fork/PR.

Obviously this is only meant to supplement and not alter or replace the existing import/export tools in openstates/people. It's really about enabling a different type of volunteer to contribute to the project.

I believe this should have label `component:people-infrastructure` based on the README list of components

**Comment by jamesturk** [comment]
This sounds great, I'm not that familiar with Airtable, but if you think the workflow could be similar to what you're saying it is essentially a missing piece of this that I'd long hoped to find time to build- but had planned something that interacted with Git directly.  Doing it this way would be fantastic, I'd be glad to be involved in any conversations about planning/etc. that are needed.    Let me know if you want to chat at some point to discuss, or have any questions!

**Comment by beatthat** [comment]
great. will get started on this this weekend

**Comment by beatthat** [comment]
@jamesturk I have a question that applies to three of the properties in `openstates/people` documents:

For the list fields `party`, `links`, and `sources`, are the list-item values ever more than a single string?

For example, every `party` record I've found looks like this:

```yaml
party:
  - name: Republican
```

...and every `links` or `sources` entry I have found looks like this:

```yaml
links:
- url: http://assembly.state.ny.us/mem/?sh=email
sources:
- url: http://assembly.state.ny.us/mem/Kieran-Michael-Lalor
```

...it makes like easier if I can assume those list-fields are just lists of strings when they're in airtable and then convert them back to single-entry dictionaries when they data comes back down to yaml.

Let me know what you think.

**Comment by jamesturk** [comment]
Technically, we can support additional values there, party memberships can
have start/end dates, links can have notes.  They are rare, but do occur.

I'm not so much concerned about people being able to edit them as much as the fact
that the process sounds like it'd be lossy if it couldn't support at least
keeping the values as they were.  That'd be an issue for people that have
switched party in particular as it'd drop the end date on their old
membership.

**Comment by jamesturk** [comment]
Wanted to check in on if you think you'll continue with this.  No worries either way, but we're making plans for tooling & not sure if this will be in a state to evaluate.

**Comment by beatthat** [comment]
Hey, I'm not going to have the time necessary to carry this forward. Feel free of course to use the existing branches if there's anything there useful for you

**Comment by jamesturk** [comment]
Thanks, appreciate you taking the time & we’ll figure out what we can do with the existing airtable work

**Comment by jamesturk** [comment]
this work inspired the addition of OSEP #003 https://github.com/openstates/enhancement-proposals/blob/main/drafts/003-manual-people-data-tools.md

closing this issue in favor of where we're heading with that 👍

**Comment by beatthat** [comment]
hey that's great! look forward to seeing that in use for resistbot
