### ISSUE TITLE
add "hidden" bill classifications for certain types of bill

### ISSUE THREAD

**Issue by jamesturk** [openstates/issues#193]
Primarily stemming from Montana's prefiles, where LCs are numerous and we want to capture them, but they aren't quite full bills.  We want to ensure that there's a way to scrape certain classifications of bills but give people a way to exclude them as needed, possibly even excluding them by default.

Steps:

- [x] decide upon classification ("proposed bill" exists, or we could add "bill request")
- [x] update Montana scraper to use this classification for LC
- [x] have openstates.org exclude these by default
- [x] decide how API should handle them, either excluded by default with a way to request them, or included with a way to exclude them

cc @showerst @jessemortenson

**Comment by jamesturk** [comment]
we'll use existing `proposed bill` for MT LCs, others may need to be added/documented as well

**Comment by showerst** [comment]
While we're on the subject, I'd like to update HI to capture [governor's messages](https://www.capitol.hawaii.gov/advreports/advreport.aspx?year=2020&report=deadline&rpt_type=&measuretype=gm&title=Governor%27s%20Messages) which is a weirdo state specfic mixed-type, that can be an appointment, a budget modification, or something else. 

These might fall into the same bucket as MT prefiles where they're not relevant, i'm not sure.

They are picked up by committees and voted on by the legislature though. I haven't figured out a good type yet, maybe we can scan the title and go with either 'nomination' or 'bill of address'.

**Comment by jamesturk** [comment]
Those look good to include to me.  I think I'll hide the proposed bills in the OS.org UI, but leave them as-is in the API.  I think that means that from your end Jesse, you can just add them to the MT scraper and folks can just choose to exclude/include them as they choose if they're using API or JSON.

**Comment by jessemortenson** [comment]
Incidentally looks like NH is another example that has proposed bills though the data available is just title, chamber and sponsors ("Legislative Service Requests") http://www.gencourt.state.nh.us/lsr_search/LSR_Results.aspx

**Comment by jamesturk** [comment]
MT gov messages look good to me, I'm getting a timeout on NH LSRs right now but will check back later

The more I think about these the more I think being liberal with what we accept but clearly label them is the right approach, they're unlikely to cause much harm and are easy enough to filter out for API consumers/etc. that don't want them.  OpenStates.org will filter certain bill types but the API/bulk data will remain complete.

**Comment by jamesturk** [comment]
going to close this as I think the core issue here is resolved now, anything with classification="proposed bill" will not show up on openstates.org and can be filtered easily by API users
