### ISSUE TITLE
VA not capturing sponsorships consistently

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#196]
**Issue Description:** Looks like sponsors are missing from bills that the VA website indicates should have at least one sponsor. Looking at about 20 bills on the VA site, all have at least one sponsor ("patron"), the person who introduced the bill. So I think any bill in OS data that lacks sponsors is probably suspect.

**URL where this issue may be seen (API or OpenStates.org):**

https://openstates.org/va/bills/2021/HB1751/
https://openstates.org/va/bills/2021/HB1737/

**Source URL of correct data if applicable:**

https://lis.virginia.gov/cgi-bin/legp604.exe?211+sum+HB1751
https://lis.virginia.gov/cgi-bin/legp604.exe?211+sum+HB1737

**Comment by jamesturk** [comment]
spent a bit of time calling around this morning and eventually spoke to their LIS dept, confirmed that the sponsors shouldn't be missing from CSVs and they believe it is a data issue on their end.  Should hear back soon

**Comment by jamesturk** [comment]
after one more conversation, looks like there's an edge case where single sponsors are omitted from Sponsors.csv.  adding a workaround using summary data

**Comment by jamesturk** [comment]
fixed!
