### ISSUE TITLE
VA 2021 bill versions named "Impact statement" not actually impact statements

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#197]
**Issue Description:** VA 2021 appears to have about 280 bills with one version where the `note` is something like "Impact statement from...". However, the URL in `links` for that version actually points to a bill text document. (There is also an Impact statement document, but it's a different URL).

**URL where this issue may be seen (API or OpenStates.org):**

https://openstates.org/va/bills/2021/HB1532/
"impact statement" links to https://lis.virginia.gov/cgi-bin/legp604.exe?211+ful+HB1532
but that URL is actually labeled "01/10/20  House: Presented and ordered printed 20105202D" on the VA website

Impact statement URL actually would be: https://lis.virginia.gov/cgi-bin/legp604.exe?211+oth+HB1532F122+PDF

**Source URL of correct data if applicable:**

https://lis.virginia.gov/cgi-bin/legp604.exe?211+sum+HB1532

**Comment by jamesturk** [comment]
the document name matching code is definitely wrong.  trying to sort out if there's a better key or if our document names are going to be uglier

**Comment by showerst** [comment]
https://github.com/openstates/openstates-scrapers/blob/master/scrapers/va/csv_bills.py#L347

I think this loop needs to be short circuited so we match the version to the first action that contains the bill code. That way if they post a fiscal impact or other related doc in a later action, we don't overwrite the name.

Haven't had time to test yet, so feel free to beat me to it =).

**Comment by jamesturk** [comment]
It turns out they aren't actually including the same code in the two CSVs, but it looks like if there's a document id (8 digits then a D) with the same date that's the action that corresponds to the bill.  

Just pushed that fix to a branch, we weren't actually grabbing Fiscal Notes, so working on that small addition now

**Comment by jamesturk** [comment]
fix for this is pushed, bill versions are actually versions and labeled as best we can, fiscal Impact statements added

**Comment by jamesturk** [comment]
verified in the scrape
