### ISSUE TITLE
People search 'filter by name' does not work

### ISSUE THREAD

**Issue by harrymattison** [openstates/issues#198]
The first person returned by this query is `"name":"Aaron Michlewitz"`
```
curl -X GET "https://v3.openstates.org/people?jurisdiction=Massachusetts" -H  "accept: application/json" -H  "x-api-key: KEY"
```

But when the `name` filter is added to search for someone named `aaron`, nothing is returned
```
curl -X GET "https://v3.openstates.org/people?jurisdiction=Massachusetts&name=aaron" -H  "accept: application/json" -H  "x-api-key: KEY"
```

**Comment by jamesturk** [comment]
just confirmed, right now this is an exact match, it should be a fuzzy search to match v1 and v2 behavior

**Comment by jamesturk** [comment]
pushed a fix for this, thanks for reporting!
