### ISSUE TITLE
Scraper regression tester?

### ISSUE THREAD

**Issue by estaub** [openstates/issues#20]
In working on scrapers I often find that they could use some serious refactoring, but I'm too scared of breaking something to take it on.  It seems like some kind of regression testing framework might help.

I'm thinking of a framework that would run a current subscraper, then run the new subscraper, and compare for unexpected differences.  By "subscraper" I mean e.g. a bill scraper, vote scraper, people scraper, or whatever.

This would obviously be for manual use in the development process, not e.g. from Travis CI testing.

Does such a thing exist already somewhere?

This may belong better in pupa; I think it makes sense to rough it out here, first, though.

**Comment by jamesturk** [comment]
hoping to integrate this as part of #85
