### ISSUE TITLE
WA ~30 bills missing bill versions in 2021-2022 session

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#203]
**Issue Description:** About 30 bills appear to be missing versions in 2021-2022 data. Spot checking a few, it seems like versions *are* posted on the source website.

    SB 5000
    SB 5001
    SB 5002
    SB 5003
    SB 5004
    SB 5005
    SB 5006
    SB 5007
    SB 5008
    SB 5009
    SB 5010
    SB 5011
    SB 5012
    SB 5013
    SB 5014
    SB 5015
    SB 5016
    SB 5017
    SB 5018
    SB 5019
    SB 5020
    SB 5021
    SB 5022
    SB 5023
    SB 5024
    SB 5025
    SB 5026
    SJM 8000
    SJR 8200
    SJR 8201

**URL where this issue may be seen (API or OpenStates.org):**

https://openstates.org/wa/bills/2021-2022/SB5015/
https://openstates.org/wa/bills/2021-2022/SB5026/

**Source URL of correct data if applicable:**

https://app.leg.wa.gov/billsummary?BillNumber=5015&Year=2021&Initiative=false
https://app.leg.wa.gov/billsummary?BillNumber=5026&Year=2021&Initiative=false

**Comment by showerst** [comment]
Taking a look at this now. My guess is the self.versions dict is getting overridden between chambers.

**Comment by jamesturk** [comment]
confirmed in scrape, thanks @showerst !!
