### ISSUE TITLE
Redis is not configured in API v3 Docker images

### ISSUE THREAD

**Issue by jdubansky** [openstates/issues#206]
This is the right template to select if you're reporting an issue with the functionality of the v3 API.
If this is a data issue, please select data issue instead!

**API Query (be sure to omit API key!!!):**
```
http://localhost:7000/jurisdictions?classification=state&include=&page=1&per_page=52&apikey=
```
If I use a key that is revoked it tells me the key is wrong but when I use a valid key it throws this error: 
`api_1  | 172.19.0.1:59420 - "GET /jurisdictions?classification=state&include=&page=1&per_page=52&apikey=****KEY HTTP/1.1" 500
api_1  | [2020-12-27 03:55:28 +0000] [9] [ERROR] Exception in ASGI application
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
api_1  |     result = await app(self.scope, self.receive, self.send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
api_1  |     return await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 179, in __call__
api_1  |     await super().__call__(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
api_1  |     await self.middleware_stack(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
api_1  |     raise exc from None
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
api_1  |     await self.app(scope, receive, _send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
api_1  |     await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
api_1  |     raise exc from None
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
api_1  |     await self.app(scope, receive, sender)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
api_1  |     await route.handle(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
api_1  |     await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
api_1  |     response = await func(request)
api_1  |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 176, in app
api_1  |     dependency_overrides_provider=dependency_overrides_provider,
api_1  |   File "/usr/local/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 552, in solve_dependencies
api_1  |     solved = await run_in_threadpool(call, **sub_values)
api_1  |   File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
api_1  |     return await loop.run_in_executor(None, func, *args)
api_1  |   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
api_1  |     result = self.fn(*self.args, **self.kwargs)
api_1  |   File "/app/api/auth.py", line 41, in apikey_auth
api_1  |     limiter.check_limit(provided_apikey, key.api_tier)
api_1  |   File "/usr/local/lib/python3.7/site-packages/rrl.py", line 81, in check_limit
api_1  |     result = pipe.execute()
api_1  |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 4013, in execute
api_1  |     self.shard_hint)
api_1  |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
api_1  |     connection.connect()
api_1  |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 563, in connect
api_1  |     raise ConnectionError(self._error_message(e))
api_1  | redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
`

**Comment by jdubansky** [comment]
When I went back to this version of auth.py it looks like it works.

https://github.com/openstates/api-v3/blob/f3f951b2dbe9160301c01eaa339aafea93eb74ed/api/auth.py

**Comment by jamesturk** [comment]
updated name of task to reflect this is an issue w/ Redis in the docker-compose, not with the API

**Comment by jamesturk** [comment]
should be fixed by https://github.com/openstates/api-v3/pull/7

 I'll need to mess with my local setup to try this out, but if you get a chance to verify locally that'd be great
