### ISSUE TITLE
MA: people data shape is out of sync scraper

### ISSUE THREAD

**Issue by bhrutledge** [openstates/issues#207]
Related to https://github.com/openstates/people/pull/374, I've been working through the contributing instructions for [scrapers](https://docs.openstates.org/en/latest/contributing/scrapers.html) and [people](https://docs.openstates.org/en/latest/contributing/people.html). When I get to `merge.py`, all of the files are modified, because it looks like the `people` scraper was modified in 2017 ([diff](https://github.com/openstates/openstates-scrapers/pull/1750/files#diff-3f2b7fa6a66cdf73aae2d442eea012f2d571dedd7344fc44f114ab707a75645c)), but the YAML files don't reflect that.

Take, for example, [Denise Provost](https://github.com/openstates/people/blob/main/data/ma/legislature/Denise-Provost-d887e897-63da-48da-b7cb-b5cc3a3a6e2a.yml). Using the [latest YAML from the scraper](https://gist.github.com/bhrutledge/2e7fbf03635d07b5532bdce8aec7294c), running `merge.py` results in:

```diff
@@ -6,12 +6,17 @@ roles:
 - district: 27th Middlesex
   jurisdiction: ocd-jurisdiction/country:us/state:ma/government
   type: lower
-  start_date: 2011-01-01
 contact_details:
 - note: Capitol Office
   address: 24 Beacon St.;Room 473B;Boston, MA, 02133
   fax: 617-626-0548
   voice: 617-722-2263
+- email: Denise.Provost@mahouse.gov
+  note: District Office
+- address: 24 Beacon St.;Room 473B;Boston, MA, 02133
+  fax: 617-626-0548
+  note: Capitol office
+  voice: 617-722-2263
 links:
 - url: https://malegislature.gov/Legislators/Profile/D_P1
 sources:
```

Beyond the differences above, the new data is missing the top-level `email` attribute. It looks like a lot of this was done in <https://github.com/openstates/people/commit/c80f69d0edd41b2e7a2707edce416856e7101ac2>.

Also, a number of YAML filenames don't match the `name` attribute, which results in new YAML files being created. For example, [Adrian C. Madaro](https://github.com/openstates/people/blob/main/data/ma/legislature/Adrian-Madaro-f8772f1e-29f7-42e2-8a8c-ab4005153b05.yml) has a filename of `Adrian-Madaro-...`, but `merge.py` generates `Adrian-C-Madaro-...`.

Here are the commands I've run so far:

```bash
# in openstates-scrapers
docker-compose run --rm scrape ma people --fastmode --scrape

# in people
docker-compose run --rm -v `realpath ../openstates-scrapers/_data`:/data people scripts/to_yaml.py /data/ma

docker-compose run --rm people scripts/merge.py --incoming ma
```

**Comment by jamesturk** [comment]
The YAML is expected to diverge from the actual output, the task to update the people is reflected in #160.  If you have the resources it'd be great to get MA people merged with any new data, scraper updates are typically required as you've noticed here.

**Comment by bhrutledge** [comment]
Thanks, @jamesturk. I'm feeling motivated to tackle this. If I understand correctly, the process would be something like:

- Update MA `people` scraper output to match current shape of `people` data
- Run MA `people` scraper
- Change filenames of existing `people` data to match `name` attribute
- Run `to_yaml.py`
- Run `merge.py --incoming`

Does that look right? Do any of those items warrant dedicated issues?

Also, given the diff in the description, any tips on how to update the scraper to minimize merge issues? For example, I note that `start_date` is removed by `merge.py`. Also, it looks like `email` should be a top-level attribute, instead of in `contact_details`.

**Comment by jamesturk** [comment]
The merge script tries to detect name changes and offers to merge them anyway, so the only step that shouldn’t be needed generally is the change filenames step unless I’m misunderstanding something.

It’s a bit annoying as you’ve noted, and improvements to the merge script would be welcome if they are general purpose and made things merge cleaner.

The only main schema change would be the email one, if start dates are getting dropped that does sound like a bug in merge possibly.

**Comment by bhrutledge** [comment]
Thanks @jamesturk. Before getting started on this, I'm inclined to finish the work of updating district names, which I think is currently blocked waiting for feedback re: updates in openstates-core: https://github.com/openstates/people/pull/374#issuecomment-751479771.

**Comment by bhrutledge** [comment]
I don't know how to proceed re: the `email` schema change, which seems to be encompassed by work for https://github.com/openstates/issues/issues/151 and https://github.com/openstates/people/pull/336. However, I don't see it reflected in [schemas/person.py](https://github.com/openstates/openstates-core/blob/main/openstates/scrape/schemas/person.py), or in the [`Person` class](https://github.com/openstates/openstates-core/blob/c5e33f2e9d5e06c8ddf94bd51fdea98bb85d4548/openstates/scrape/popolo.py#L96-L107), which seems to be used in [scrapers/ma/people.py](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/ma/people.py). In other words, it seems like the call to [`Person.add_contact_detail(type="email")`](https://github.com/openstates/openstates-scrapers/blob/176063ad08b56716514719ff5e6f4125486d1884/scrapers/ma/people.py#L74-L75) needs to change, but that seems to require more core changes.

I note that there have been additions and updates to `openstates/people/data` since the `email` schema change, which reflect the new schema:

- [IN: Update legislators by csnardi · Pull Request #342](https://github.com/openstates/people/pull/342)
- [ME: Update legislators after 2020 election by csnardi · Pull Request #356](https://github.com/openstates/people/pull/356)
- [Al 2021 by jamesturk · Pull Request #363](https://github.com/openstates/people/pull/363)
- [Ms 2021 by jamesturk · Pull Request #366](https://github.com/openstates/people/pull/366)

However, it doesn't look like the associated scrapers have been updated. So, I feel like I'm missing something re: how to properly update `people`.

P.S. If there's a more appropriate place for this discussion, I'm happy to move there.

**Comment by jamesturk** [comment]
the scrapers here are not in the same shape generally as the people ones, but to_yaml can transform them, including the email field (it was recently updated for this)

almost missed this since it was on a closed issue, if you decide to claim MA & have general questions/etc. feel free to open an issue and we can work to get it working
