### ISSUE TITLE
addresses marked wrong location

### ISSUE THREAD

**Issue by juliesutton** [openstates/issues#209]
I wondered what to do when we find an address that is marked a wrong location?  for example 400 Buford Highway, Suwanee, GA 30024

**Comment by jamesturk** [comment]
If you can give more details (the expected results, what you got, etc.) we can look into it.  If you don’t want to share publicly, you can also email contact@openstates.org

**Comment by juliesutton** [comment]
Thank you.  The pin point on your map is in the wrong location of the address… if you look at the pic below the pinpoint should be above the word “Suwanee”

I will email contact@.

[cid:image001.png@01D6DDFA.A1A81CC0]

**Comment by jamesturk** [comment]
Gotcha, this is actually an issue with the geocoded address, which our map provider can’t identify.  https://apps.mapbox.com/feedback/ is the place to report the specific issue with your address.

**Comment by juliesutton** [comment]
Ok thanks.  I just reported it.  Hope I did it correctly…
