### ISSUE TITLE
RFC: Action Categorization Overhaul

### ISSUE THREAD

**Issue by jamesturk** [openstates/issues#21]
As part of the work we're doing we want to be able to improve action categorization, part of that will involve reworking how it works so that we can re-categorize actions without a new scrape (important for old sessions).  I'd also like to make it easier for people to submit simple fixes to the action categorizers without editing a bunch of code in the scraper itself.

With those goals in mind, here's my proposal:

- pupa gains a new command, essentially `pupa categorize-actions nc`
    - by default this will run on all actions and print a report of how it categorized actions with enough detail for debugging
- this command relies on writing some new action categorization code and making a few code changes in each state, it will look for two things (in this order)
    - [state].actions.categorize_actions - a function that takes action details (text, chamber, session?) and returns a list (can be empty) of categories
    - [state].actions.categorizers - a list of tuples mapping regex to actions, used if no function is defined (probably sufficient in 90% of cases)

other things that'll need to be done:
- existing action categorization needs to continue to work for backwards compatibility (at least for now)
- presumably the categorizer should be called after a scrape automatically (categorize-actions is mainly for adding categories to historical data)
- we'll need to special case action categories on import to not be overwritten so that update detection doesn't break

Open questions:
- will these two approaches be sufficient? / are any states a lot more complex to categorize?

**Comment by jamesturk** [comment]
Just noting the fact that entity recognition (e.g. 'ADDED H.SMITH AS SPONSOR') is currently part of the categorizers, and we'd want to revisit that too.

**Comment by showerst** [comment]
Yeah, one vote here for splitting that out into separate logic.

Spit-balling here, does it make sense to do a multi-pass approach:

1. classify action 
1. resolve people 
1. resolve entities (thinking principally of committees here)

Then we could re-use the people and entity resolution code elsewhere for looking up voters and sponsors.

I'm imagining some built-ins that's are easy to override on a per-jurisdiction level, maybe in the __init__.py or something.

**Comment by showerst** [comment]
Side note on my idea of the entity resolvers living in the scrapers, that might make running in scrape mode a real mess, so maybe that should be left in core where it lives now? 

It would be cool to make that easier to update though, so maybe there's another way.
