### ISSUE TITLE
MD 2021 prefiles missing bill sponsors

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#210]
**Issue Description:** MD bills in 2021 session are missing bill sponsors.

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/md/bills/2021/HB20/
https://openstates.org/md/bills/2021/HB34/
https://openstates.org/md/bills/2021/SB227/

**Source URL of correct data if applicable:**
http://mgaleg.maryland.gov/mgawebsite/Legislation/Details/hb0020?ys=2021RS
http://mgaleg.maryland.gov/mgawebsite/Legislation/Details/hb0034?ys=2021RS
http://mgaleg.maryland.gov/mgawebsite/Legislation/Details/sb0227?ys=2021RS

**Comment by jamesturk** [comment]
just pushed a fix, will run once docker image builds

**Comment by jessemortenson** [comment]
Thanks! Looks like at least one wrinkle still to iron out, found a couple bills that have sponsors like 

Chair 
Education 
Health
Environmental Affairs Committee (By Request - Departmental - Labor)

https://openstates.org/md/bills/2021/SB141/
https://openstates.org/md/bills/2021/SB125/
