### ISSUE TITLE
NH Bills are Missing Versions

### ISSUE THREAD

**Issue by alexobaseki** [openstates/issues#224]
**Issue Description**

There are few bills on NH that are missing versions. This is affecting a set of the first House and Senate Resolutions. Further investigation into this, observed that these same bills does not appear in the [LsrsOnly.txt Document in source](http://gencourt.state.nh.us/dynamicdatafiles/LsrsOnly.txt), thus [scrape_version_ids() fails to capture these missing versions](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/nh/bills.py#L285)

**URLs Where Issue Can Be Seen**

https://openstates.org/nh/bills/2021/HR1/

https://openstates.org/nh/bills/2021/SR1/

**Source URLs for Correct Data (if available)**

http://www.gencourt.state.nh.us/bill_Status/bill_status.aspx?lsr=0847&sy=2021&sortoption=&txtsessionyear=2021

http://www.gencourt.state.nh.us/bill_Status/bill_status.aspx?lsr=0573&sy=2021&sortoption=&txtsessionyear=2021

**Comment by showerst** [comment]
I'll take a look at this tomorrow, can confirm I see the same thing you do.

Note: these bills do show up on http://gencourt.state.nh.us/dynamicdatafiles/LSRs.txt?x=20210107085037 , but they're not in LsrsOnly.txt

**Comment by jamesturk** [comment]
> Philip Tsien commented in Jira:

HiRylie Johnson! Do you have an estimate for this ticket that we could add? Or is it the kind of ticket that will require a bit of investigation/start on before we can understand that? Thank you!🙂
