### ISSUE TITLE
IN joint and concurrent resolutions bill number discrepancy

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#227]
**Issue Description:** IN has a set of concurrent and joint resolutions filed in each chamber. In Open States, the identifier / bill number uses a prefix in the form SJ/SC/HJ/HC. However, on the IN website the identifier is prefixed with SJR/SCR/HJR/HCR.

I don't have an IN API key so can't immediately check to see if the API data shows this discrepancy or not. Looking at the [IN website](http://iga.in.gov/legislative/2021/resolutions/) I'm guessing an end user would expect to see the three-alpha prefixes.

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/in/bills/2021/SJ7/
https://openstates.org/in/bills/2021/HC2/

**Source URL of correct data if applicable:**
http://iga.in.gov/legislative/2021/resolutions/senate/joint/7
http://iga.in.gov/legislative/2021/resolutions/house/concurrent/2

**Comment by jamesturk** [comment]
taking a look at this one

**Comment by jamesturk** [comment]
it does seem like the API is returning the 2 letter version. IN is unfortunately already quite slow to run but I'll work on testing a fix to make the names match the site as I do think that is probably the intent

**Comment by jamesturk** [comment]
after digging through the API, there was a displayName property all along, will give this a run and clean up the other bills

**Comment by jamesturk** [comment]
IN is being incredibly slow again.. timed out again a few minutes ago.

**Comment by jamesturk** [comment]
fixed & removed improperly named bills for this session
