### ISSUE TITLE
InconsistentMigrationHistory when trying to restore the 2020 dump

### ISSUE THREAD

**Issue by jdubansky** [openstates/issues#234]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Hello, when I try to restore the database to a remote server using the scheme and dump I get an error saying "column opencivicdata_person.email does not exist" So I figured there is some migration that is out of sync and try to run migrate I get this error 
`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration profiles.0001_initial is applied before its dependency data.0001_initial on database 'default'.`

Not sure if it is possible to use a remote database but I would like to.

**Comment by jdubansky** [comment]
I was able to get one step closer with doing `migrate data --fake-initial` but now running into an issue `no such organization ocd-jurisdiction/country:us/state:ak/government executive` when trying to import people.

**Comment by jamesturk** [comment]
Have you tried with a more current dump, the jan 2021 dump should have the migrations you need.

**Comment by jdubansky** [comment]
I didnt realize those were available! downloading right now! Thanks for the heads up!

**Comment by jdubansky** [comment]
That worked! Thank you!
