### ISSUE TITLE
TX: duplicate actions for at least 1 bill

### ISSUE THREAD

**Issue by azban** [openstates/issues#236]
**Issue Description:**
I found one bill with a very large number (656) of actions in Texas. This looked high, so I checked to see if some of them were similar/dupes, and it looks like there's only 95 unique actions returned.

```python
>>> len(bill["actions"])
656
>>> [action.pop("order") for action in actions]
...
>>> len(set([json.dumps(action) for action in bill["actions"]]))
95
```

**URL where this issue may be seen (API or OpenStates.org):**
https://v3.openstates.org/bills/ocd-bill/bedac43f-39a9-4958-8668-e32fb9f6be52?&include=actions

**Source URL of correct data if applicable:**
Texas FTP

**Comment by showerst** [comment]
Extra data, this is from last session, (86) HB1

https://openstates.org/tx/bills/86/HB1/

https://capitol.texas.gov/BillLookup/History.aspx?LegSess=86R&Bill=HB1

@azban -- I don't think this is a bug. It looks like many of these are "amended" which can happen multiple times, in fact happens hundreds of separate times on this bill, many of them on the same day. That's not a bug, actions don't have to to be unique if the state doesn't give us granular enough time data to tell them apart.

**Comment by jamesturk** [comment]
yeah @Azban my mistake for not checking the source before saying this looked like a bug.  this looks legitimate after all
