### ISSUE TITLE
South Dakota information is not being populated into OpenStates - example:   "id": "ocd-bill/4c2ea03f-82f1-4188-94be-e5dddc59d60c"

### ISSUE THREAD

**Issue by LauraBula** [openstates/issues#238]
We are tracking several South Dakota Bills, but the info in OpenStates is not updated with the state's information.  Is there a problem with the South Dakota feed? 

Here is an example:
South Dakota SB 19 (https://sdlegislature.gov/Session/Bill/21899) lists 4 events: 

     > 01/12/2021 | First read in Senate and referred to Senate Health and Human Services S.J.1 | N/A |  
     > 01/20/2021 | Scheduled for hearing |   | 1:19:33
     > 01/20/2021 | Health and Human Services Do Pass, Passed, YEAS 7, NAYS 0. S.J. 2 |   | 1:19:33
     > 01/20/2021 | Certified uncontested, placed on consent, S.J. 2 |   | 1:19:33

HOwever, the OpenStates data has "null" for all fields: 

{
  "**id": "ocd-bill/4c2ea03f-82f1-4188-94be-e5dddc59d60c**",
  "session": "2021",
  "jurisdiction": {
    "id": "ocd-jurisdiction/country:us/state:sd/government",
    "name": "South Dakota",
    "classification": "state"
  },
  "from_organization": {
    "id": "ocd-organization/5a7260e0-bd1e-4f37-949f-ebb386e8bacc",
    "name": "Senate",
    "classification": "upper"
  },
  "identifier": "SB 19",
  "title": "correct errors in statutory cross-references in certain provisions regarding health care.",
  "classification": [
    "bill"
  ],
  "subject": [
    "Executive/Judiciary Request",
    "Health Care",
    "Technical Corrections"
  ],
  "extras": {},
  "created_at": "2021-01-12T19:03:47.348412Z",
  "updated_at": "2021-01-12T19:03:47.348434Z",
  "openstates_url": "https://openstates.org/sd/bills/2021/SB19/",
  "first_action_date": **null**,
  "latest_action_date": **null**,
  "latest_action_description": **""**,
  "latest_passage_date": **null**,
  "abstracts": **null**,
  "other_titles": **null**,
  "other_identifiers": **null**,
  "sponsorships": **null**,
  "actions": [],
  "sources": [
    {
      "url": "https://sdlegislature.gov/api/Bills/21899",
      "note": ""
    }
  ],
  "versions": null,
  "documents": null,
  "votes": null
}

**URL where this issue may be seen (API or OpenStates.org):**

**Source URL of correct data if applicable:**

**Comment by showerst** [comment]
Confirmed the SD scraper isn't capturing actions correctly. @LauraBula this is a new website and I believe we were waiting for some actions to post to figure out how to scrape them. I'll take a look at this shortly.

**Comment by LauraBula** [comment]
Thank you!

   Laura Carpenter, CEO

[cid:image005.png@01D6EFDF.056D4140]

Office: 480.339.8383   Cell: 602.740.4058
2150 E Highland Ave., Suite 105, Phoenix, Arizona 85016​
www.bulalaw.com<http://www.bulalaw.com/>
[cid:image006.jpg@01D6EFDF.056D4140]
This electronic mail transmission and any attachments are confidential. They should be read or retained only by the intended recipient. If you have received this transmission in error, please notify the sender immediately and delete the transmission from your system.
BulaLaw provides general information about statutes and regulations. It does not provide legal advice.

**Comment by showerst** [comment]
I pushed a patch for this, the data should become accurate after the next scrape.

**Comment by LauraBula** [comment]
Thank you!!!!

   Laura Carpenter, CEO

[cid:image005.png@01D6EFE7.E66C7640]

Office: 480.339.8383   Cell: 602.740.4058
2150 E Highland Ave., Suite 105, Phoenix, Arizona 85016​
www.bulalaw.com<http://www.bulalaw.com/>
[cid:image006.jpg@01D6EFE7.E66C7640]
This electronic mail transmission and any attachments are confidential. They should be read or retained only by the intended recipient. If you have received this transmission in error, please notify the sender immediately and delete the transmission from your system.
BulaLaw provides general information about statutes and regulations. It does not provide legal advice.

**Comment by jamesturk** [comment]
actions are up!
