### ISSUE TITLE
MD SB 169 (Session = 2021) has the data from 2016, 2017, 2019, 2018, 2019 and 2020 Bills with same number

### ISSUE THREAD

**Issue by LauraBula** [openstates/issues#249]
"results": [
    {
      "id": "**ocd-bill/c7f91821-135d-48c5-b15b-7f665c1f8918**",
      **"session": "2021",**
      "jurisdiction": {
        "id": "ocd-jurisdiction/country:us/**state:md**/government",
        "name": "**Maryland**",
        "classification": "state"
      },
      "from_organization": {
        "id": "ocd-organization/6328292e-c35e-4187-903c-75829a17d5d8",
        "name": "Senate",
        "classification": "upper"
      },
      "identifier": "**SB 169"**,
      "title": "Health Occupations - Podiatric Physicians",
      "classification": [
        "bill"
      ],
      "subject": [
        "A"
      ],
      "extras": {
        "date_effective": "October 1, 2021"
      },
      "created_at": "2020-12-29T16:42:26.750212+00:00",
      "updated_at": "2021-01-15T18:17:46.468716+00:00",
      "openstates_url": "https://openstates.org/md/bills/2021/SB169/",
      "first_action_date": "2020-10-30",
      "latest_action_date": "2021-01-13",
      "latest_action_description": "First Reading Education, Health, and Environmental Affairs",
      "latest_passage_date": ""
    },
    {
      "id": "ocd-bill/ffd5dc4e-d59e-4c99-95fc-3e3fa70129b1",
      "session": "2020",
      "jurisdiction": {
        "id": "ocd-jurisdiction/country:us/state:md/government",
        "name": "Maryland",
        "classification": "state"
      },
      "from_organization": {
        "id": "ocd-organization/6328292e-c35e-4187-903c-75829a17d5d8",
        "name": "Senate",
        "classification": "upper"
      },
      _"identifier": "SB 169",
      "title": "Health Occupations - Violations of the Maryland Dentistry Act - Penalties and Cease and Desist Orders",
      "classification": [
        "bill"
      ],
      "subject": [],
      "extras": {
        "date_effective": "October 1, 2020"
      },
      "created_at": "2020-02-04T04:30:08.164601+00:00",
      "updated_at": "2020-07-09T11:31:13.662966+00:00",
      "openstates_url": "https://openstates.org/md/bills/2020/SB169/",
      "first_action_date": "2020-01-13",
      "latest_action_date": "2020-05-08",
      "latest_action_description": "Enacted under Article II, Section 17(c) of the Maryland Constitution - Chapter 386",
      "latest_passage_date": "2020-03-16"
    },
    {_
      _"id": "ocd-bill/c30daa6f-5ca6-412d-bea8-b5f3757c0ef7",
      "session": "2019",
      "jurisdiction": {
        "id": "ocd-jurisdiction/country:us/state:md/government",
        "name": "Maryland",
        "classification": "state"
      },
      "from_organization": {
        "id": "ocd-organization/6328292e-c35e-4187-903c-75829a17d5d8",
        "name": "Senate",
        "classification": "upper"
      },
      "identifier": "SB 169",
      "title": "State Personnel Recruitment Modernization Act of 2019",
      "classification": [
        "bill"
      ],
      "subject": [
        "State Government - Personnel",
        "Advertising",
        "Budget and Management, Department of",
        "Examinations",
        "Notices",
        "State Employees",
        "Time",
        "Work, Labor and Employment"
      ],
      "extras": {},
      "created_at": "2019-01-23T10:18:05.912351+00:00",
      "updated_at": "2020-04-28T23:56:45.232101+00:00",
      "openstates_url": "https://openstates.org/md/bills/2019/SB169/",
      "first_action_date": "2019-01-21",
      "latest_action_date": "2019-03-15",
      "latest_action_description": "Unfavorable Report by Finance; Withdrawn",
      "latest_passage_date": ""
    },
    {
      "id": "ocd-bill/78dc9cad-e3d4-472d-b8ed-d062b8c63f49",
      "session": "2018",
      "jurisdiction": {
        "id": "ocd-jurisdiction/country:us/state:md/government",
        "name": "Maryland",
        "classification": "state"
      },
      "from_organization": {
        "id": "ocd-organization/6328292e-c35e-4187-903c-75829a17d5d8",
        "name": "Senate",
        "classification": "upper"
      },
      "identifier": "SB 169",
      "title": "Public Health - Prescription Drug and Medical Supply Access and Affordability Workgroup",
      "classification": [
        "bill"
      ],
      "subject": [
        "Public Health",
        "Insurance - Health",
        "Committees and Commissions",
        "Drugs",
        "Equipment",
        "Health Care Facilities",
        "Health, Department of",
        "Health Insurance",
        "Health Maintenance Organizations",
        "Hospitals",
        "Pharmacists and Pharmacies",
        "Reports",
        "Sunset"
      ],
      "extras": {},
      "created_at": "2018-01-17T04:26:40.722182+00:00",
      "updated_at": "2020-04-28T23:56:26.249222+00:00",
      "openstates_url": "https://openstates.org/md/bills/2018/SB169/",
      "first_action_date": "2018-01-15",
      "latest_action_date": "2018-01-24",
      "latest_action_description": "Hearing 2/07 at 1:00 p.m.",
      "latest_passage_date": ""
    },
    {
      "id": "ocd-bill/ec06aa6b-f667-461b-9e86-5a2a88a75950",
      "session": "2017",
      "jurisdiction": {
        "id": "ocd-jurisdiction/country:us/state:md/government",
        "name": "Maryland",
        "classification": "state"
      },
      "from_organization": {
        "id": "ocd-organization/6328292e-c35e-4187-903c-75829a17d5d8",
        "name": "Senate",
        "classification": "upper"
      },
      "identifier": "SB 169",
      "title": "Health - Cost of Emergency Room Visits to Treat Dental Conditions and Coverage of Dental Services Under Medicaid - Study",
      "classification": [
        "bill"
      ],
      "subject": [
        "Public Health",
        "Committees and Commissions",
        "Dentists",
        "Emergency Medical Services",
        "Emergencies",
        "General Assembly",
        "Health and Mental Hygiene, Department of",
        "Medical Assistance",
        "Patients",
        "Prices",
        "Reports"
      ],_
      "_extras": {},
      "created_at": "2017-07-15T07:13:58.007621+00:00",
      "updated_at": "2020-04-28T23:55:25.902814+00:00",
      "openstates_url": "https://openstates.org/md/bills/2017/SB169/",
      "first_action_date": "2017-01-18",
      "latest_action_date": "2017-05-25",
      "latest_action_description": "Approved by the Governor - Chapter 721",
      "latest_passage_date": "2017-04-10"
    }_
  ],
  "pagination": {
    "per_page": 10,
    "page": 1,
    "max_page": 1,
    "total_items": 5
  }

**Comment by jamesturk** [comment]
Can you specify what query you're making to get this bill?  I'd think this is an issue w/ the query itself

**Comment by LauraBula** [comment]
Now i can;t replicate.  Can we close this out?
