### ISSUE TITLE
PR missing > 120 bills

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#251]
This may be a continuation of #121 which was perhaps not fixed for the last session.

**Issue Description:** Despite scraper having just run, OS data appears to be missing over a hundred bills from PR in the current session, including:

RCC 1 - RCC 34
RC 137 - RC 202
RKC 1 - RKC 19
RS 57 - RS 58

Again not seeing a super clear pattern, and haven't had a chance to look at the scraper code yet. Weird that RC and RS bills are getting picked up to a certain point in scraper output, then it just stops (despite those stopping points appearing to be in the middle of result pages when looking at the PR website)

**Source URL of correct data if applicable:**

https://sutra.oslpr.org/osl/esutra/MedidaBus.aspx?rid=127866

**Comment by jamesturk** [comment]
PR's pagination leaves much to be desired, but it looks like there's a way to bypass it now.  Working on a fix for this and #121

**Comment by jamesturk** [comment]
latest scrape restores 220 missing bills, those mentioned above seem to be there, and the total number now matches PR's site
