### ISSUE TITLE
AR: Legislature names not "linked" to ID

### ISSUE THREAD

**Issue by ColbyReed** [openstates/issues#254]
**Issue Description:**
Wasn't really sure how to title this. But it seems the names being scraped for legislatures are not being "linked" to that persons ID. On vote counts or sponsorships, it will simply show the abbreviated scraped name of some legislatures while showing the full name and details of others. 

**URL where this issue may be seen (API or OpenStates.org):**
Examples:
HB 1001 votes
https://openstates.org/vote/16e7036a-2d29-4193-a9b9-8d4804d6918c/
https://openstates.org/vote/1811ed80-d823-4982-b543-1f867384b0ac/

GraphQl request:
{
  bill(jurisdiction: "Arkansas", session: "2021", identifier: "HB 1001") {
    title
    votes {
      edges {
        node {
          votes {
            voter {
              id
            }
            voterName
          }
        }
      }
    }
  }
}

**Source URL of correct data if applicable:**
Arkansas website vote links:
https://www.arkleg.state.ar.us/Bills/Votes?id=HB1001&rcs=1740&chamber=Senate&ddBienniumSession=2021%2F2021R
https://www.arkleg.state.ar.us/Bills/Votes?id=HB1001&rcs=1759&chamber=House&ddBienniumSession=2021%2F2021R

**Comment by jamesturk** [comment]
Hi Colby, 

#22 covers this nationally, it is an ongoing effort

if you'd like to help get AR fixed up, really what is needed is to add the aliases that they use for voting/etc. (G. Leding) to their people files in openstates/people

We're planning on building tooling for this in coming months, but if it is a priority for you should be possible to do without that.

**Comment by jamesturk** [comment]
& going to close this one out since we're tracking the issue nationally already
