### ISSUE TITLE
Filter bills by actions

### ISSUE THREAD

**Issue by dannyfritz** [openstates/issues#26]
**Is your feature request related to a problem? Please describe.**
I want to make a website that displays all bills in Colorado that have passed both the senate and house, but haven't been signed by the governor yet.

**Describe the solution you'd like**
I'd like to be able to filter bills by which actions it has passed/failed.
* Filter by "passed senate committee"
* Filter by "passed house committee and passed senate committee"
* Filter by "failed house committee"
* etc.

**Describe alternatives you've considered**
Fetch all bill data, page it all, and filter it on the consumer side.
Download the bulk data and filter it on the consumer side.

**Additional context**
https://discourse.openstates.org/t/api-v2-filter-by-status/490

**Comment by jamesturk** [comment]
This is possible now based on action categorization, but the completeness of action categorization varies a lot per state.

**Comment by jamesturk** [comment]
I'm curious if any of those interested in this ticket have opinions on the tradeoff vs. a generic way to query actions vs. some specific subset.  I'd also be more than glad to guide someone through working on this feature if there's interest.
