### ISSUE TITLE
NY Bill from 2019-2020 Session was not updated with 1/30/2021 info (ocd-bill/589014d7-6657-4b1d-9271-e9f1e6ed54d4)

### ISSUE THREAD

**Issue by LauraBula** [openstates/issues#263]
Hello!  We are looking at 2019-2020 New York S 6492 (ocd-bill/589014d7-6657-4b1d-9271-e9f1e6ed54d4) and noted that the last action date in OpenStates is 12/30/2020.  However when we go to the state website, there are 2 events from 1/30/2021. 

OpenStates:  
  "latest_action_date": "2020-12-30T00:00:00Z",
  "latest_action_description": "DELIVERED TO GOVERNOR",

[New York Legislature webite](https://www.nyassembly.gov/leg/?default_fld=&leg_video=&bn=S06492&term=2019&Actions=Y): 
01/30/2021 | SIGNED CHAP.388 
01/30/2021 | APPROVAL MEMO.77

is this a function of how the scrapes occur?  In other words, do we need to manually check Bills that are passed by both chambers at the end of a Session year, but are not signed by the governor until the next year? 

Thanks!
Laura

**Comment by jamesturk** [comment]
Generally we do stop scraping the old session after a new one is up, as most states don't update past that point.

In this case, it sounds like NY might benefit from a one-off, so I'll kick that off this afternoon.

**Comment by LauraBula** [comment]
Thanks, James!  In the future, we will just manually check bills that are still pending after the session has closed.
