### ISSUE TITLE
RI: Representative Blake Filippi is listed as wrong party

### ISSUE THREAD

**Issue by landshark22** [openstates/issues#265]
Blake Filippi is being shown as an Independent, he is now a Republican in fact he is the minority leader. 

He was originally elected as an Independent but changed to Republican in 2016

This is the page on OpenStates where he is listed as an independent https://openstates.org/person/blake-a-filippi-5xYUmjYEpfu4rbhBjpzFWa/

Here is the link to his official page where it shows "R" for district 36 http://www.rilin.state.ri.us/representatives/filippi/default.aspx

**Comment by jamesturk** [comment]
thanks for catching this, if you're curious/interested in contributing a fix the people data lives here: https://github.com/openstates/people/

a fix to his file (in data/ri/legislature) would fix this, someone can get to it very soon I'm sure but if you are able to that'd be great!
