### ISSUE TITLE
General Question about the task-definitions repo

### ISSUE THREAD

**Issue by jdubansky** [openstates/issues#268]
Hello,

I was able to get the latest dumps imported into my database but I would like to keep it as updated as possible. I noticed the https://github.com/openstates/task-definitions has tasks to run the scrapers but I am a bit lost on how to run these. Can it be done in AWS? 

Thanks,

**Comment by jamesturk** [comment]
**Please do not run the scrapers yourself.**

If you want the latest data, we have an API that is available to help with that- we cannot support individuals running the scrapers regularly and it can cause problems for everyone (having the scrapers blocked/APIs down/etc.) when done incorrectly.
