### ISSUE TITLE
Arizona Legislator Check Issues

### ISSUE THREAD

**Issue by JhaelleP** [openstates/issues#279]
State: AZ

Short Description: When checking Arizona’s legislators, I only found one legislator that did not have their email recorded. 

Missing or Incorrect legislators:
N/A

Data Issues:
- Judy M. Burges’ contact information is not recorded on OpenStates and the link on her OpenStates page is not updated.

Additional Data:
N/A

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/judy-burges-6wzKXK1YSW4xe7uHCZYxko/

**Source URL of correct data if applicable:**
https://www.azleg.gov/house-member/?legislature=55&legislator=2060

**Comment by mpedrego** [comment]
Hello guys, Judy's email is jburges@azleg.gov

**Comment by mpedrego** [comment]
I have a document that says the email of the politicians email = First Initial + Last Name + @azleg.gov. For future reference. =) thank you
