### ISSUE TITLE
South Carolina Legislator Spot Check Issues

### ISSUE THREAD

**Issue by JhaelleP** [openstates/issues#280]
State: SC

Short Description: When checking South Carolina’s legislators, one legislator's number was incorrect. However, I could not find a pattern.

Missing or Incorrect legislators:
N/A

Data Issues:
- Thomas D. "Tom" Corbin's number is incorrect on his contact information

Additional Data:
N/A

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/thomas-d-tom-corbin-18KGLeYh8LQCToLVfYoMyp/

**Source URL of correct data if applicable:**
https://www.scstatehouse.gov/member.php?code=0402272679

**Comment by jamesturk** [comment]
this legislator's information appears correct

**Comment by yi-yang-github** [comment]
Not sure if we can reopen this? I believe it's a wide spread issue with at least all state leg senators
E.g.
Senator George E. "Chip" Campsen, III
https://www.scstatehouse.gov/member.php?code=0302272691
has 
```
Home Address
360 Concord St.
Suite 201, Charleston 29401

Home Phone (843) 886-8454

Business Phone (843) 722-0123
```
and OpenStates data scraped the "Home Phone", when we call that phone number we got connected with his wife.

The scraper needs to be fixed to skip home phone numbers.

**Comment by jamesturk** [comment]
Hmm, I'm not sure this is an issue per se.  

If SC is listing incorrect numbers that folks do not want to be called, I'd get in touch with the legislator themselves so they can work to get it corrected upstream.

**Comment by yi-yang-github** [comment]
I have no idea why they post their "Home Phone" number there, it's probably a bit unique to their website. 
As a general rule I think people using OpenStates or similar database would be trying to contact the rep's office though, not their home phone, so maybe scraper can choose to use the "Business Phone" instead of the "Home phone" here?

**Comment by jamesturk** [comment]
Business office typically isn’t better, it is often a law firm or similar.. have you called the business offices in this case to verify that they are the right place to be calling?

James

**Comment by yi-yang-github** [comment]
ok you are right it's a law firm. 
I guess the scraper can be kept as is then. I'll have to manually override these individual cases in our systems.

**Comment by jamesturk** [comment]
Yeah, the situation with home office numbers isn’t ideal.  If any of them ever give you better numbers let me know and we can figure out how to incorporate them.

James
