### ISSUE TITLE
Alaska Legislator Spot Check Issues

### ISSUE THREAD

**Issue by JhaelleP** [openstates/issues#283]
State: AK

Short Description: When checking Alaska’s legislators, I found information missing for legislators and noticed legislators missing. 

Missing or Incorrect legislators:
There were not any vacant seats, but Chuck Kopp, Colleen Sullivan-Leonard, David Talerico,   Donald Olson, Gabrielle LeDoux, Gary Knopp, Jennifer Johnston, John Lincoln, Joshua Revak, Lance Pruitt, Mark Neuman, and Sharon Jackson are not on OpenStates even though they are on the legislative site. 
While, Mike Cronk, Ronald Gillham, James Kaufman, Christopher Kurka, Kevin McCabe, Ken McCarty, Tom McKay, David Nelson, Josiah Patkotak, Calvin Schrage, Liz Snyder, and Donny Olson are not on the legislative site, but they are listed on OpenStates.

Data Issues:
-David Wilson's address on OpenStates is incorrect
-There is no mention of any legislators interim contact information or their Toll-Free phone number on OpenStates

Additional Data:
N/A

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/david-wilson-6NYIVIH3fr3ev8qJsgjJUU/

**Source URL of correct data if applicable:**
http://www.akleg.gov/basis/Member/Detail/32?code=wln

**Comment by jamesturk** [comment]
@JhaelleP can you look at this again?  The members you listed seem to have all lost elections/retired.
