### ISSUE TITLE
VA: Check scraper after special ends

### ISSUE THREAD

**Issue by showerst** [openstates/issues#289]
VA created a special in 2021 that carried over every regular session bill. It's possible they revert back to the regular afterwards, with or without including special session actions back in the regular bills.

Check on this again in the future and see what the deal is, hopefully https://github.com/openstates/openstates-scrapers/commit/a529a4536e24c57223de011a8ce200659e3d4ffc can be reverted.

**Comment by jamesturk** [comment]
old FTP is gone, so this is "resolved" for now :)
