### ISSUE TITLE
TX Legislator Spot Check Issues]

### ISSUE THREAD

**Issue by emilybenson1111** [openstates/issues#292]
State: Texas

Short Description:
One senator missing on Open States, other senators either missing district office addresses/phone numbers on Open States or the district office address and phone number is incorrectly stated. 

Missing or Incorrect legislators:
Senator listed on TX general assembly is not listed on OpenStates
-Patrick: https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=87&Chamber=S&Code=A1430

Data Issues:
Legislators missing District Office address and phone numbers 
-Alvarado: https://openstates.org/person/carol-alvarado-72rIh8ohHkvXPl5uDqMGU8/
-Johnson: https://openstates.org/person/nathan-johnson-6madvoe1F2w6yhp3otuEsZ/
-West: https://openstates.org/person/royce-west-6XbsQfyfEjn6cM4xIcmPNY/

Discrepancy in District Office address listed in TX general assembly and OpenStates
-Kolkhorst: https://openstates.org/person/lois-kolkhorst-1FDI4GckgqoM1OPl7SQ6ii/
-Perry (district office phone # is also incorrect): https://openstates.org/person/charles-perry-34q5upVwumIoO9Fsq4iQd1/
-Hall: https://openstates.org/person/bob-hall-2L3bRQIJsEbDjJR4WlyFk/
-Hefner: https://openstates.org/person/cole-hefner-23oNWdxwJrmSNzkK50DVo5/
-Morales: https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=87&Chamber=H&Code=A3910

Additional Data:
n/a

**Comment by jamesturk** [comment]
going through missing legislators first, confirmed no issue here.  Dan Patrick is not a legislator, he is Lt. Gov
