### ISSUE TITLE
AL Legislators need office updates

### ISSUE THREAD

**Issue by emilybenson1111** [openstates/issues#293]
State: AL

Short Description: Legislator's office listings are incorrect and the senate has 2 vacancies unlisted on open states. Consistent problems with emails that might be a software coding/pulling problem (reference both data issues and additional data sections). 

**Missing or Incorrect legislators:**
n/a

**Data Issues:**
(checked approximately 40 legislators) 

Some legislators have the wrong office # listed on Open States (happens fairly frequently):
-Jack W. Williams: https://openstates.org/person/jack-w-williams-56nY7PBQMyf5ZqjFNVT9na/
-Chris Elliott: https://openstates.org/person/chris-elliott-38svZyaLHy79JOMx4fruA6/
-Bobby D. Singleton: https://openstates.org/person/bobby-d-singleton-3MN8UmRm8fh486arTrCr0l/
-Louise Alexaner: https://openstates.org/person/louise-alexander-78Rpo4DSYtPZb4ICngAmm2/
-Ginny Shaver: https://openstates.org/person/ginny-shaver-GxVmWTXlVI85AY5csxah3/
-Gil Isbell: https://openstates.org/person/gil-isbell-1oj6JDA3agxq5m63uN0BME/
-Ed Oliver: https://openstates.org/person/ed-oliver-4pctEen4FVw9VEf2s0wYiT/

Some legislators don't have their emails listed on Open States:
-Priscilla Dunn: https://openstates.org/person/priscilla-dunn-6eIsgwj7TAr9S5z4Hktyko/
-Alan Baker: https://openstates.org/person/alan-baker-6BK8b9dJQAn8RJoZ5MPeqN/
-Andy Whitt: https://openstates.org/person/andy-whitt-5sUDmo104q0f1lKdVJ6gjI/

Different emails listed for a legislator on Open States and AL general assembly (doesn't appear systemic)
-Linda Coleman-Madison: https://openstates.org/person/linda-coleman-madison-4NgwFYWocMUSblfYAD1oy5/

Different phone numbers listed  for a legislator on Open States and AL general assembly (doesn't appear systemic)
-Del Marsh: https://openstates.org/person/del-marsh-PIrCujqLFn7IdmFj7C9R2/

**Additional Data:**

Capitalization of some legislators incorrect on OS (McMillan shown as Mcmillan, McCampbell shown as Mccampbell, etc.)

Open States doesn't note the counties of the legislator, just the district (AL general assembly site lists both) 

AL general assembly lists both a standard email (which can either be personal or professional ie. @alhouse.gov) and then another email address for the district email. Open States will only feature the first email, and if there is no email listed there but a district email is listed on the AL general assembly site, Open States won't feature any email. This issue has a lot of overlap with the "Some legislators don't have their emails listed on Open States" issue listed under Data Issues. EXAMPLE:
-Anthony Daniels: https://openstates.org/person/anthony-daniels-4YyswWygCvjxXIdZtx055k/
-Andy Whitt: https://openstates.org/person/andy-whitt-5sUDmo104q0f1lKdVJ6gjI/

**Comment by jamesturk** [comment]
vacancies are resolved
