### ISSUE TITLE
CT Legislators: addresses need to be updated

### ISSUE THREAD

**Issue by emilybenson1111** [openstates/issues#294]
State: CT
Short Description: One vacancy unlisted, issues with incorrect office numbers and phone numbers, however the big issue stems with the way that the CT general assembly site operates (Additional Data). Because the site itself doesn't have pages specifically for legislators and instead outsources to their personal sites or their pages on CT dems/reps sites, information acquisition is less uniform.

**Missing or Incorrect legislators:**

updated: fixed

**Data Issues:**

Many Legislators have the wrong office number/no office number listed in address. Occurs fairly commonly but here are a couple of examples: 
-Alex Kasser (wrong office number listed): https://openstates.org/person/alex-kasser-2LeifQ7tIcgP9cjALFHPV7/, http://www.senatedems.ct.gov/Kasser-contact
-Mae Flexer (wrong office number listed): https://openstates.org/person/mae-flexer-3dNpiKCcpGQA1Npd3eK4Hi/ , http://www.senatedems.ct.gov/Flexer-contact
-Rick Lopes (no office number listed): https://openstates.org/person/rick-lopes-5m615OSi3qJt5Tj5AeiaCh/ , http://www.senatedems.ct.gov/lopes-contact
-Norman Needleman (wrong office number listed): https://openstates.org/person/norman-needleman-VGrjGptCOu7fc4UDdIGAh/ , http://www.senatedems.ct.gov/needleman-contact 

Some legislators have the wrong phone number listed (doesn't appear to be systemic): 
-Catherine F. Abercrombie: https://openstates.org/person/catherine-f-abercrombie-44UMlw4hDG9STN1IPVOmce/ , http://www.housedems.ct.gov/Abercrombie

 Some legislators don't have a number listed at all (doesn't appear to be systemic): 
-Amy Morrin Bello: https://openstates.org/person/amy-morrin-bello-7lNycyX1nIFArL15X8KdSo/ , https://www.housedems.ct.gov/morrinbello

**Additional Data:**

CT general assembly lists info for legislative and press aides for Senators (open states doesn't). The phone number listed for most Senators is that of their aides (their numbers aren't listed on CT general assembly), however Open States doesn't specifically clarify this (ex. Alex Kasser: https://openstates.org/person/alex-kasser-2LeifQ7tIcgP9cjALFHPV7/)

IMPORTANT TO NOTE: It seems the CT general assembly site isn't perfectly functioning! Many of the district offices for legislators aren't listed on CT general assembly but are on Open states (ex. Derek Slap: https://openstates.org/person/derek-slap-4y0JUdYxvhVL5aMq6Y0hAE/ and Catherine A. Olsten: https://openstates.org/person/catherine-a-osten-5JlJpA7QTKRx0KSPnjOYO6/) and some senators don't even have pages that are linked to their name in the member list (ex. Kevin D. Witkos and Gary A. Winfield). Furthermore, CT general assembly doesn't have their own pages for legislators, rather links to their information on either CT senate dems/republicans.

**Comment by jamesturk** [comment]
Checked and do not see a vacancy, can you reconfirm?

**Comment by emilybenson1111** [comment]
Just checked, seems that CT general assembly has removed the vacancy since
when I did spot checks!
