### ISSUE TITLE
Maryland legislator issues

### ISSUE THREAD

**Issue by starcollector-ce** [openstates/issues#301]
**Short Description:** There were two legislators missing and a large address formatting error.

**Missing or Incorrect legislators:**
Reid J Novotny (House District 9A) is missing from OpenStates [https://msa.maryland.gov/msa/mdmanual/06hse/html/msa18290.html]

Michael A Jackson (Senate, District 27) missing from Openstates [https://msa.maryland.gov/msa/mdmanual/05sen/html/msa14132.html]

**Data Issues:**
Every legislator, there were addresses that were either incomplete or formatted incorrectly.
Examples:
Adrienne Jones 
Alonzo T Washington
Adelaide Eckardt
Arthur Ellis

**Comment by jamesturk** [comment]
closing as duplicate of #295 which has more details
