### ISSUE TITLE
Maine legislator phone numbers are missing

### ISSUE THREAD

**Issue by starcollector-ce** [openstates/issues#303]
Short Description: No other issues save for missing phone numbers for some House members.

**Missing or Incorrect legislators:**
Note

**Data Issues:**
Abigail Griffin, Barbara Cadone, Bruce. A White all don't have a phone number on their OpenStates page.
https://openstates.org/person/abigail-w-griffin-2TJ6gaQlcNGM72KRqkZeYU/
https://openstates.org/person/barbara-a-cardone-5FFcl9I010NxZPsoDCF1l6/
https://openstates.org/person/bruce-a-white-79GNSDtBqH0yHFv5fwS419/

**Additional Data:**
None

**Comment by jamesturk** [comment]
Thanks for this, going forward please try to name the issues with a title that will help us understand what it is.
