### ISSUE TITLE
Virginia State Spot Check Issues

### ISSUE THREAD

**Issue by JhaelleP** [openstates/issues#306]
State: VA
Short Description: When checking Virginia's bill data, there were issues with inaccurate actions

Include these 3 sections as appropriate (or note none)

Missing or Incorrect legislators:
N/A

Data Issues:
-In some cases, OpenStates does not have the first action reported by the legislative site. For example in bills SR103 and SR109
![Screen Shot 2021-02-19 at 1 47 12 PM](https://user-images.githubusercontent.com/62361110/108547890-131b3b00-72b9-11eb-907d-4054f32a8b1a.png)
![Screen Shot 2021-02-19 at 1 48 07 PM](https://user-images.githubusercontent.com/62361110/108547914-1d3d3980-72b9-11eb-9160-217513e51832.png)

Additional Data:
N/A

**Comment by jamesturk** [comment]
Thanks for this, when reporting bill issues can you provide links to 1-2 Open States bills with the issue in question?
