### ISSUE TITLE
Washington State Spot Check Issues

### ISSUE THREAD

**Issue by JhaelleP** [openstates/issues#307]
State: WA
Short Description: When checking Washington’s bill data, there were actions that were inaccurate.

Include these 3 sections as appropriate (or note none)

Missing or Incorrect legislators:
N/A

Data Issues:
-Some actions are repeated twice. For example, in bills SB 5203, SB 5287, and SB 5096

Example of bill SB 5287
![Screen Shot 2021-02-19 at 1 53 42 PM](https://user-images.githubusercontent.com/62361110/108548488-e3b8fe00-72b9-11eb-9bd3-5b6f338f0ad9.png)
![Screen Shot 2021-02-19 at 1 54 56 PM](https://user-images.githubusercontent.com/62361110/108548597-106d1580-72ba-11eb-9aa0-66c92fd99811.png)

Example of bill SB 5203
![Screen Shot 2021-02-19 at 1 59 38 PM](https://user-images.githubusercontent.com/62361110/108549102-b6b91b00-72ba-11eb-8fd7-465520d57de4.png)

Additional Data:
N/A

**Comment by showerst** [comment]
https://openstates.org/wa/bills/2021-2022/HB1220/

This appears to match the state site, which actions are wrong?

**Comment by JhaelleP** [comment]
I updated my comment and provided examples
