### ISSUE TITLE
Wyoming State Spot Check Issues

### ISSUE THREAD

**Issue by JhaelleP** [openstates/issues#308]
State: WY
Short Description: When checking Wyoming’s bill data, Enview listed a committee twice and the data on the legislative site is inaccurate, therefore it shows up inaccurately on Enview and OS.

Include these 3 sections as appropriate (or note none)

Missing or Incorrect legislators:
N/A

Data Issues:
Enview listed the committee twice for bill HB0009

Additional Data:
Enview and OS reported the right sponsor, but the legislator site has the committee listed in place of the sponsor. This was seen in most bills. For example, in bills SF0009, and SF0027

**Comment by showerst** [comment]
https://openstates.org/wy/bills/2021/SF9/

This looks correct.

@JhaelleP we appreciate the spot checking and we're happy to look into data issues, but this Openstates' bug tracker, not enviews. 

Please link to openstates pages (or api urls) and specific parts of the data that are bad, as we have no access to enview, or interest in tracking down bugs in third party consumer applications.
