### ISSUE TITLE
No good way to order votes chronologically; VoteNode.billAction, BillActionNode.vote is null

### ISSUE THREAD

**Issue by estaub** [openstates/issues#31]
[This Discourse post](https://discourse.openstates.org/t/database-query-for-final-passage-vote/454/3) by [dsal1951](https://discourse.openstates.org/u/dsal1951) reported difficulty in analyzing vote events for bills, in part because there are often several `passage` votes on a bill on one day, the exact time of each vote is often unavailable from the state, and there is no `order` field on `VoteNode` (unlike `BillActionNode`).  

The GraphQL schema claims cross-links of `VoteNode.billAction` and `BillActionNode.vote`, which would allow vote ordering by a client using `BillActionNode.order`, but these fields are usually null.  `VoteNode.billAction` is only populated in Montana, sometimes, and AFAICT `BillActionNode.vote` is never populated.

```sql
select v.id, v.bill_action_id, j.name, s.identifier from opencivicdata_voteevent as v
    join opencivicdata_legislativesession as s on v.legislative_session_id = s.id
    join opencivicdata_jurisdiction j on s.jurisdiction_id = j.id
where bill_action_id is not null;
```

The easiest way to address this _might_ be to add an `order` field to `VoteNode`, rather than to populate the missing fields.

Example GraphQL Query:
```
{
  bills(jurisdiction: "ocd-jurisdiction/country:us/state:nh/government", session: "2019", first: 100) {
    edges {
      node {
        id
        identifier
        votes(first:10) {
          edges {
            node {
              startDate
              motionClassification
              billAction {
                order
              }
            }
          }
        }
      }
    }
  }
}

```

It may make sense to split this issue up, depending on its preliminary disposition.

**Comment by jamesturk** [comment]
VoteEvent now has an order field that can be populated directly for this
