### ISSUE TITLE
WV missing a few legislators recently sworn in

### ISSUE THREAD

**Issue by emilybenson1111** [openstates/issues#323]
State: West Virginia

Short Description: a couple senators/house reps. missing from Open States, issues with missing/omitted phone numbers. 

**Missing or Incorrect legislators:**
OS missing house rep. Josh Booth. OS missing senator Mike Caputo. OS missing senator Eric Nelson.

**Data Issues:**

Missing/incorrect District Office phone number:
-Jack Woodrum: https://openstates.org/person/jack-woodrum-5VIeyXOwjRH2XcTIK6WqTS/ , https://www.wvlegislature.gov/Senate1/lawmaker.cfm?member=Senator%20Woodrum
-Mick Bates (incorrect): https://www.wvlegislature.gov/House/lawmaker.cfm?member=Delegate%20Bates , https://openstates.org/person/mick-bates-3Jl9Z0HFUHQ7Zv4xAYgsUo/

Incorrect email address (doesn't appear systemic):
-Amy Grady:  https://www.wvlegislature.gov/Senate1/lawmaker.cfm?member=Senator%20Grady , https://openstates.org/person/amy-grady-2faJ4iw2GcoVJd2hb4sNhs/

District Office Address incorrect (doesn't appear systemic): 
-Danielle Walker: https://www.wvlegislature.gov/House/lawmaker.cfm?member=Delegate%20Walker , https://openstates.org/person/danielle-walker-3nAcm8Iq73VLHx0QUxqlwC/

**Additional Data**
n/a

**Comment by jamesturk** [comment]
missing legislators resolved
