### ISSUE TITLE
MD: 2020 needs a one-off scrape

### ISSUE THREAD

**Issue by showerst** [openstates/issues#329]
State: MD

In February 2021, MD went back and overrode a veto on at least one 2020 bill.
http://mgaleg.maryland.gov/mgawebsite/Legislation/Details/hb0732?ys=2020RS&search=True

https://openstates.org/md/bills/2020/HB732/

So 2020 needs a rescrape to catch that data up.

**Comment by jamesturk** [comment]
thanks for the heads up!
