### ISSUE TITLE
MA:  new bills are delayed in being added into OpenStates

### ISSUE THREAD

**Issue by LauraBula** [openstates/issues#330]
2 Massachusetts Bills were just entered into OpenStates on 2/24, but we had identified them on the state's website on 2/9.   Is there a problem with the Massachusetts scrape? 

1) [**MA HD 898**](url) (ocd-bill/19feaf3b-5591-413b-8c59-1639062817d3) 
      a) was identified by my staff on  the Massachusetts legislature website since at least **2/9/21**.  
      b)  According to the [State's copy of the Bill ](https://malegislature.gov/Bills/192/HD898/House/Bill/Preview), it was filed on **1/28/21**.  
      c) The OpenStates information says:  
          "created_at": "**2021-02-24**T07:40:27.46072Z",
          "updated_at": "2021-02-24T07:40:27.460748Z",
          "openstates_url": "https://openstates.org/ma/bills/192nd/HD898/",
          "first_action_date": null,

2) [**MA SD 529**](url)  (ocd-bill/7d8b3c87-c34c-4c4e-a2e3-365b09b67e8e) 
     a) was identified by my staff on  the Massachusetts legislature website since at least **2/16/21**.  
     b) According to the [State's copy of the Bill](https://malegislature.gov/Bills/192/SD529/Senate/Bill/Preview) , it was filed on **2/1/2021**.
     c) The OpenStates information says: 
         "created_at": "**2021-02-24**T07:37:40.6649Z",
         "updated_at": "2021-02-24T07:37:40.664928Z",
         "openstates_url": "https://openstates.org/ma/bills/192nd/SD529/",
         "first_action_date": null,

**Comment by showerst** [comment]
There was, it was resolved in https://github.com/openstates/task-definitions/pull/19 

MA is a very challenging state to collect data from due to how their site is built, so we added some additional scraping to ensure we don't miss updates.

**Comment by LauraBula** [comment]
Thankyou!
