### ISSUE TITLE
AR: Unmatched legislators

### ISSUE THREAD

**Issue by ColbyReed** [openstates/issues#331]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Following up on findings from this PR:
https://github.com/openstates/people/pull/456

Currently there are three members who remain unmatched to their voting records after assigning voting aliases. I believe this is due to their last names matching retired legislatures as mention in the PR.

The members are:
Senator Joyce Elliott
Rep. Karilyn Brown
Rep. Jamie Scott

I believe this is also related to the work being discussed here:
https://github.com/openstates/issues/issues/22

**URL where this issue may be seen (API or OpenStates.org):**
Voting event example
https://openstates.org/vote/44220451-c352-40a3-be69-8d7ca3509057/  - Senate
https://openstates.org/vote/3a35b9b5-4176-42f9-b82a-b6444dd41bfb/   - House

**Source URL of correct data if applicable:**
https://www.arkleg.state.ar.us/Bills/Votes?id=SB1&rcs=1738&chamber=Senate&ddBienniumSession=2021%2F2021R  - Senate
https://www.arkleg.state.ar.us/Bills/Votes?id=SB1&rcs=1762&chamber=House&ddBienniumSession=2021%2F2021R  - House

**Comment by jamesturk** [comment]
this may be a core issue in name matching, needs further investigation

**Comment by jamesturk** [comment]
this appears to be fixed now 👍 thanks for the help in tracking it down
