### ISSUE TITLE
CA Legislators: some room numbers are wrong

### ISSUE THREAD

**Issue by emilybenson1111** [openstates/issues#337]
State: California
Short Description: Some wrong numbers listed incorrectly, a legislator listed on OS and not general assembly and a vacancy not listed on open states. 

Missing or Incorrect legislators:
California general assembly lists one vacancy (no name listed), open states does not. 
Shirley Weber is on the open states house roster and not Cali. GA roster. 

Data Issues:
Open States lists wrong room # for state capitol:
-Bob Archuleta
-Josh Becker
-Dave Cortese
-Josh Newman

Aguiar-Curry: lists 4 district offices, open states lists 3 
Marc Berman - district office address doesn't match, neither does the corresponding phone number

Additional Data:
open states includes links to contact congressmen/women but doesn’t include the links to their campaign/official sites (source site does include this). Open States orders names by first name whereas most of the legislature websites order them alphabetically by last name (i suggest we also order by last name because it makes roster verification easier and it also makes more sense to someone looking for a member on our website).

**Comment by jamesturk** [comment]
Thanks, and can you provide links to these in the future?  Without the links there's a lot of extra work to fix the bad numbers.

**Comment by jamesturk** [comment]
Vacancy fix is in.
