### ISSUE TITLE
OH links to legislation text in prior sessions are broken

### ISSUE THREAD

**Issue by SusanOhio** [openstates/issues#345]
Current session links correctly return the document.

Previous session links all yield error messages:

"Forbidden

You don't have permission to access /solarapi/v1/general_assembly_133/bills/hb687/IN/00 on this server."

**Comment by jamesturk** [comment]
Ohio changed things on their end and we'll have to look at whether there is a fix for the earlier session or if the documents are unavailable now.  (Far too many states make breaking changes like this, and there's little we can do.)

**Comment by SusanOhio** [comment]
The links are still available. 

I compared links from OpenStates vs the Legislature's own, and it appears all that happens is that the links need to be in secure protocol. When I manually add the "s" to the "http" in the link from OpenStates, it's identical to the link on the Legislature's site and points to a valid download.

**Comment by jamesturk** [comment]
Ah thanks!  That is indeed an easy fix and one we can make shortly.

**Comment by SusanOhio** [comment]
Thank you!
