### ISSUE TITLE
Nevada Missing Addresses

### ISSUE THREAD

**Issue by starcollector-ce** [openstates/issues#352]
**Multiple assembly members missing phone numbers but not all
-Clara Thomas
-Jill Tolles **

**https://openstates.org/person/clara-claire-thomas-6HwVJwsjLm4t14RsDOXKUK/
https://openstates.org/person/jill-tolles-7eGsyrCo6PMXugZwgAHquY/**

**https://www.leg.state.nv.us/App/Legislator/A/Assembly/Current/17
https://www.leg.state.nv.us/App/Legislator/A/Assembly/Current/25**

**Comment by jamesturk** [comment]
splitting these up was very helpful 👍  thank you
