### ISSUE TITLE
Pluralization issue with tsvector configuration

### ISSUE THREAD

**Issue by donaldwasserman** [openstates/issues#355]
In the v3 API, full text search isn't handling pluralization correctly. 

This query has 0 results 
```
https://v3.openstates.org/bills?jurisdiction=Michigan&session=2021-2022&q=firearms
```

This query has 36 results: 
```
https://v3.openstates.org/bills?jurisdiction=Michigan&session=2021-2022&q=firearm
```

This query has 36 results 
```
query MyQuery {
  bills(jurisdiction: "Michigan", session:"2021-2022", searchQuery: "firearms", first: 100) {
    totalCount
  }
}
```

My understanding is that `websearch_to_tsquery` should automatically handle pluralization like this out of the box, so it's a little perplexing

**Comment by jamesturk** [comment]
Very interesting, I'll have to dig in to figure out what might be happening here.

**Comment by jamesturk** [comment]
I've found a difference in how SQLAlchemy handles the config parameter to websearch_to_tsquery, which I believe is responsible for this and another hard to diagnose V3 issue.  I'm looking into a fix now

**Comment by donaldwasserman** [comment]
@jamesturk - I was also looking into this some more this morning and I'm not sure if this is the same issue or a related issue, but it seems like possible the `BillTitle` also isn't being added into the `SearchableBill` data (and thus vector index). 

I haven't full put together an exhaustive test-case, but it seems (like for michigan bills at least) searching for hyper-specific exact strings from the title returns 0 results from either the `q` param on the v3api _and_ the `searchQuery` field on the graphql side. 

For example `ocd-bill/b3773714-7e5d-47e2-9db1-36df249aae0e`

```title
Crimes: assaultive; reference to vulnerable adult chapter of the Michigan penal code in the public health code; modify to reflect addition of elder adults. Amends secs. 20173a & 21313 of 1978 PA 368 (MCL 333.20173a & 333.21313).  TIE BAR WITH: HB 4475'21
```

0 Results 
```
https://v3.openstates.org/bills?jurisdiction=Michigan&session=2021-2022&q=Amends%20secs.%2020173a%20%26%2021313
```

This may be to my misunderstanding how the postgres full text search is supposed to work, but i assume at least as well as `contains`

**Comment by jamesturk** [comment]
This is fixed now :)  The english analyzer wasn't running on the tsquery properly, this seems to have been the cause of both issues
