### ISSUE TITLE
FL Bills Missing for 2021 Session

### ISSUE THREAD

**Issue by mcshane4304** [openstates/issues#356]
Bills Missing from OpenStates for 2021 FL Session:

SB 540
HB 1601
HB 1617
HB 7011
HB 7019

Can be found here: https://www.myfloridahouse.gov/sections/bills/bills.aspx

Thank you!!

**Comment by showerst** [comment]
@mcshane4304 I was able to find these bills on the site -- 

https://openstates.org/fl/bills/2021/HB1601/
https://openstates.org/fl/bills/2021/HB1617/
https://openstates.org/fl/bills/2021/HB7011/
https://openstates.org/fl/bills/2021/HB7019/

I wasn't able to find an SB 540 on the FL site -- are you sure you were looking at the right session? If so, could you provide a link?

How were you searching? Maybe there's something we can improve there on the search UX.

**Comment by jamesturk** [comment]
Re: 540, looks like
https://openstates.org/fl/bills/2021/SJR540/ 
matches
https://www.myfloridahouse.gov/Sections/Bills/bills.aspx?Chamber=B&SessionId=90&BillSponsorIndex=-1&BillReferredIndex=-1&BillTypeIndex=-1&BillListIndex=-1&BillNumber=540

**Comment by mcshane4304** [comment]
Thank you!!!

Susan Sampaio
McShane Communications
Office: (813) 832-3373
Cell: (813) 724-2548

*Please note*: As we continue to work remotely with flexible hours, I may
send or respond to emails outside of typical office hours. However all
emails will be addressed at the earliest convenience. If there is an
emergency, please contact Charlie McShane at (813) 832-3373.

**Comment by jamesturk** [comment]
Going to close this, but Susan, can you clarify what led you to believe these were missing?

**Comment by mcshane4304** [comment]
Yes, waiting on client.  I'll resond as soon as I hear.

Thanks!

Susan Sampaio
McShane Communications
Office: (813) 832-3373
Cell: (813) 724-2548

*Please note*: As we continue to work remotely with flexible hours, I may
send or respond to emails outside of typical office hours. However all
emails will be addressed at the earliest convenience. If there is an
emergency, please contact Charlie McShane at (813) 832-3373.

**Comment by jamesturk** [comment]
Thanks, and in the future, if you could get that info up front before posting the issue it’d be greatly appreciated.  Most of the time these kinds of things tend to be client error.

**Comment by mcshane4304** [comment]
Yes! I will do that - thank you!

Susan Sampaio
McShane Communications
Office: (813) 832-3373
Cell: (813) 724-2548

*Please note*: As we continue to work remotely with flexible hours, I may
send or respond to emails outside of typical office hours. However all
emails will be addressed at the earliest convenience. If there is an
emergency, please contact Charlie McShane at (813) 832-3373.
