### ISSUE TITLE
[API] Enumerate the districts of a chamber?

### ISSUE THREAD

**Issue by estaub** [openstates/issues#36]
Currently the only way to get all the districts for a chamber in V2 is to walk the legislators. This fails when a seat is vacant or the legislator data is in error.

Consider adding a "posts" connection to OrganizationNodes, which is probably null for all organizations that aren’t chambers.   

It's a connection, not an array, because in the future I suspect that we may want a "currentHolders" member on PostNode to point at the legislators, and then an array might lead to corpulent responses (especially in the 400-member NH House).

**Comment by jamesturk** [comment]
this is now available in V3 via the Jurisdictions endpoint, organizations have a list of their districts by default
