### ISSUE TITLE
NV handful of bills reintroduced from prior session

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#360]
**Issue Description:** Pesky edge case in NV.There are six bills that appear to be reintroduced into the current session, but were originally introduced in a prior session. These are present in the NV bills list and marked with one or two asterisks (* or **). But these do not appear in Open States data. Some of them share an identifier (except for the asterisk!) with a totally different bill that *was* introduced first in the current session.

[AB444*](https://www.leg.state.nv.us/App/NELIS/REL/81st2021/Bill/7334/Overview)
AJR1** (distinct from AJR 1)
AJR2** (distinct from AJR 2)
AJR10*
SJR1**
SJR8*

AB444* for example merely has the action "Returned from Secretary of State. Bill read with Governor's veto message. Placed on Chief Clerk's desk."

but AJR10* has actions both "Returned from Secretary of State. Read first time. Referred to Committee on Commerce and Labor. To printer. From printer." and "To committee." in Feb 2021, so seems clearly active.

**Source URL of correct data if applicable:** 

https://www.leg.state.nv.us/App/NELIS/REL/81st2021/Bills/List
https://www.leg.state.nv.us/Session/81st2021/Reports/BillsListLegacy.cfm?DoctypeID=1 (and other DoctypeID values)

**Comment by showerst** [comment]
Bleck, good catch.

https://github.com/openstates/openstates-scrapers/blob/main/scrapers/nv/bills.py#L110 is where we're skipping, I'm going to play with this some later. While we tend to keep state identifiers, I don't like the asterisk, that's just asking for trouble with search.

I remember a similar issue in New York where they do a substitution re-using bill numbers marked in some funky way.

**Comment by showerst** [comment]
Quick tip to make testing this easier, you can add '&Filters.SelectedBillTypes=SJR' to the index url https://github.com/openstates/openstates-scrapers/blob/main/scrapers/nv/bills.py#L103
to immediately pull sjr1/sjr1*

**Comment by showerst** [comment]
I added a PR that scrapes those bills and subs asterisk for 'C', which i arbitrarily picked for carryover.

1. Should we just leave the state's identifier? It does scrape (although I didn't check postgres import) . That feels like a landmine for third parties and possibly future us (or maybe current us?). Asterisk will trip up trying to search for it in lucene/elasticsearch, sphinx, and maybe postgres depending on your settings. 
2. If we do change the ID, what should we change it to? 'C' is arbitrary and undiscoverable. 
3. We could look up the past session in __init__ and add the year -- so like "SJR1-2019", which might make more sense when browsing.
4. What do multiple asterisks mean, anything? Gotta research that.

Curious about your thoughts on this one @jamesturk @jessemortenson

**Comment by jessemortenson** [comment]
1. I agree, asterisk seems like asking for trouble.
2. Also agree that "C" is arbitrary, better but still not great
3. I am coming to the same conclusion, appending the year of prior session seems like a better option
4. The legacy bill listing has a legend:

```
* The bill was introduced in the 80th (2019) Session.
** The bill was introduced in the 32nd (2020) Special Session.
```
So it'd be `SJR 1-2020` and `SJR 8-2019`

**Comment by jamesturk** [comment]
I agree that appending the year is what we should do, it doesn’t break the fix_bill_id function we currently have so I believe it’ll work fine without modification but we can keep an eye out for other weirdness.

**Comment by showerst** [comment]
I see that we can't do it automatically, because they're pulling from specials and skipping around. We'll have to read the legend and hard code it. 

I'm thinking we do something like:

```
carryovers = {
    '2021': {
    '*': '2020Special32',
    '**': '2019'
   }
}
```

And I'll write in a code path that throws an error if the scraper encounters a session/* combo that's not in the dict. 

Offhand not sure if you can use a * as a python dict key, if not we'll sub something else.

Thoughts?

**Comment by jamesturk** [comment]
That makes sense to me, and * is fine as a dict key 👍

**Comment by showerst** [comment]
Cool, i'll jump back on this later this afternoon, working on a minor update to the ME scraper to grab committee actions first.

**Comment by showerst** [comment]
PR is updated, it changes SJR1* into SJR1-2019 

Let me know if you have feedback, otherwise i'll merge later today.
