### ISSUE TITLE
Open States Legislator Bulk Data field list describe email incorrectly

### ISSUE THREAD

**Issue by paulschreiber** [openstates/issues#362]
**Issue Description:**
On "Open States Legislator Bulk Data", `capitol_email` and `district_email` are listed. In the CSVs, only `email` is given.

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/data/legislator-csv/

**Comment by jamesturk** [comment]
thanks for reporting this, pushed a fix that'll go live in the next release
