### ISSUE TITLE
View Latest Bill Text Button

### ISSUE THREAD

**Issue by skuzmic** [openstates/issues#364]
View Latest Bill Text Button does not work on openstates.org web page.
![OKHB2293](https://user-images.githubusercontent.com/81047376/111884526-2d1b6c80-8990-11eb-9ac6-1eed1a6c07ec.jpg)

**Comment by jamesturk** [comment]
Can you link to the bill that it isn’t working on?  I believe this is a data issue as the button works for the bills I just checked.

**Comment by skuzmic** [comment]
https://openstates.org/ok/bills/2021/HB2293/

    On Saturday, March 20, 2021, 03:30:33 PM CDT, James Turk ***@***.***> wrote:  
 
 

Can you link to the bill that it isn’t working on?  I believe this is a data issue as the button works for the bills I just checked.

**Comment by jamesturk** [comment]
What happens when you click the button?  What OS/browser?  It is working for me and redirects to http://webserver1.lsb.state.ok.us/cf_pdf/2021-22%20ENGR/hB/HB2293%20ENGR.PDF

**Comment by skuzmic** [comment]
Windows 10 in Chrome

    On Saturday, March 20, 2021, 03:34:47 PM CDT, James Turk ***@***.***> wrote:  
 
 


What happens when you click the button? What OS/browser? It is working for me and redirects to http://webserver1.lsb.state.ok.us/cf_pdf/2021-22%20ENGR/hB/HB2293%20ENGR.PDF

**Comment by jamesturk** [comment]
Gotcha, thanks!  Does anything happen at all?  If you hover over the button does it show a URL in the bottom left corner?

**Comment by skuzmic** [comment]
There is a gray line with the web address in the lower left corner but by the time I move my cursor over there, it is gone.

    On Saturday, March 20, 2021, 03:34:47 PM CDT, James Turk ***@***.***> wrote:  
 
 


What happens when you click the button? What OS/browser? It is working for me and redirects to http://webserver1.lsb.state.ok.us/cf_pdf/2021-22%20ENGR/hB/HB2293%20ENGR.PDF

**Comment by jamesturk** [comment]
That grey line is part of your browser… does clicking the link on other pages work?

**Comment by skuzmic** [comment]
Yes, other links work.    On Saturday, March 20, 2021, 03:48:42 PM CDT, James Turk ***@***.***> wrote:  
 
 

That grey line is part of your browser… does clicking the link on other pages work?

**Comment by skuzmic** [comment]
Yes, other links work.
    On Saturday, March 20, 2021, 03:48:42 PM CDT, James Turk ***@***.***> wrote:  
 
 

That grey line is part of your browser… does clicking the link on other pages work?

**Comment by jamesturk** [comment]
this seems to be an isolated incident, typically I'd suggest trying disabling extensions/etc. but since it is just one link, the link you want is http://webserver1.lsb.state.ok.us/cf_pdf/2021-22%20ENGR/hB/HB2293%20ENGR.PDF but I can't reproduce this on any platform/browser I have access to

feel free to reopen with more details if you encounter again, thanks for reporting!

**Comment by skuzmic** [comment]
Thank you for your quick assistance!

    On Saturday, March 20, 2021, 06:08:49 PM CDT, James Turk ***@***.***> wrote:  
 
 


this seems to be an isolated incident, typically I'd suggest trying disabling extensions/etc. but since it is just one link, the link you want is http://webserver1.lsb.state.ok.us/cf_pdf/2021-22%20ENGR/hB/HB2293%20ENGR.PDF but I can't reproduce this on any platform/browser I have access to

feel free to reopen with more details if you encounter again, thanks for reporting!
