### ISSUE TITLE
CA legislature  address field contains phone numbers for some members

### ISSUE THREAD

**Issue by paulschreiber** [openstates/issues#367]
**Issue Description:**
In California, Steven Bradford (ocd-person/99fd8cce-55ba-493a-b787-e339a57de7d) has a phone number in the address field
```
302 W. 5th Street, Suite 203, San Pedro, CA 90731. (310) 514-8573
```

**URL where this issue may be seen (API or OpenStates.org):**
https://github.com/openstates/people/blob/main/data/ca/legislature/Steven-Bradford-99fd8cce-55ba-493a-b787-e339a57de7df.yml

**Source URL of correct data if applicable:**
https://www.senate.ca.gov/senators

**Comment by jamesturk** [comment]
to clarify, was this the only one you found? or was the problem systemic
