### ISSUE TITLE
VA legislators use "Virginia" instead of VA in address fields

### ISSUE THREAD

**Issue by paulschreiber** [openstates/issues#370]
**Issue Description:**
Most VA legislators use "Virginia" instead of VA in address fields.

Expected: VA in all cases.

```
P.O. Box 26415;Alexandria, Virginia 22313
P.O. Box 64544;Virginia Beach, Virginia 23467
P.O. Box 40366;Arlington, Virginia 22204
P.O. Box 194;Norge, Virginia 23127
P.O. Box 5811;Midlothian, Virginia 23112
5121 East Virginia Beach Blvd., Suite A-1; Norfolk, VA 23502
```

**URL where this issue may be seen (API or OpenStates.org):**
https://data.openstates.org/people/current/vt.csv

**Comment by jamesturk** [comment]
this is really a matter of preference... we don't have a policy to normalize these addresses but if you'd like to it would be welcome
