### ISSUE TITLE
CO legislators out of date

### ISSUE THREAD

**Issue by pqnelson** [openstates/issues#371]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Colorado state senate does not have current members. I was first alerted to this by the absence of Larry Liston (current state senator representing district 10) and found Owen Hill as not-yet-replaced.

**URL where this issue may be seen (API or OpenStates.org):** For Owen Hill, see https://openstates.org/person/owen-hill-1cJaYgsFSMVMMTUck0ttvU/

**Source URL of correct data if applicable:**
I defer to the great and powerful [Ballotpedia](https://ballotpedia.org/Larry_Liston), though you may prefer https://leg.colorado.gov/legislators/larry-liston

**Comment by jamesturk** [comment]
Thanks for this, is this the only mismatch in CO?

**Comment by pqnelson** [comment]
In the Senate, it appears so (even though there are four or five new state Senators in CO). I don't know about the lower chamber of CO, though.
