### ISSUE TITLE
SD: old, invalid source URLs for one legislator

### ISSUE THREAD

**Issue by paulschreiber** [openstates/issues#374]
**Issue Description:**
For `ocd-person/e40b342d-1732-4d1d-aa23-6d904e871e98` (Wayne H. Steinhauer), the source URLs listed are

```
http://legis.sd.gov/Legislators/Legislators/MemberCommittees.aspx?Member=1069&Session=2016
http://legis.sd.gov/Legislators/Legislators/MemberDetail.aspx?Member=1069&Session=2016
```

`legis.sd.gov` no longer exists. All other source correctly use `sdlegislature.gov`.

**Comment by jamesturk** [comment]
Would you be willing to submit some fixes for these kinds of tiny issues?  If you're familiar with YAML a fix to openstates/people would in most cases take about as long as submitting these issues  & would help us out a lot :)
