### ISSUE TITLE
TX: Bills: Clean up action classifier

### ISSUE THREAD

**Issue by showerst** [openstates/issues#375]
TX has a big if loop for classifying actions, this should be cleaned up into a nice regex matcher

**Comment by drvander** [comment]
Hello,
I'm a first-time contributor here. If no one else has tackled this yet I'd be happy to do it!

**Comment by showerst** [comment]
Hey @drvander ! Sorry for the late response!

The crux of this issue is that if you look at the TX scraper, we're classifying each action taken on the bill by a big if loop: 

https://github.com/openstates/openstates-scrapers/blob/main/scrapers/tx/bills.py#L192

We have code in place elsewhere to instead break this out as a list of regex, classification tuples, for instance in AL.

https://github.com/openstates/openstates-scrapers/blob/main/scrapers/al/bills.py

Porting this would make it way more readable, and you could do a scrape first with the current scraper to have reference data to compare your changes against. 

Do you have the project setup yet? If not, I can link you a guide to get started.

**Comment by drvander** [comment]
Thanks! I do have the project up and running, and I'm able to run most of the scrapers locally.

When I try to run the Texas bills one, I'm getting the same error as reported in some of the auto-closed issues:
[385](https://github.com/openstates/issues/issues/385)
[384](https://github.com/openstates/issues/issues/384)

`$ docker-compose run --rm scrape tx bills --fastmode --scrape` successfully retrieves and searches all the FTP folders, but raises the TypeError exception when it tries to save the first bill.
`21:01:10 INFO openstates: save bill HB 1 in 87 as bill_0aa41668-9b09-11eb-ab1b-0242ac120002.json
...
TypeError: 'microsecond' is an invalid keyword argument for replace()`

It looks like for the issues above they eventually successfully ran. Any idea what could be causing this on my local machine? Thanks again!

**Comment by showerst** [comment]
@jamesturk -- any idea what the cause of those is/was?

**Comment by jamesturk** [comment]
yes, sorry about that @drvander  there was a bug in a version of openstates-core that survived for ~12 hours or so and you happened to get unlucky with your initial fork.

if you try pulling & rebuilding the docker image you should see the issue go away, my apologies

**Comment by drvander** [comment]
Thanks @jamesturk -- pulling and rebuilding docker image fixed it

**Comment by johnseekins** [comment]
Given the PR was merged, can we close this issue?
