### ISSUE TITLE
sponsor identification error

### ISSUE THREAD

**Issue by pqnelson** [openstates/issues#376]
**Issue Description:**
Former (WA) state legislator [Maralyn Chase](https://github.com/openstates/people/blob/main/data/wa/retired/Maralyn-Chase-1a3cac8c-6cb6-458d-9fb5-7abb052e8e73.yml) is being tagged as a cosponsor on current legislation, instead of [Rob Chase](https://github.com/openstates/people/blob/main/data/wa/legislature/Rob-Chase-359ededd-b78a-4d25-98f7-6bc5b01876bc.yml).

(I have found this occurring in a few other states, I can dig up examples later; should I open other issues or append additional examples to this thread?)

**URL where this issue may be seen (API or OpenStates.org):**
[Openstates page](https://openstates.org/wa/bills/2021-2022/HB1219/) lists Maralyn Chase as a cosponsor.

**Source URL of correct data if applicable:**
[Official page](http://apps.leg.wa.gov/billinfo/summary.aspx?bill=1219&year=2021) links to [Representative Rob Chase (R)](https://leg.wa.gov/house/representatives/pages/default.aspx#chase)

**Comment by jamesturk** [comment]
Thanks for pointing this out, additional examples in this thread would be good, I think this is an issue that needs attention at the core level instead of state-by-state.

**Comment by pqnelson** [comment]
- [Texas HB2856](https://openstates.org/tx/bills/87/HB2856/) has [Byron Cook](https://github.com/openstates/people/blob/main/data/tx/retired/Byron-Cook-e805daee-c971-426e-b235-a9e0f93578ee.yml) as a cosponsor, it should be [David Cook](https://github.com/openstates/people/blob/main/data/tx/legislature/David-Cook-2d5f629c-76a7-455b-aff7-262d8c1c23f6.yml).
- [TX HB11](https://openstates.org/tx/bills/87/HB11/) has the same problem (Byron Cook instead of David Cook)

**Comment by pqnelson** [comment]
- [MS HB 1245](https://openstates.org/ms/bills/2021/HB1245/) has [Robert Foster](https://github.com/openstates/people/blob/main/data/ms/retired/Robert-Foster-8c4d38fb-1809-4989-bf0b-1936dcf2ade8.yml) as a cosponsor, but it should be [Stephanie Foster](https://github.com/openstates/people/blob/main/data/ms/legislature/Stephanie-Foster-1253bd3e-36dd-4f23-a671-ab24dc4aed12.yml)

**Comment by jamesturk** [comment]
after some investigation of these issues it seems like they're all coming down to favoring family_name if set and not ensuring the legislator is in office during the session in question

I'm working on a multi-step mitigation plan for this:
- [x] restore check that legislators are in office during the session in question
- [x] fix people_linter to complain when last name is missing but can be intuited from the data
- [x] fix all existing people without last name set where it can be (linter autofix rule)

**Comment by ColbyReed** [comment]
This also seems related to the unmatched legislators for vote events in Arkansas. Since the unmatched legislators share family_names with retired legislators.
https://github.com/openstates/issues/issues/331

**Comment by jamesturk** [comment]
update: as a result of openstates-core 5.9.2 all of the examples are no longer linked to incorrect people, but some are no longer linked to anyone, openstates-core 5.9.3 has a fix that will likely help with the remaining ones

**Comment by jamesturk** [comment]
this issue is now resolved at the root, some states are still awaiting a run but over the next 12-24 hours all will have resolved
