### ISSUE TITLE
Add Veto/Override vote classifications

### ISSUE THREAD

**Issue by showerst** [openstates/issues#382]
https://bobsled.openstates.org/run/a641b19d93bd4b17aef52ac3a0df55ab 

It looks like at some point we lost veto and veto override as possible vote classifications in openstates core -- see https://github.com/openstates/openstates-core/blob/cab31ede4fcb6aada04357395ce5ea3342a6a30a/openstates/data/common.py#L138

@jamesturk was that a purposeful decision? If not, I can PR it, unless you think it rises to the level of a PEP.

**Comment by jamesturk** [comment]
it was not, PR would be great
