### ISSUE TITLE
Incorrect Data for Some Georgia State Legislators

### ISSUE THREAD

**Issue by eatmorebacon** [openstates/issues#396]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Outdated data for Georgia state legislators.  Also, two links for incumbent/reelected legislators

It looks like for newly elected legislators, the API isn't picking up any data beyond the website URL (photo, address etc), even though that additional legislator information is available at the legislator URL.  See URLs below for example.

On a possibly related note, some Georgia legislators have two different links in the API.  Session 27 is the recently completed Georgia session, while Session 1029 is the more recent one.   Doesn't seem like there should be multiple links.  It is also possible that the API is trying to scrape the old Session pages for legislator info, which would explain why the content for the newly elected legislators isn't appearing.  (However, that is just speculation on my part).

**URL where this issue may be seen (API or OpenStates.org):**
One example on Openstates:  https://openstates.org/person/mesha-mainor-1EGPOtCk5V8mj1PkGPCVO8/

Also, note this partial API for a different legislator  "links":[{"url":"http://www.senate.ga.gov/SENATORS/en-US/member.aspx?Member=33&Session=27","note":""},{"url":"https://www.legis.ga.gov/members/senate/33?session=1029","note":""}

**Source URL of correct data if applicable:**
https://www.legis.ga.gov/members/house/4995?session=1029

**Comment by jamesturk** [comment]
> Philip Tsien commented in Jira:

Rylie Johnson,James Turk:

In case this is related to the work for this ticket, wanted to include a potential area of investigation that came about when testing for theCommittees release!

It looks like certain GA legislators are not showing up in Enview/showing up on any Committee Detail pages/do not have their own Legislator Detail pages (perhaps it’s those who are not connected to any piece of legislation?)

Example:Devan Seabaugh

Georgia House Committee on Creative Arts & Entertainment in Enview

Georgia House Committee on Creative Arts & Entertainment Source Website

Seabaugh was recently elected via a special election and has yet to sponsor any legislation

Seabaugh does not have a page in Enview

CC:Ruby Choonoo

**Comment by jamesturk** [comment]
> Rylie Johnson commented in Jira:

Georgia legislator info has been updated, Devan is in the enview database, and should have a page when he sponsors a bill.

**Comment by jamesturk** [comment]
> Philip Tsien commented in Jira:

Thanks so much,Rylie Johnson!🙂
