### ISSUE TITLE
HI: Votes Missing Last Letter

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#408]
**Issue Description:** Was looking at the HI matcher options, looks like the last letter of the last name is left off on the vote data but only when the legislator is excused from the vote. Might need to check regex scraping the name.

**URL where this issue may be seen (API or OpenStates.org):** Bottom 1/3ish of the list [here](https://openstates.org/admin/people/hi/matcher/)

**Source URL of correct data if applicable:** [Example bill](https://www.capitol.hawaii.gov/measure_indiv.aspx?billtype=HCR&billnumber=137&year=2021) with a few legislators with the last letter missing on scrape

**Comment by jamesturk** [comment]
fixed!
