### ISSUE TITLE
VA one bill missing: SB 906

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#411]
**Issue Description:** VA scraper is missing one bill: SB 906, which appears to be in the "carried over" set of bills from 2021 session. Virginia never sent me FTP credentials :( otherwise I'd check it out

**URL where this issue may be seen (API or OpenStates.org):** https://openstates.org/search/?query=SB+906&state=va

**Source URL of correct data if applicable:** https://lis.virginia.gov/cgi-bin/legp604.exe?211+sum+SB906

**Comment by showerst** [comment]
Did you guys get this figured out? If not, i'll take a look tomorrow when i'm back in the office.

**Comment by jessemortenson** [comment]
No, I haven't been able to get back to it yet

**Comment by showerst** [comment]
I don't think this bill was carried over, your VA link shows the 2021 session, not the "2021 Special Session I", and it's not in the bulk data at ftp://CREDENTIALS_HERE@legis.virginia.gov/fromdlas/csv212/Amendments.csv

**Comment by jessemortenson** [comment]
Hmmm, maybe I misunderstand VA's weird special session, I thought all 2021 bills were functionally carried over. Wouldn't we still expect it to show up on https://openstates.org/search/?query=SB+906&state=va under 2021? Well either way it's just one bill, if it's not in the CSV it's not in the CSV

**Comment by jamesturk** [comment]
Doing a bit of cleanup & verified that this wasn't carried over.
