### ISSUE TITLE
Additional Filter Params for v3 Bills API

### ISSUE THREAD

**Issue by donaldwasserman** [openstates/issues#413]
This is really more of a feature request, but wanted to get it tagged in the right v3 bucket. 

It would be nice to have list filter to get a list of bills based on `identifier` field.

**Proposed Query**
```
https://v3.openstates.org/bills?identifier=HB%204033&identifier=SB%20201
```

I can put a PR together for this if it's something @jamesturk feels ok with.

**Comment by jamesturk** [comment]
Is the main use case here to get multiple bills at a time?

I’m hesitant to introduce a new way to get the same behavior that already exists with q= and the individual bill lookup, but I’m open to it.

**Comment by donaldwasserman** [comment]
If you want to fetch a specific list of N bills by `identifier` (and probably by `open_states_id`) you have to make N requests, and bump into API rate limiting. `q=` doesn't really handle that use case. 

(Related,  I'd be happy to discuss purchasing a higher rate limit)

**Comment by jamesturk** [comment]
Hmm, if the main use is to deal with limits let's discuss that.  Generally I'd like to avoid adding additional ways to do the same thing.

we can discuss raising usage if you want to reach out directly to me on the Open States Slack or contact@openstates.org

**Comment by donaldwasserman** [comment]
So @jamesturk - The main thing isn't really rate limiting it's more a question of N+1 queries.

If I want to get two different bills with one api request, i'm not really sure what the path is to accomplish that. 

I don't really consider N requests to lookup N bills functionally equivalent to 1 lookup for N bills, but I won't pitch a fit if you disagree. 

For example, I want to get Michigan HB 4033 and SB 1. Theoretically something like this _should_ work, but since the `SearchableBill.search_vector` is the full bill text (I'm unclear on how that works, so am just guessing) it doesn't return the right data.

```
https://v3.openstates.org/bills?jurisdiction=Michigan&session=2021-2022&q=HB%204034%20OR%20SB%201
```

I'll follow up re: rate limiting. I think I have your email anyway.

**Comment by jamesturk** [comment]
I've been thinking about this and I'm open to it, but I think to avoid some ridiculous uses (you'd be surprised what I see) that'd do insane queries we'd need to limit N.   Do you think 10 or so would be a reasonable compromise?

**Comment by donaldwasserman** [comment]
To be honest, the implications of potential abuse never came across my mind. 

I know there are a lot of potential interactions with the various includes, so if you think 10 is a reasonable number, that works for me.  

As a side note, I don’t there is a way to accomplish this graphql right?

I left this is a half-complete state and will finish it up and put up a PR
