### ISSUE TITLE
NY A 4321 

### ISSUE THREAD

**Issue by BethSoliere** [openstates/issues#419]
Receiving error message that open states id does not exist.
ocd-bill/4774cc97-d597-43af-81f3-bff6302c565b
NY A 4321

**Comment by BethSoliere** [comment]
Same issue for MA bills: S 1372 and S 691

**Comment by jamesturk** [comment]
Hi Beth,

Can you give a bit more detail about this error so we can look into it?  Where are you seeing it?  (An API?  What call?)

**Comment by BethSoliere** [comment]
Hi James,

I am entering the id that populates here and receiving an error. This is happening on one NY bill and two MA bills.
***@***.***D74714.F0849DE0]

***@***.***D74714.F0849DE0]

**Comment by jamesturk** [comment]
Can you elaborate on "id that populates here" 

Where is the "here" that you're referring to?
Where are you entering it?

**Comment by BethSoliere** [comment]
Sorry I added screen shots, maybe they didn’t go through. It is the ID I get form the Open States API v3

**Comment by jamesturk** [comment]
No, the screenshots haven't gone through.  Without more context we can't really help you.  These bills exist, I just double checked.

**Comment by BethSoliere** [comment]
I am entering it into our system to link the Bill to Open States.

From: Beth Soliere
Sent: Wednesday, May 12, 2021 10:00 AM
To: 'openstates/issues' ***@***.***>; openstates/issues ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [openstates/issues] NY A 4321 (#419)

Sorry I added screen shots, maybe they didn’t go through. It is the ID I get form the Open States API v3

**Comment by jamesturk** [comment]
I see. 

These bills exist in Open States, I checked the IDs you provided/etc. and all return fine.

I'm not sure what your system is, how it works, etc.  but I'd recommend discussing this with whoever is responsible for it.  If they can come back to us with an Open States URL that gives incorrect data, or an error message, we can investigate further.  But as it stands this sounds like an issue in your implementation.
