### ISSUE TITLE
HB 3580

### ISSUE THREAD

**Issue by Rust64** [openstates/issues#421]
Can you help me with figuring out why this House Bill hasn't been updated with new information?  For example, if the Bill text states that it goes into effect on September 1, 2021 regardless of whether or not it gets a 2/3 vote to pass, will the Bill be honored if Texas doesn't have the funding necessary to provide the large salary increases?  Does this Bill receive Federal funding to ensure it is carried out?  How do I find out the answers to these questions if you don't know the answers?

Thank you,
Chuck Clark

**Comment by jamesturk** [comment]
Sorry, we're an aggregator of information and can't answer specific questions on legislation.  Your state's website has contact information that might help you, you can also reach out directly to your legislators.

**Comment by Rust64** [comment]
Thank you
