### ISSUE TITLE
NC: My reps not correct, districts have changed

### ISSUE THREAD

**Issue by yesicanhearyouclemfandango** [openstates/issues#422]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:** When I search for my NC representatives, the names are incorrectly given as Joyce Krawiec and Donny Lambeth. That was certainly the case prior to district boundary changes in January, but it's not now. I suspect that old district boundaries are still being used.

**URL where this issue may be seen (API or OpenStates.org):** https://openstates.org/nc/

**Source URL of correct data if applicable:** https://www.ncleg.gov/Redistricting You can run a comparison address search here: https://www.ncleg.gov/Redistricting/DistrictPlanMap/H2019E

**Comment by jamesturk** [comment]
thanks for this report, I'll take a closer look at what has changed so we can get the updated boundaries in place

**Comment by jamesturk** [comment]
I've loaded updated NC districts, I checked a couple of addresses and they seem to match but it is tough to say for sure we fixed your issue.  if not please get in touch with me privately at contact@openstates.org so we can use your address or a similar one that demonstrates the issue to try to figure out what needs to update
