### ISSUE TITLE
Incorrect unicode encoding in bulk legislator csv

### ISSUE THREAD

**Issue by mcchang** [openstates/issues#436]
**Issue Description:**
It looks like there is incorrect unicode encoding for some legislator names in the bulk legislator data. Jessica González looks correct in the [source yaml file](https://github.com/openstates/people/blob/main/data/tx/legislature/Jessica-Gonzlez-8eeb1aad-24b6-487b-bbc0-31c2238b1ccd.yml), but the corresponding row does not encode the á in her last name correctly.

**URL where this issue may be seen (API or OpenStates.org):**
https://data.openstates.org/people/current/tx.csv, `ocd-person/8eeb1aad-24b6-487b-bbc0-31c2238b1ccd`

**Source URL of correct data if applicable:**
https://github.com/openstates/people/blob/main/data/tx/legislature/Jessica-Gonzlez-8eeb1aad-24b6-487b-bbc0-31c2238b1ccd.yml

**Comment by jamesturk** [comment]
I just double checked, and the file does indeed have the correct character from what I can tell:

<img width="503" alt="Screen Shot 2021-06-30 at 10 42 40 AM" src="https://user-images.githubusercontent.com/8034/123981010-fcd06a80-d98f-11eb-9e3a-486f767e6d24.png">
I also checked with a terminal and the text showed up fine there as well.

I'm wondering if this is an issue in whatever software you're using to open the file?  CSV files do not have a built-in encoding, so if Excel or similar is opening the file with an incorrect encoding that may cause the issue.

**Comment by mcchang** [comment]
@jamesturk I mistakenly assumed when fetching `tx.csv` using the python `requests` library that it would interpret the csv contents as utf-8 directly, but since the HTTP response does not specify a `charset` in the `Content-Type` header, [`requests` interprets the contents as ISO-8859-1](https://docs.python-requests.org/en/master/user/advanced/#encodings) instead. Apologies for the trouble you went through!

Perhaps an improvement is to return `charset=UTF-8` in the HTTP response? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#syntax
