### ISSUE TITLE
NOT RECIEVING UNEMPLOYMENT BENEFITS 

### ISSUE THREAD

**Issue by hnicolediaz38** [openstates/issues#438]
i have been filing since january im owed 20 weeks of unemployment business closed down due to covid 19 im fixing to loose everything i have please help me they keep telling me it will be issued to me but im negative in my bank account

**Comment by jamesturk** [comment]
Sorry, you've reached out to a software project that helps people track state legislation- you can reach out to your legislators directly via https://openstates.org/find_your_legislator/
