### ISSUE TITLE
CO HB21-1090- Governor's signature not picked up

### ISSUE THREAD

**Issue by BethSoliere** [openstates/issues#444]
The governor signed this bill on 5/20/21 but it was not picked up by OpenStates until 6/12/21

https://leg.colorado.gov/bills/hb21-1090

**Comment by jamesturk** [comment]
Sometimes the state doesn't publish this information in a timely manner.  It is hard to say what happened here since the error isn't happening anymore, but if you notice any others that lag we can investigate if the state is behind or if there's some other issue.
