### ISSUE TITLE
AZ SB 1082

### ISSUE THREAD

**Issue by BethSoliere** [openstates/issues#451]
Stopped pulling events after 3/2/21

**Comment by LauraBula** [comment]
OS number = b0428af0-a953-43b3-a0eb-df6ef9be6248

See state page for additional information after 3/2/21 that should have been caught https://apps.azleg.gov/BillStatus/BillOverview/74437?SessionId=123  
Dates of missing events
1) 6/28/2021 
2) 6/29/2021
3) 6/30/2021

**Comment by jamesturk** [comment]
This is running now & should pick up the new data soon, the special session had superceded it so we weren't still checking for updates to that bill.

Should be up by this afternoon

**Comment by BethSoliere** [comment]
Thank you!

**Comment by jamesturk** [comment]
data is now updated
