### ISSUE TITLE
INCORRECT DISTRICT OFFICE ADDRESS

### ISSUE THREAD

**Issue by connoti-dezigned** [openstates/issues#460]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
DISTRICT OFFICE ADDRESS has been changed.
651 Old Mt. Pleasant AvenueLivingston, NJ 07039

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/richard-j-codey-mvY8LjSqT9IV5fQ1hnJsd/

**Source URL of correct data if applicable:**
https://www.njleg.state.nj.us/members/bio.asp?leg=82

**Comment by jamesturk** [comment]
thanks, just pushed a fix, should be live today
