### ISSUE TITLE
parallelism in scraping?

### ISSUE THREAD

**Issue by azban** [openstates/issues#47]
State: n/a

don't know where the correct place for this is given guide, but let me know if i should address this elsewhere.

the MA scrape is quite slow (~12hrs) and i'm guessing other states are slow because of the single threaded nature of pupa/scrapelib. this makes it harder for developers to test that their changes are not causing regressions, and also presumably costing $$ for compute.

- has parallelism in pupa/scrapelib been explored? 
- are y'all open to considering a different framework for high level scraping for states, as implemented? seems like scrapy has a solid framework, with strong usage + development, for things that scrapelib are trying to accomplish with some solid additions like parallelism and some bonus features that would be nice like stats reporting, general sugar, auto throttling, etc.. i think this could be tested as a drop in replacement from state to state with minimal friction. pupa could run scrapy , and get the same json as expected, with a little upfront work.

i did a quick test with MA (only bills, no child pages (actions/sponsors/votes)) and am seeing ~270+ bills/min with a scrapy implementation, as opposed to ~12 bills/min as is (with same modifications).. guessing the difference will grow when the scrapes for child pages are included.

**Comment by jamesturk** [comment]
going to close this out as I don't think we're likely to move forward on any parallelization in the near term
