### ISSUE TITLE
Documentation Issue: Text Extraction

### ISSUE THREAD

**Issue by AliAbstract** [openstates/issues#473]
Now that the Text Extraction archive is no longer available and has been fully merged into OS Core, the documentation for contribution to Text Extraction (https://docs.openstates.org/en/latest/contributing/text-extraction.html) is very out of date, from general facts and links being wrong due to its move down to some mechanics as well.

I'd love it if someone more familiar with the move from its own repository to OS-core could update the documentation as I use it to remember certain quirks of openstates as I'm working on it.

**Comment by jamesturk** [comment]
Thanks for the nudge on this, on my radar now :)
