### ISSUE TITLE
Montgomery & Stewart Co. Septic Permit

### ISSUE THREAD

**Issue by Treist1** [openstates/issues#474]
The application process for a new septic permit in Montgomery and Stewart counties is broken. There is a backlog that is at least 3 months behind. The actual length of time it takes to get a permit is unknown. One of many serious problems is created by this backlog. I will explain the problem that this back up has created for me and for many others. 
  When purchasing land to live and build on a contract is created. The contract has a final date in which to be executed. In order to build a home the land has to pass a percolation test. Without the passing test the lender will not lend to a buyer To build his/her home. My contract date is quickly approaching and there is still no percolation test scheduled. We submitted a request for a percolation test and a septic permit on June 10th of 2021 it is now August 20 and there is no one in the department of environment and conservation who can tell us when the test will be conducted. When The contract date is reached with no septic permit we will lose the contract.
   It is absolutely unreasonable that someone should have to wait three or four or even five months for a septic permit. It is unfair to both sellers and buyers. 
   I have been told over the phone by department of energy environment and conservation staff that new employees have been hired and are being trained but this does nothing to solve the tremendous backlog that is currently bogging down Montgomery and Stewart counties Septic permit process.  
   
Please help, sincerely,
Terry Reist
Treist1@gmail.com

**Comment by jamesturk** [comment]
Hi Terry,

We are an aggregator of government information, with no official role in any state.

You can reach out to your local elected officials via https://openstates.org/find_your_legislator/

Good luck,

James
