### ISSUE TITLE
Add Way to Exit Scrape Without Objects But Also Without Throwing Error

### ISSUE THREAD

**Issue by jamesturk** [openstates/issues#480]
Possibly add something like anNoObjectsFoundYetexception that scrapers can throw when there are no objects returned but they do not wantos-updateto error out

*Will help with running events scrapers regularly without issues*

**Comment by jamesturk** [comment]
just added a check for this, now if a scraper raises `openstates.scrape.EmptyScrape` before it yields any objects no error will be raised (a warning will be printed to make it clear what is happening)

this will be released in the upcoming 6.5.0 `openstates-core` release

cc @showerst

**Comment by showerst** [comment]
@jamesturk after that openstates-core release, someone from GH will do a pass at implementing this in the current states where it's testable.
