### ISSUE TITLE
GA - Missing Legislator Data

### ISSUE THREAD

**Issue by DJQuez** [openstates/issues#483]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
I have noticed multiple GA legislators in both chambers who do not have all their data from the Georgia General Assembly website.

Examples Of Missing Data:
Photo
Email Address
Capitol Office Address
District Office Address

**URL where this issue may be seen (API or OpenStates.org):**
Just a few of many I have noticed:

Michelle Au: https://openstates.org/person/michelle-au-2DBtuVLPbEzNmUsDtSlW1G/
Sonya Halpern: https://openstates.org/person/sonya-halpern-1IdTXHeguTGekIBduzRhoC/
Will Wade: https://openstates.org/person/will-wade-4c6xvumknUctjjrL1jLkqt/

**Source URL of correct data if applicable:**
Michelle Au: https://www.legis.ga.gov/members/senate/4983?session=1029
Sonya Halpern: https://www.legis.ga.gov/members/senate/4985?session=1029
Will Wade: https://www.legis.ga.gov/members/house/4988?session=1029

can pair w/ james or rylie on this!🙂

**Comment by jamesturk** [comment]
> Philip Tsien commented in Jira:

Can be paired with James!
