### ISSUE TITLE
Design problem: address search box obscured by button

### ISSUE THREAD

**Issue by JoeGermuska** [openstates/issues#508]
Example URL: https://openstates.org/find_your_legislator/
Browser: Firefox 93.0 on MacOS

The "Enter your address" field is obscured by the "Search by address" button. 

![image](https://user-images.githubusercontent.com/46313/137945476-24f3047a-49e8-43ea-a3ba-ea066a3c89a4.png)

**Comment by jamesturk** [comment]
Thanks for the report Joe, I’ll take a look at this soon

James

**Comment by jamesturk** [comment]
just pushed a fix, thanks again
