### ISSUE TITLE
/events endpoint not returning any results

### ISSUE THREAD

**Issue by connorts** [openstates/issues#512]
**API Query :**
/events?jurisdiction=Indiana
/events?jurisdiction=Illinois
/events?jurisdiction=New York

**Please describe the issue:**
No event results returned. 
Response Body:
```
{
  "results": [],
  "pagination": {
    "per_page": 20,
    "page": 1,
    "max_page": 1,
    "total_items": 0
  }
}
```
Response Headers:
```
 content-length: 81 
 content-type: application/json 
 date: Thu,21 Oct 2021 21:47:23 GMT 
 server: uvicorn 
```

**Comment by jamesturk** [comment]
Sorry about this! Event data is not yet available in all jurisdictions- MN, GA, TX for now.  We'll be turning more on (and making this much more clear) soon.
