### ISSUE TITLE
Bills with future-dated action repeat email notification daily.

### ISSUE THREAD

**Issue by jtheletter** [openstates/issues#544]
Followed bills that get assigned a future-dated action will trigger daily emails of the same action.

Examples:

https://openstates.org/ga/bills/2021_22/SB100/

In May, Georgia SB 100 was assigned an effective date of July 1. So from May to July, an email was sent every day with a false alert that the bill had new activity.

https://openstates.org/ok/bills/2022/SB1103/

In November, Oklahoma SB 1103 was filed and assigned a date of authoring and first reading for February 7. So from now until February, an email is being sent every day with a false alert that the bill has new activity.

Can this daily false-positive recurrence be prevented? Thank you.

**Comment by jamesturk** [comment]
Thanks for pointing this out, and sorry for the duplicate emails- we’ll take a look and determine the best course of action.

James

**Comment by jamesturk** [comment]
This should be fixed now

https://github.com/openstates/openstates.org/commit/f53295748091456cdd64deed816878245fa86879
