### ISSUE TITLE
NH- No data for 2022 bills in Open States

### ISSUE THREAD

**Issue by BethSoliere** [openstates/issues#557]
New Hampshire 2022 bills not linking; no data in open states

http://www.gencourt.state.nh.us/bill_status/legacy/bs2016/Bill_status.aspx?lsr=2137&sy=2022&sortoption=&txtsessionyear=2022&txtgstatus=02,03

**Comment by NewAgeAirbender** [comment]
Hey Beth, sorry this took so long. We were waiting on updates from New Hampshire's bulk data endpoints, but the 2022 session is now available on Open States! That bill in particular: [https://openstates.org/nh/bills/2022/HB1022/](https://openstates.org/nh/bills/2022/HB1022/)

**Comment by BethSoliere** [comment]
Awesome! Thank you!
