### ISSUE TITLE
MN: No Senate votes

### ISSUE THREAD

**Issue by estaub** [openstates/issues#57]
I opened this as a separate issue, as opposed to amending https://github.com/openstates/openstates/issues/1906, since I'm guessing that after fixing this the original entity-resolution issue will remain.  Please re-org if useful.

**Comment by jessemortenson** [comment]
Collecting context about this old issue: 

* The existing [Votes scraper for MN works](https://github.com/openstates/openstates-scrapers/blob/870f74440984c4c5c547febb48bc4251fa719c32/scrapers/mn/vote_events.py), but only for the House of Representatives (lower chamber). The MN Senate votes are not collected in one place, but rather are scattered throughout the narrative text of proceedings recorded in PDFs called Journals, [as described here by the MN legislature](https://www.lrl.mn.gov/guides/guides?issue=ratings).
* The goal is to get a full dataset of [Vote Events](https://github.com/openstates/openstates-core/blob/80ce66047a061a653bc9a2355945bacf70d6e9ec/openstates/scrape/vote_event.py#L9) for MN in both House and Senate, including [classification](https://github.com/openstates/openstates-core/blob/c6e034093dafd2604af2f310bd1d80ad11e3ca32/openstates/data/common.py#L139), motion text, the result of the vote (eg total number of votes, pass vs. fail) and also the yes/no vote of each member who voted.
* [Journals can be found here](https://www.senate.mn/journals/index.html), and for example the [Senate 2023-2024 journals can be found here](https://www.senate.mn/journals/journal_list.html?display_ls_year=93#2023regular).
* This is unstructured text data, so it's tricky to consistently recognize and parse. Some votes are on procedural motions within the body, which we do not need to record. We are concerned with votes on Bills and amendments to Bills.
*  [Examples within the most recent Senate journal](https://www.senate.mn/journals//2023-2024/20230522077.pdf):
    * "CALL OF THE SENATE" on the first page is just a roll call, not a vote on a bill, so we do not need to parse it out.
    * "The Senate resumed consideration of S.F. No. 2995 and the Utke motion" on page 692 of the PDF (labeled page 11336 in the upper left corner) is a vote on a bill (SF 2995). You can see this correspond to an action listed on the bill page labeled ["Motion to reject CC report, did not prevail" on the bill page]](https://www.revisor.mn.gov/bills/bill.php?b=senate&f=SF2995&ssn=0&y=2023) with a reference to page 11336 of the Senate Journal next to the vote summary.
* One option is to write scraper logic that parses through each large Senate Journal PDF, identify votes on bills from the text that are peppered within those documents. Another option would be to incorporate logic into the MN Bills scraper to recognize when a vote is mentioned in a Bill Action ("Motion to reject CC report, did not prevail" from the example above, but others like it on that bill), and then load the Senate Journal, find the matching page, and then parse the text within that page (possibly including the following page) to get the details about the vote.

**Comment by braykuka** [comment]
@jessemortenson, is it possible to scrape this website https://legiscan.com/MN/votes/HF1938/2023 instead of scraping https://www.senate.mn/ for votes?
