### ISSUE TITLE
UT prefiled bills not info in OpenStates

### ISSUE THREAD

**Issue by BethSoliere** [openstates/issues#585]
No info in Open States for Utah bills 2022 session prefiled 12/2021

https://le.utah.gov/~2022/bills/static/SB0043.html

**Comment by NewAgeAirbender** [comment]
Thank you for spotting that, will have the 2022 bills available today.

**Comment by NewAgeAirbender** [comment]
Bill data now available

**Comment by BethSoliere** [comment]
Thanks! There is a similar situation happening with the NH 2022 bills. I added it as an issue awhile back it is #557.
