### ISSUE TITLE
Incorrect session classifications for West Virgina Bill API

### ISSUE THREAD

**Issue by msicknick** [openstates/issues#597]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
I wrote an API to pull sessions for each state and grab the most recent regular session:
if($session['classification'] != 'special') {
     $sessionslist[] = $session;
}

However, as you can see in the sample data below, the last three Special Sessions are classified as primary not special, and my code is pulling the wrong session as the latest one.

**Sample data:**
[{"name":"2011 Regular Session","classification":"primary","identifier":"2011"},{"name":"2012 Regular Session","classification":"primary","identifier":"2012"},{"name":"2013 Regular Session","classification":"primary","identifier":"2013"},{"name":"2014 Regular Session","classification":"primary","identifier":"2014"},{"name":"2015 Regular Session","classification":"primary","identifier":"2015"},{"name":"2016 Regular Session","classification":"primary","identifier":"2016"},{"name":"2017 Regular Session","classification":"primary","identifier":"2017"},{"name":"2018 Regular Session","classification":"primary","identifier":"2018"},{"name":"2019 Regular Session","classification":"primary","identifier":"2019"},{"name":"2020 Regular Session","classification":"primary","identifier":"2020"},{"name":"2021 Regular Session","classification":"primary","identifier":"2021"},{"name":"2021 First Special Session","classification":"primary","identifier":"20211S"},{"name":"2021 Second Special Session","classification":"primary","identifier":"20212S"},{"name":"2021 Third Special Session","classification":"primary","identifier":"20213S"}]

**Comment by showerst** [comment]
Thanks for the bug report, I'll drop in a fix for this today.
