### ISSUE TITLE
Committees with Identical Names

### ISSUE THREAD

**Issue by csnardi** [openstates/issues#598]
update-database [has been failing] (https://github.com/openstates/people/runs/4721084103) because the committee update cannot complete. This is because multiple Alaska committees have the same name & chamber (e.g. [Judiciary](https://github.com/openstates/people/blob/main/data/ak/committees/lower-Judiciary-3c4e9b5c-8e06-4125-b415-110fa96f4680.yml) and [Judiciary](https://github.com/openstates/people/blob/main/data/ak/committees/lower-Judiciary-1eaa5f0f-1ec2-42d0-97e6-a08cddecfd6b.yml)), and committee syncing occurs with `coms_by_chamber_and_name`.  Potential solutions include either changing `coms_by_chamber_and_name` to account for whether a committee is a subcommittee, or just renaming the Alaska committees (they appear to be the only ones with duplicate names currently).

**Comment by jamesturk** [comment]
looking at this today, thanks for flagging

**Comment by jamesturk** [comment]
> Philip Tsien commented in Jira:

James Turk: If you could please add a rough estimate for this when you’re able to (no rush at all), that would be great! Thank you so much!
