### ISSUE TITLE
Representative Corey Paris Missing Fields in openstates/people

### ISSUE THREAD

**Issue by calebclimatecabinet** [openstates/issues#607]
The[ .yml file for Corey Paris](https://github.com/openstates/people/blob/main/data/ct/legislature/Corey-P-Paris-fcc3d3fa-4b4d-4d3c-b512-003a58657a85.yml) is missing the fields `given_name` and `family_name`.

I believe this could also be causing Rep. Paris from being excluded from the website's [bulk download page's](https://openstates.org/data/legislator-csv/) .csv download. That is, the Connecticut .csv (link: https://data.openstates.org/people/current/ct.csv) does not contain Rep. Corey Paris.

**Comment by jamesturk** [comment]
Thanks for this, the fields themselves are allowed to be missing, but Corey Paris missing from the bulk download is something we'll investigate.

**Comment by jamesturk** [comment]
> James Turk commented in Jira:

This issue is actually affecting lots of people data exports, need to look at what it is.
