### ISSUE TITLE
Person Database Updating Failing Due to people_admin.UnmatchedName

### ISSUE THREAD

**Issue by csnardi** [openstates/issues#608]
After I merged in https://github.com/openstates/people/pull/666, updating the database failed:

```
psycopg2.errors.ForeignKeyViolation: update or delete on table "opencivicdata_person" violates foreign key constraint "people_admin_unmatch_matched_person_id_c2c06fdb_fk_opencivic" on table "people_admin_unmatchedname"
DETAIL:  Key (id)=(ocd-person/21523bd3-e711-4c97-82fa-84a1fb55a6f1) is still referenced from table "people_admin_unmatchedname".
```

Looks like it should set the ForeignKey to null on delete though? https://github.com/openstates/openstates.org/blob/main/people_admin/models.py#L52

**Comment by jamesturk** [comment]
Taking a look at this, it does look like it should be setting those to null.

**Comment by jamesturk** [comment]
Ah, so the models in openstates.org aren't loaded when these scripts run, which is an issue that will be pretty hairy to untangle.  For now I have a way to manually load them locally but it isn't fit for production, but did allow me to run the update against the database without issue.  Doing that now for the latest, and will continue to think on a good solution here.
