### ISSUE TITLE
wrong email address

### ISSUE THREAD

**Issue by rep-nn** [openstates/issues#609]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Someone created a page about me without my knowledge and without providing an opportunity for me to review it for accuracy.  The email address is wrong and needs to be corrected ASAP.

The email address is missing "rep." at the beginning.  It should be:
rep.nancynathanson@oregonlegislature.gov

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/nancy-nathanson-6jfGpw2JFXnrUvyN2mirrX/

**Source URL of correct data if applicable:**

**Comment by jamesturk** [comment]
Thank you for reporting the issue, we'll have it fixed today.
