### ISSUE TITLE
CT: Missing Vote Data for Lower Chamber

### ISSUE THREAD

**Issue by ilyagerner** [openstates/issues#61]
State: CT

Votes seem to be missing from the CT lower chamber between [July 20, 2015 and February, 2018](https://openstates.org/ct/legislators/CTL000044/votes/?page=38). I assume this is related to openstates/openstates-scrapers#1803, wherein the issue was fixed but the old data never scraped.

Also, this is my first time opening an issue anywhere, so forgive me if anything about this note is improper.

**Comment by serixscorpio** [comment]
A spot check for session year 2020 show votes are included on individual bills pages (if the bill makes it that far in the process). For example, [HB 6002](https://cga.ct.gov/asp/cgabillstatus/cgabillstatus.asp?selBillType=Bill&bill_num=HB06002) has Senate/House vote results.  Please see below gif.  It's my first time looking at CT, so I could be mistaken or not understand things as intended.  Thanks.

![vokoscreen-2020-08-09_12-24-41](https://user-images.githubusercontent.com/1740566/89737037-01202c00-da3c-11ea-9b01-69c66478f4b8.gif)

**Comment by jamesturk** [comment]
Thanks for looking at this, I'll update the issue from marked upstream to something that we can tackle
