### ISSUE TITLE
Rhode Island bills not linking to OpenStates for 2022

### ISSUE THREAD

**Issue by BethSoliere** [openstates/issues#617]
![image](https://user-images.githubusercontent.com/77754422/150377657-ae1cab78-8023-40fd-9350-980537e75ff4.png)

**Comment by jamesturk** [comment]
Hi Beth,

We do have RI 2022 bills: https://openstates.org/ri/bills/?session=2022

The bug report you submitted is just an image that doesn't tell us how to reproduce your issue.  I just verified though and 2022 bills are in our API and on the site.

**Comment by BethSoliere** [comment]
Thanks and sorry about that!

**Comment by BethSoliere** [comment]
The bill I am looking for is HB 6600, I am not seeing any bills that start with a six in OpenStates.

http://webserver.rilin.state.ri.us/BillText/BillText22/HouseText22/H6600.pdf

***@***.***

**Comment by showerst** [comment]
Hi Beth; this looks to be a scraper issue. In past years they've started their second year of a biennium with 7000; so we aren't currently scraping the 6000 series. I'm going to get that change made, once it's been tested you can expect to see the new bills in a day or two.

**Comment by BethSoliere** [comment]
Thank you! It sounds like this is the only bill so far that starts with a 6, possibly it could be a state error.
