### ISSUE TITLE
Many people have multiple IDs

### ISSUE THREAD

**Issue by calebclimatecabinet** [openstates/issues#620]
**Issue Description:**
I see @csnardi has been working on removing people with duplicate IDs -- I've found 59 more, mainly in the openstates/people/[state]/retired datasets.

Not sure what the best format is for reporting them, but attached is a summary:
[open_state_duplicates_small.csv](https://github.com/openstates/issues/files/7917439/open_state_duplicates_small.csv)

**Comment by csnardi** [comment]
I've been manually verifying apparent duplicates to make sure they're the same person and then merging them as appropriate. Happy to do that for these, though feel free to submit a PR if you want!

**Comment by calebclimatecabinet** [comment]
I'm pretty confident these duplicates really are the same person. Since you're on a roll would you merge these as well? I'd be happy to review whatever you can get to.

**Comment by csnardi** [comment]
These should all be merged now. They're hard to review, but let me know if you notice any mistakes or misses!
