### ISSUE TITLE
MD Bill events not being captured when date is out of numerical order

### ISSUE THREAD

**Issue by BethSoliere** [openstates/issues#625]
Not capturing last even if the date is out of numerical order.

1/7/22 Event not captured
https://mgaleg.maryland.gov/mgawebsite/Legislation/Details/sb0189?ys=2022RS

![image](https://user-images.githubusercontent.com/77754422/151842796-ce705e15-9033-48cd-9dbf-a20ac5ecc31d.png)

**Comment by jamesturk** [comment]
There isn't a 1/7 event on the history page at the URL linked, can you clarify what you're referring to?

<img width="1269" alt="Screen Shot 2022-02-01 at 12 01 37 PM" src="https://user-images.githubusercontent.com/8034/152014953-7f3f6454-795d-4199-b8b9-d004c2a49fc6.png">
?

**Comment by BethSoliere** [comment]
Sorry, there are two bills that did the same things. This is the link so to HB 33 with the 1/7 event.

https://mgaleg.maryland.gov/mgawebsite/Legislation/Details/hb0033?ys=2022RS

**Comment by jamesturk** [comment]
HB33 has the 1/7 data: https://openstates.org/md/bills/2022/HB33/

**Comment by BethSoliere** [comment]
Ok it may be an issue on my end. Thanks!
