### ISSUE TITLE
Kentucky General Assembly Data

### ISSUE THREAD

**Issue by raginggoat** [openstates/issues#631]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
The district and general assembly data is incorrect. 

**URL where this issue may be seen (API or OpenStates.org):**
An example is here: https://openstates.org/find_your_legislator/?lat=38.22528&lon=-85.58986&address=9201%20Bunsen%20Pkwy%20Louisville,%20KY%2040220&state=

**Source URL of correct data if applicable:**
https://legislature.ky.gov/Legislators/Pages/default.aspx

**Comment by jamesturk** [comment]
Hi, It looks like that address is right on the border of a district- can
you clarify what results you were expecting to see so we can help diagnose?

**Comment by raginggoat** [comment]
According to data on legislature.ky.gov, the districts and legislators for this district are incorrect. If you go to https://apps.legislature.ky.gov/findyourlegislator/findyourlegislator.html and enter the sample address, you can see that OpenStates is returning the outdated legislator and district info for the state legislature. For the state senate, OpenStates shows Paul Hornback from district 20 and house rep Tina Bojanowski from district 32. According to ky.gov, those are the former legislators and districts. They should now be Senator Karen Berg District 26 and Representative Josie Raymond District 31. This is just one example that I'm aware of.

**Comment by johnseekins** [comment]
When I compare the two sites, we now get the same data. @raginggoat, can you confirm this issue is resolved?

**Comment by raginggoat** [comment]
It appears to be up to date now.
