### ISSUE TITLE
Is API for bills/ working?

### ISSUE THREAD

**Issue by wmaallison** [openstates/issues#639]
If I try to filter for subjects using the bills/ api but keep getting null results even though the web page displays plenty of results for that subject.

For example, Alaska and Debt in the 32d legislative session yields 15 results when I search online but the API says there are no results...

https://v3.openstates.org/bills?jurisdiction=Alaska&session=32&subject=Debt&sort=updated_desc&page=1&per_page=20&<<My API KEY>>

Same thing happens when I use created since instead of the session ID

https://v3.openstates.org/bills?jurisdiction=Alaska&classification=bill&subject=Debt&created_since=2021-01-01&sort=updated_desc&page=1&per_page=20&apikey=<<MY API KEY>>

Both return this as a result:

{
  "results": [],
  "pagination": {
    "per_page": 20,
    "page": 1,
    "max_page": 1,
    "total_items": 0
  }
}

The same thing happened when I tried a subject filter in Arizona. Of course, it might be me doing something incredibly stupid, but if it is I can't figure out what it is. Should add: If I take out the subject "Debt" the API produces results.

**Comment by NewAgeAirbender** [comment]
Hello! Thanks for bringing this up, sorry for the late response. Subjects are case-sensitive, and AK has completely uppercase subjects, so if you'd like to get bills on debt you'd use a query like
[https://v3.openstates.org/bills?jurisdiction=Alaska&session=32&subject=DEBT&sort=updated_desc&page=1&per_page=20&apikey=](https://v3.openstates.org/bills?jurisdiction=Alaska&session=32&subject=DEBT&sort=updated_desc&page=1&per_page=20&apikey=)<>

This can vary across jurisdictions, so it may be helpful to run an initial query to check what kind of case the jurisdiction has before adding the subject to it.

**Comment by wmaallison** [comment]
Thanks so much for getting back to me -- I assumed it was some knuckleheaded error on my part.

Keep up the great work, Open States is a treasure! I tell every reporter I know about it!

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------
