### ISSUE TITLE
Wrong Senator

### ISSUE THREAD

**Issue by UriWeg** [openstates/issues#668]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**

Brian Benjamin is no longer in the state senate in new york. he became lt. governor. https://en.wikipedia.org/wiki/Brian_Benjamin

**URL where this issue may be seen (API or OpenStates.org):**
https://v3.openstates.org/people.geo?include=offices&lat=40.8079468&lng=-73.9665422&apikey=8394eab6-5e14-4617-8335-7d7d44a766ed

**Source URL of correct data if applicable:**
https://www.nysenate.gov/senators/cordell-cleare

**Comment by shelomo** [comment]
Aby updates this is causing issues within our system?

**Comment by putorti** [comment]
I went ahead and created a pull request if someone can grab and merge, I also noticed that the Governor is still Cuomo in the data? I'll make one there next. https://github.com/openstates/people/pull/737

**Comment by putorti** [comment]
Added a PR for Cuomo/Hochul: https://github.com/openstates/people/pull/742

**Comment by johnseekins** [comment]
Both PRs were merged. Please re-open if this issue is persisting...
