### ISSUE TITLE
VA Scrape Failing since at least 4-08-2022

### ISSUE THREAD

**Issue by mwhipple20** [openstates/issues#688]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**

**URL where this issue may be seen (API or OpenStates.org):**

**Source URL of correct data if applicable:**

**Comment by NewAgeAirbender** [comment]
Hey, can you give me more detail on where you're seeing this? There's the appropriate amount of bills for both the 2022 regular and special session.

**Comment by mwhipple20** [comment]
Hello,

I am not getting event updates for VA bills. None of the Gov signing events have been caught, we have had to manually add them.

**Comment by NewAgeAirbender** [comment]
This should be fixed now!

**Comment by mwhipple20** [comment]
Thank you!
