### ISSUE TITLE
States broken due to stricter vote classification

### ISSUE THREAD

**Issue by showerst** [openstates/issues#69]
**Issue Description:**
A few states broke because they have vote classifications of "other" or something else not in the tighter list.

- [x] [CA](https://bobsled.openstates.org/run/f0ee5a9a42044e63a5aa9d6554295584)
- [x] [KY](https://bobsled.openstates.org/run/3342117d764d43b7a3ea1bdda35a8fd4)

**Comment by doubleswirve** [comment]
`LA`, `WI` might be part of this as well.

**Comment by showerst** [comment]
All fixed.
