### ISSUE TITLE
Question: Why are the results different from /people.geo versus OpenStates.org?

### ISSUE THREAD

**Issue by arheinjohnson** [openstates/issues#738]
**API Query:**
```
curl -X 'GET' \
  'https://v3.openstates.org/people.geo?lat=33.918260&lng=-118.408960' \
  -H 'accept: application/json' \
  -H 'x-api-key: <omitted>'
```

**Please describe the issue:**

Thank you for this awesome tool.

Why are the results different between using /people.geo versus the [openstates.org](http://openstates.org/) website?

https://openstates.org/find_your_legislator/?lat=33.91809&lon=-118.40899&address=211%20Sierra%20Street%20El%20Segundo&state=

**Comment by NewAgeAirbender** [comment]
Good question! The API endpoint is meant to only be state legislators, whereas the Find Your Legislator page is for state & federal. Will look into why federal house reps are showing up on the API response.

**Comment by NewAgeAirbender** [comment]
We've got a ticket in the backlog to add federal legislators to that response so it will be the same results.
