### ISSUE TITLE
Error running init-db.sh

### ISSUE THREAD

**Issue by arheinjohnson** [openstates/issues#748]
**Issue Description:**
I've cloned the openstates-scrapers repository, and reading the documentation here I should run init-db.sh
https://docs.openstates.org/contributing/local-database/

But I'm hitting this error on the command docker-compose run --rm --entrypoint 'poetry run os-initdb' scrape
(image attached)

psycopg2.OperationalError: could not translate host name 'db' to address: Name or service not known

<img width="841" alt="Screen Shot 2022-07-25 at 7 26 03 AM" src="https://user-images.githubusercontent.com/35582206/180800885-7b64b6ae-dba0-434a-92b5-2559e8bc3757.png">

**Comment by johnseekins** [comment]
@arheinjohnson Can you try this branch and see if it resolves your problem? https://github.com/openstates/openstates-scrapers/pull/4091

**Comment by arheinjohnson** [comment]
Sorry, this seems to have resolved on its own, or at least I'm unable to reproduce it.
