### ISSUE TITLE
Issues receiving email alerts

### ISSUE THREAD

**Issue by laceycoppage** [openstates/issues#768]
This is the right template to select if you're reporting an issue with the functionality of OpenStates.org.
If this is a data issue, please select data issue instead!

Example URL: https://openstates.org/<path-to-page>
Browser: 

Please describe the issue: I have various email alerts/subscriptions set for legislation tracking purposes. I have alerts set for searches (i.e., bills with the words "public defender") as well as alerts set on bills that I have chosen to follow (i.e., so I am notified when there is any new activity on that bill). However, I have noticed I do not always receive an email when there has been new activity on a bill that I am following. This makes me concerned that I also am not always being notified when new bills are introduced that meet my search alerts. Is this something you have encountered before? Maybe I need to change my settings in some way? Any help is appreciated!

Please attach a screenshot if applicable!

**Comment by NewAgeAirbender** [comment]
This should be working again, please let us know if that's not the case.
