### ISSUE TITLE
Can't use other_names values with ScrapePerson model

### ISSUE THREAD

**Issue by ColbyReed** [openstates/issues#769]
When trying to scrape for other_names values for vote matching, I am unable to due to the model not supporting it.

Link to model:
https://github.com/openstates/openstates-core/blob/main/openstates/models/people.py#L176

**Comment by NewAgeAirbender** [comment]
Can you share a case where it's needed?

**Comment by ColbyReed** [comment]
From what I understand, this is needed to make sure votes are matched to legislatures as mentioned in this past issue:
https://github.com/openstates/issues/issues/254

I had a previous PR where I added this functionality in the previous people scraper.
https://github.com/openstates/openstates-scrapers/pull/3604
