### ISSUE TITLE
Open States Enhancement Proposal for campaign finance?

### ISSUE THREAD

**Issue by crkrenn** [openstates/issues#783]
Hi, I'm interested in correlating open states data with campaign finance data. Below are a few data sources that I found on a quick search. 

Would you/have you considered doing this under the open states umbrella?

At a minimum, it would require a schema and table for donations. Would it be helpful to sketch out a OSEP (Open States Enhancement Proposal)?

https://mainecampaignfinance.com/#/index
https://sunshine.sos.idaho.gov/
https://illinoissunshine.org/
https://dos.elections.myflorida.com/campaign-finance/contributions/
https://www.sos.ca.gov/campaign-lobbying/cal-access-resources/raw-data-campaign-finance-and-lobbying-activity
https://github.com/maplight/CAPS

**Comment by showerst** [comment]
Hi @crkrenn! -- Years back I know someone folks had adapted the older opencivicdata formats for campaign finance in California, you might want to reach out to them -- https://californiacivicdata.org/

Openstates has several groups of active contributors, I know my company doesn't have bandwidth to commit to helping you build out the backend/migrations for this, but pinging @jessemortenson and @putorti in case they would be interested.

For this to fall under the Openstates umbrella we'd want some kind of commitment to ongoing maintenance for the scrapers, which is usually the big pain point in adding new data sets like this.

**Comment by crkrenn** [comment]
@showerst, thanks for the response!

I also sent a note to open states tech support, and Rylie Johnson (see below) suggested I look at Follow The Money, which has collected a lot of campaign finance data. 

-Chris

Hello,

Excellent question! There are some organizations that provide data for this already, namely Follow the Money which is now a part of OpenSecrets. They provide bulk data and an API as well.

Best,

Rylie Johnson
