### ISSUE TITLE
Proposal for repo for state districting info

### ISSUE THREAD

**Issue by crkrenn** [openstates/issues#787]
Hello,

What are your thoughts for adding a curated repo for state districting info?

I'm about to scrape information on what towns are in each state senate and house district for Maine, and I thought that open states might be a good place to host this type of information in a structured way. 

I need this info to map 2020 presidential election results to legislator. 

I could help support this for other states, but my current focus is on Maine. 

Sincerely,

- Chris Krenn

https://legislature.maine.gov/senate/district-listing/9526

https://legislature.maine.gov/house/house/MemberProfiles/ListDistrictTowns

**Comment by johnseekins** [comment]
Are you describing something like this tool, @crkrenn ? https://openstates.org/find_your_legislator/?address=&geolocate=Use+Current+Location

**Comment by johnseekins** [comment]
You can also download bulk district data from here: https://openstates.org/data/geo/
