### ISSUE TITLE
Adding sessions before the data is in

### ISSUE THREAD

**Issue by showerst** [openstates/issues#804]
In past years as states have added sessions but not posted data yet, we've added them to the ignored sessions list and dropped in a commented out stub session in the main metadata, until bills were posted and we could test.

Now that we have the active=False attribute, should we just add the sessions that way, and keep them inactive until the data can be verified? I don't care either way, just want to to be on the same page with the other contributors as things ramp up.

@jessemortenson @NewAgeAirbender

**Comment by NewAgeAirbender** [comment]
Feel like we've just been adding the metadata blocks, commenting it out, and adding the session to the ignore list anyway, so really just makes more sense to just add that metadata with active=False. Thanks for bringing that up!
