### ISSUE TITLE
PA HB 1059

### ISSUE THREAD

**Issue by davidpassmore** [openstates/issues#805]
Your site says this passed on Jan 26. Wasn't passage on 28 Oct?

**Comment by showerst** [comment]
It looks like this one got bounced around, amended and re-referred which happens sometimes. Openstates shows the first  passage date, in that case.

https://openstates.org/pa/bills/2021-2022/HB1059/

If you check the [state site](https://www.legis.state.pa.us/cfdocs/billinfo/bill_history.cfm?syear=2021&sind=0&body=H&type=B&bn=1059) you can see the house had an action "Third consideration and final passage, Jan. 26, 2022 (201-0)", this usually denotes passage in the chamber.
