### ISSUE TITLE
New VT Committee Scraper

### ISSUE THREAD

**Issue by NewAgeAirbender** [openstates/issues#840]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Vermont.

It should scrape this [JSON webpage](https://legislature.vermont.gov/committee/loadList/2024/) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - *Note: if there does not seem to be a specific data key that indicates which “chamber” a committee belongs to (whether “upper”, “lower”, or “legislature”), look for any patterns that could indicate this and cross-reference with [Vermont's HTML webpage list](https://legislature.vermont.gov/committee/list/2024/). The JSON page is preferable for data ingestion, but you can use the HTML pages for increasing domain knowledge and accuracy assurance.*
   - “upper”, “lower”, or “legislature” (when joint, etc.)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/vt/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/ga/committees.py) that also parses a JSON page for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by chrisyamas** [comment]
The PR for this scraper rewrite has been approved and merged.
