### ISSUE TITLE
Vermont Legislative Districts Out of Date

### ISSUE THREAD

**Issue by ImperiumAdvisors** [openstates/issues#853]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Vermont legislative districts have not been updated. Previous legislators are showing and the legislative session started this week and we rely on the API to identify the correct legislators to send messages to.

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/find_your_legislator/?lat=44.476203&lon=-73.21511&address=100%20main%20street,%20burlington,%20vt&state=

**Source URL of correct data if applicable:**
https://legislature.vermont.gov/bill/QuickSearch/2024?SearchBy=Name&SearchBills=&SearchLegislators=burlington&SearchCommittees=

**Comment by johnseekins** [comment]
Hi @ImperiumAdvisors  We're actively working on this, but the [data source we typically use for geo location](https://www2.census.gov/geo/tiger/) won't be updated until March (at the earliest). Once we have a new data source to update from, we'll have Geo updates out shortly.

**Comment by ImperiumAdvisors** [comment]
Thanks John, what about the new legislators that were elected in November?

[photograph]
Ben Kinsley
Principal
M 802.310.3904
E ***@***.******@***.***>
Imperium Advisors
PO Box 4084
Burlington, VT
imperiumvt.com<http://imperiumvt.com/>
[twitter icon]<https://twitter.com/Ben_Kinsley> [linkedin icon] <https://www.linkedin.com/in/ben-kinsley-5074b26a/>  [instagram icon] <https://www.instagram.com/benkvt/>

**Comment by johnseekins** [comment]
People updates are being actively processed now. If you'd like to help, you can contribute here: https://github.com/openstates/people

**Comment by ImperiumAdvisors** [comment]
Got it, thanks!

[photograph]
Ben Kinsley
Principal
M 802.310.3904
E ***@***.******@***.***>
Imperium Advisors
PO Box 4084
Burlington, VT
imperiumvt.com<http://imperiumvt.com/>
[twitter icon]<https://twitter.com/Ben_Kinsley> [linkedin icon] <https://www.linkedin.com/in/ben-kinsley-5074b26a/>  [instagram icon] <https://www.instagram.com/benkvt/>

**Comment by johnseekins** [comment]
Geo updates were completed last Thursday/Friday.
