### ISSUE TITLE
Nevada State Senate and State Assembly redistricting

### ISSUE THREAD

**Issue by skipking** [openstates/issues#854]
NEVADA STATE SENATE AND STATE ASSEMBLY REDISTRICTING

As of Nov 8 2022 Nevada redistricted both the state senate and state assembly districts.

Upon my search with my address you returned...
https://openstates.org/find_your_legislator/?lat=36.13439&lon=-115.05491&address=3036%20bellavista%20ln,%20las%20vegas,%20nv&state=
SENATE: DISTRICT 21 James Ohrenschall
ASSEMBLY: DISTRICT 12 Susie Martinez

However, for my address, effective Nov 8 2022, it should be...
https://ballotpedia.org/Nevada_State_Senate_District_7
SENATE: DISTRICT 7 Roberta Lange
AND
https://ballotpedia.org/Nevada_State_Assembly_District_18
ASSEMBLY: DISTRICT 18 Venicia Considine

You need to fix your Nevada state senate and state assembly districts in your database.

**Comment by johnseekins** [comment]
Hi @skipking We're actively working on this, but the [data source we typically use for geo location](https://www2.census.gov/geo/tiger/) won't be updated until March (at the earliest). Once we have a new (reliable) data source to update from, we'll have Geo updates out shortly.

**Comment by skipking** [comment]
Thank you for the quick reply! And thank you for your efforts. 
 
I'm old school IT (I was very good, per my bosses and fellow employees, but my last full time job was in 2001) but I need employment in May (when I turn 66.5 years old) due to unsuccessful endeavors (long story) so if you need anything I'd love to work in IT again, whether it's coding, data base, etc. I did it all!
 
William "Skip" King
https://www.linkedin.com/in/williamskipking

**Comment by johnseekins** [comment]
District data was updated last Thursday/Friday.
