### ISSUE TITLE
Ga Leg 2023 not updated

### ISSUE THREAD

**Issue by erenbrumley-nerd** [openstates/issues#856]
**Issue Description:**
Georgia Leg started today and it only goes for 40 days and the data for the new districts and officers elected is not updated. 

**URL where this issue may be seen (API or OpenStates.org):**
on the website , i select my address and says I’m in HD 48 which in reality, is now HD 51. Also the new officer for HD48 hasn’t been added 

**Source URL of correct data if applicable:**
https://mvp.sos.ga.gov/s/

I can help update the data if you give me format.

**Comment by johnseekins** [comment]
Data was updated last Thursday/Friday with GA districts.
