### ISSUE TITLE
New TN Committee Scraper 

### ISSUE THREAD

**Issue by sroomf** [openstates/issues#862]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Tennessee.
​
It should scrape [the Senate committees](https://wapp.capitol.tn.gov/apps/CommitteeInfo/AllSenate.aspx), [the House committees](https://wapp.capitol.tn.gov/apps/CommitteeInfo/AllHouse.aspx) and [the Joint committees](https://www.capitol.tn.gov/joint/) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, etc.)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.
​
#### [Here is helpful documentation](https://docs.openstates.org/contributing/writing-a-committee-scraper/) for writing a committee scraper
​
### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/tn/committees.py) that may be helpful in understanding how we have captured the data in the past.
​
A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also parses an HTML page for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).
​
### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.
​
Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by abejburton** [comment]
I'll take this one

**Comment by chrisyamas** [comment]
For committee members:

```
class_officers = content.xpath(".//ul[@class='no-list members large small-block-grid-3']//a")
for officer in class_officers:
    name_and_role = [x.strip() for x in officer.text_content().split("\r\n") if len(x)]
    name, title = name_and_role
    com.add_member(name=name, role=role)

class_normal = content.xpath(".//ul[@class='members small-block-grid-4 no-list']")
```

**Comment by sroomf** [comment]
hi @abejburton, thanks for tackling this scraper! We would love it if you could finish up your work on this by **Monday, 1/31**. It's not a problem if you can't finish it up, but it is important for you to [push the work that you've done](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) so we can take over. Let us know if you have any questions or issues! We're happy to help out :)
