### ISSUE TITLE
New MT Committee Scraper

### ISSUE THREAD

**Issue by chrisyamas** [openstates/issues#864]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Montana.

It should scrape this [webpage for Senate Committees](https://leg.mt.gov/content/Committees/Session/2023-Senate-Committees.pdf) and this [webpage for House Committees](https://leg.mt.gov/content/Committees/Session/2023-House-Committees.pdf) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, etc.)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/mt/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/fl/bills.py) that uses several spatula `PdfPage` classes for processing different PDF pages, for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by glydeb** [comment]
Would like to work on this one for the 2023 Hackathon

**Comment by glydeb** [comment]
I'm going to switch to a different one - really want to make progress and I'm stuck on this one even with a lot of involvement.  Would be open to coming back to it in coming weeks.
