### ISSUE TITLE
New HI Committee Scraper

### ISSUE THREAD

**Issue by sroomf** [openstates/issues#870]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Hawaii.

It should scrape this [webpage of House, Senate, and Special Committees](https://www.capitol.hawaii.gov/comminfolist.aspx) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, etc.)
   - *Note: HI's Special Committees are typically chamber-specific because Hawaii rarely has joint committees.
      - The Special Committee on State of Hawaiʻi Procurement (SCP) is Senate (`chamber="upper"`).*
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/hi/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also parses an HTML page for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by claireboyd** [comment]
starting on this!

**Comment by sroomf** [comment]
hi @claireboyd, thanks for tackling this scraper! We would love it if you could finish up your work on this by **Monday, 1/31**. It's not a problem if you can't finish it up, but it is important for you to [push the work that you've done](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) so we can take over. Let us know if you have any questions or issues! We're happy to help out :)

**Comment by claireboyd** [comment]
great! I will definitely keep working on it until then and will let you know if I have any questions as I work through it :) thanks!

**Comment by claireboyd** [comment]
I just pushed my start of it - it took me longer than I expected to try to understand how spatula worked, so I didn't get very far. Happy to keep working on it after this week, but if you're hoping to move on then totally understand. Thanks for including me!

**Comment by chrisyamas** [comment]
Hi @claireboyd, thank you for pushing up what you had! We'll take it from here, but please let us know in the comments on any unassigned issues if you're still interested in contributing to the Open States project! You can also reach out to me at [christopher@civiceagle.com](mailto:christopher@civiceagle.com) if you want to learn more about the project and how you could contribute!
