### ISSUE TITLE
New NV Committee Scraper

### ISSUE THREAD

**Issue by sroomf** [openstates/issues#871]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Nevada. 

It should scrape this [webpage](https://www.leg.state.nv.us/App/NELIS/REL/82nd2023/Committees/List) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, etc.)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/nv/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also parses an HTML page for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by glydeb** [comment]
I'd like to do this one, please.  What is the desired timeline for completion?

**Comment by glydeb** [comment]
If the timeline for this is the same as the SD committee scraper, I should have no problem completing this one as well.

**Comment by NewAgeAirbender** [comment]
Yes, it's the same timeline. Really appreciate your help! If you run into issues, feel free to create a WIP PR and we'll help as we can!
