### ISSUE TITLE
New ND Committee Scraper

### ISSUE THREAD

**Issue by chrisyamas** [openstates/issues#874]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for North Dakota.

It should scrape this [webpage for regular committees](https://www.ndlegis.gov/assembly/68-2023/committees) (standing and procedural committees specific, to each chamber) and this [webpage of interim committees](https://www.ndlegis.gov/assembly/68-2023/session-interim) (joint i.e. `chamber="legislature"`) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, etc.)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/nd/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also scrapes an HTML List Page (using `HtmlListPage` and `HtmlPage` spatula classes) for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by ethanarsht** [comment]
I'll try this one! - Ethan

**Comment by sroomf** [comment]
hi @ethanarsht, , thanks for tackling this scraper! We would love it if you could finish up your work on this by **Monday, 1/31**. It's not a problem if you can't finish it up, but it is important for you to [push the work that you've done](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) so we can take over. Let us know if you have any questions or issues! We're happy to help out :)

**Comment by chrisyamas** [comment]
Hi @ethanarsht, while we have reassigned this issue due to time constraints, please let us know in the comments on any unassigned issues if you're still interested in contributing to the Open States project! You can also reach out to me at [christopher@civiceagle.com](mailto:christopher@civiceagle.com) if you want to learn more about the project and how you could contribute!

**Comment by ethanarsht** [comment]
Hi Chris,

Sorry I missed that initial email. I am interested in continuing to be
involved, I apologize I didn't get to more of this scraper.

Thanks,
Ethan
