### ISSUE TITLE
New NE Committee Scraper

### ISSUE THREAD

**Issue by chrisyamas** [openstates/issues#878]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Nebraska's unicameral legislature.

It should scrape this [webpage of standing committees](https://nebraskalegislature.gov/committees/standing-committees.php) and this [webpage of select and special committees](https://nebraskalegislature.gov/committees/select-committees.php) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “legislature” *(this will be the only chamber value for this jurisdiction, because ND has a unicameral a.k.a. one-chamber legislature)*
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/ne/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also scrapes an HTML List Page (using `HtmlListPage` and `HtmlPage` spatula classes) for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).
- *Note on Nebraska's site: pay special attention to the contents of each accordion element on page (for standing committee page it contains links to each committee's HTML Page, for select/special committee page it contains members of committee named in accordion header)*

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by jaskcodes** [comment]
Working on it

**Comment by ssegovba** [comment]
Working on this one too

**Comment by sroomf** [comment]
hi @jaskcodes and @ssegovba, thanks for tackling this scraper! We would love it if you could finish up your work on this by **Monday, 1/31**. It's not a problem if you can't finish it up, but it is important for you to [push the work that you've done](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) so we can take over. Let us know if you have any questions or issues! We're happy to help out :)
