### ISSUE TITLE
New ID Committee Scraper

### ISSUE THREAD

**Issue by chrisyamas** [openstates/issues#883]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Idaho.

It should scrape this [webpage of Senate Committees](https://legislature.idaho.gov/committees/senatecommittees/), this [webpage of House Committees](https://legislature.idaho.gov/committees/housecommittees/), this [webpage of Joint Committees](https://legislature.idaho.gov/committees/jointcommittees/), this [webpage of Interim/Special Committees](https://legislature.idaho.gov/committees/interimcommittees/), and this [specific webpage for Legislative Council (a unique management committee)](https://legislature.idaho.gov/legcouncil/) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, special/interim, legislative council)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/id/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also scrapes an HTML List Page (using `HtmlListPage` and `HtmlPage` spatula classes) for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by morden35** [comment]
<img width="978" alt="Screenshot 2023-01-14 at 4 58 19 PM" src="https://user-images.githubusercontent.com/82831800/212500737-1b4d554d-208e-422c-80e8-df8c2160f11d.png">

**Comment by morden35** [comment]
@jamesturk
