### ISSUE TITLE
New NJ Committee Scraper

### ISSUE THREAD

**Issue by chrisyamas** [openstates/issues#888]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for New Jersey.

It should scrape this [webpage of Senate Committees](https://www.njleg.state.nj.us/committees/senate-committees), this [webpage of Assembly (lower chamber) Committees](https://www.njleg.state.nj.us/committees/assembly-committees), this [webpage of Joint Committees](https://www.njleg.state.nj.us/committees/joint-committees), and this [webpage of Other Committees](https://www.njleg.state.nj.us/committees/other-committees) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (which, in NJ's case, are those on Joint or Other Committees pages)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/nj/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also scrapes an HTML List Page (using `HtmlListPage` and `HtmlPage` spatula classes) for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by divij-sinha** [comment]
Working on this!

**Comment by sroomf** [comment]
hi @divij-sinha, thanks for tackling this scraper! We would love it if you could finish up your work on this by **Monday, 1/31**. It's not a problem if you can't finish it up, but it is important for you to [push the work that you've done](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) so we can take over. Let us know if you have any questions or issues! We're happy to help out :)

**Comment by SteadyGiant** [comment]
Why scrape webpages when NJ committee data is already available as text files?

**Comment by chrisyamas** [comment]
@everettttt that's a great question! Do you have a source for where those text files are found?

**Comment by SteadyGiant** [comment]
[Right here](https://njleg.state.nj.us/legislative-downloads?downloadType=Bill_Tracking). The current "scraper" downloads and uses these files already--at least, that's how it was when I [submitted this PR](https://github.com/openstates/openstates-scrapers/pull/3765).

**Comment by chrisyamas** [comment]
Well I'm really glad you caught this, thank you. This was a classic example of data source research for the new session being aggregated through collaboration with some of our non-technical team members, and this convenient data source got lost in the shuffle as we've been converting all of our prior scrapers into [spatula](https://jamesturk.github.io/spatula/)-based scrapers.

However, I just went to that source page you had the scraper using before, and while I was concerned at first that it might not yet be updated for 2023 session, several committee membership spot checks seem to indicate that is! Thank you for bringing this to our attention!

**Comment by chrisyamas** [comment]
By the way @everettttt, I just wanted to update you that NJ actually has an API now for each of its committee types (senate, assembly, joint, and other), and that's what we're using with the new spatula scraper (rather than either the .mdb or .txt files from the download site, or any HTML pages).

**Comment by chrisyamas** [comment]
The [PR for the rewrite](https://github.com/openstates/openstates-scrapers/pull/4367) has been approved and merged.

**Comment by SteadyGiant** [comment]
@chrisyamas: Are all the endpoints (committees and beyond) documented somewhere?

**Comment by NewAgeAirbender** [comment]
> @chrisyamas: Are all the endpoints (committees and beyond) documented somewhere?

You can find an overview of the API [here](https://docs.openstates.org/api-v3/) & dig in & test them out on the [swagger docs](https://v3.openstates.org/docs#/)

**Comment by SteadyGiant** [comment]
@NewAgeAirbender I mean the original NJ legislature API on their website, not the Open States API.
