### ISSUE TITLE
Census providing wrong GeoIDs for two MA Senate districts

### ISSUE THREAD

**Issue by dscush** [openstates/issues#893]
**Issue Description:**
Here in MA, we have stupid county-based names for our districts, but we also have official number IDs which is what the census uses for their GeoIDs. As you can see [here](https://malegislature.gov/assets/redistricting/Senate%20Map%20Key-2021.pdf), the numerical district ID for the First Suffolk and Middlesex senate district is 25, and the ID for the Second Middlesex district is 27. Those are the numbers used on the [MA legislature's map](https://malegislature.gov/StateHouse/MediaGallery/Image/Greater%20Boston%20Area) as well. But in the Open States data those are flipped - see lines [800](https://github.com/openstates/openstates-geo/blob/main/data/ocdids/us_sldu.csv#L800) and [802](https://github.com/openstates/openstates-geo/blob/main/data/ocdids/us_sldu.csv#L802). I tracked this all the way back to the census. This [table](https://tigerweb.geo.census.gov/tigerwebmain/Files/acs21/tigerweb_acs21_sldu2010_tab10_ma.html) shows them flipped.

Interestingly, if you use the Open States website for these two senators, [Lydia Edwards](https://openstates.org/person/lydia-edwards-2VcPbDW4xGQvtLsiYKtVeO/) and [Pat Jehlen](https://openstates.org/person/patricia-d-jehlen-3LMqI08RJwWczeDSRbJGJ3/), you can see that their maps are each centered over the correct district, but the incorrect district is shaded in. Compare that to the [MA legislature's map](https://malegislature.gov/StateHouse/MediaGallery/Image/Greater%20Boston%20Area), which shows the correct numerical codes for these two districts.

Considering that the census has mixed up data, I'm not sure what the best solution for Open States would be. It's possible that simply flipping the GeoIDs in lines [800](https://github.com/openstates/openstates-geo/blob/main/data/ocdids/us_sldu.csv#L800) and [802](https://github.com/openstates/openstates-geo/blob/main/data/ocdids/us_sldu.csv#L802) could solve it, but I'm not sure how to fully test that out myself. The best thing would be to get the census to correct their data, but I have no idea how to log a bug with them, and even if that were corrected, I don't know whether that updated data would need to be manually updated here anyway.

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/person/lydia-edwards-2VcPbDW4xGQvtLsiYKtVeO/
https://openstates.org/person/patricia-d-jehlen-3LMqI08RJwWczeDSRbJGJ3/

**Source URL of correct data if applicable:**
https://malegislature.gov/StateHouse/MediaGallery/Image/Greater%20Boston%20Area

**Comment by dscush** [comment]
It doesn't seem to let me add a label. I believe this should have `component:geo`.

**Comment by johnseekins** [comment]
Hi, Dan. This isn't actually the only issue with census data right now. For example, MT still hasn't submitted their new division boundaries, so we're still supplying their old boundaries. So generally, we're still kinda working on updating geo data (although it's _mostly_ accurate at this point).

In fact, we're so in flux right now we're actually working off a branch in the geo repo: https://github.com/openstates/openstates-geo/pull/27.

I've updated the settings in the branch and am re-uploading data to correct this issue now.

**Comment by johnseekins** [comment]
@dscush Please re-open if the changes I made didn't resolve this issue.
