### ISSUE TITLE
Wrong Senate Districts

### ISSUE THREAD

**Issue by darrenwb123** [openstates/issues#902]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**

The Legislator lookup tool for the Kansas Senate is inaccurate. Senate Districts were changed by law in 2022, but they do not go into effect until 2024. Constituents are unknowingly being directed to members who do not represent them and may not after the 2024 election. 

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org

**Source URL of correct data if applicable:**
I'm not sure where you're getting your new district data, but I work in the Kansas Capitol and would be happy to work to connect you with those resources.

**Comment by johnseekins** [comment]
Hi @darrenwb123 As noted [here](https://openstates.org/find_your_legislator/), we received what we _believed_ to be complete post-2020 redistricting data from [The Redistricting Data Hub](https://redistrictingdatahub.org/). We also try not to update jurisdictional boundaries until _after_ elections with the new boundaries, so if there are new boundaries for KS coming to 2024 it sounds like The Redistricting Data Hub _and_ openstates.org are wrong.

**Comment by darrenwb123** [comment]
> Hi @darrenwb123 As noted [here](https://openstates.org/find_your_legislator/), we received what we _believed_ to be complete post-2020 redistricting data from [The Redistricting Data Hub](https://redistrictingdatahub.org/). We also try not to update jurisdictional boundaries until _after_ elections with the new boundaries, so if there are new boundaries for KS coming to 2024 it sounds like The Redistricting Data Hub _and_ openstates.org are wrong.

Thanks for the speedy reply. The problem is you did not wait to update the jurisdictional boundaries for the Senate. The House boundaries should have been (and I'm assuming they have also already been) updated, but the Senate should still be showing 2012 redistricting boundaries until the 2024 election.

**Comment by johnseekins** [comment]
We're reaching out to our data providers to see if we can get this easily rectified for everyone involved.

**Comment by darrenwb123** [comment]
Do we have an update on this? 

Perhaps we can just roll back the districts to what you had loaded previously? Do you still have your last data set for the Senate? That's all we'd need to do.

**Comment by johnseekins** [comment]
@darrenwb123 Can you provide any documentation about this change? We (and our data providers) can't find anything indicating that KS isn't updating Senate districts until 2024.

**Comment by johnseekins** [comment]
Finally heard back from the KS legislature. Our data partners are working on updating their maps to correctly reflect this change.

**Comment by darrenwb123** [comment]
What's the timeline on this change. Every day mea'ns constituents meeting with the wrong members. It happened again today. I'm a staffer and this if affecting sitting members.

**Comment by showerst** [comment]
@darrenwb123  we're working on loading proper data, but we could use some test addresses.

Do you have any cases you can provide of "101 anywhere street should be in district 12 until 2024, when it moves to district 15"? Anything along those lines so we can verify the underlying data sources for updates would help.

**Comment by johnseekins** [comment]
We believe we've resolved KS boundaries for the Senate. Please close this issue if things are working again.
