### ISSUE TITLE
Any way to know when a bill is *scheduled for a hearing (before votes)?

### ISSUE THREAD

**Issue by koryp123** [openstates/issues#903]
Hi all, apologies if this is not the best place to ask the question.

I'm wondering if there's a way to know about when a bill is scheduled for a hearing (before the votes happen).  In the API docs it shows referrals to a committee and votes, but I don't see where it says a hearing was actually scheduled

**Comment by johnseekins** [comment]
We do our best to track events for bills as they move through committees/etc. For example: https://openstates.org/or/bills/2023R1/HCR9/. You can see it moving through committtee, being voted on, etc. Essentially, we try and track whatever the legislature makes available about bills as they move through the process.

Does that help clarify?

**Comment by koryp123** [comment]
Yes that clairifes thanks, but this still doesn't get to committee hearing notices, it only reports that a bill was assigned to the committee, and then again after the votes have taken place -- no data on date and time of committee hearings.
