### ISSUE TITLE
Arizona State Legislators OOD

### ISSUE THREAD

**Issue by michaelnewmode** [openstates/issues#907]
**Issue Description:**
Both the Arizona State House and Senate are currently out of date. 

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/az/legislators/?chamber=upper (Senate)
https://openstates.org/az/legislators/?chamber=lower (Lower) 

**Source URL of correct data if applicable:**
https://www.azleg.gov/MemberRoster/?body=H (House)
https://www.azleg.gov/MemberRoster/?body=S (Senate)

**Comment by NewAgeAirbender** [comment]
Hello, we're working on updating Legislators and should have a fix in shortly.
