### ISSUE TITLE
New LA Committee Scraper

### ISSUE THREAD

**Issue by chrisyamas** [openstates/issues#911]
### We need a new committee scraper written in [spatula](https://jamesturk.github.io/spatula/) for Louisiana.

*IMPORTANT NOTE: the miscellaneous committees list page includes various other committees that span different chambers, so some will be "lower", some "upper", and some "legislature". This should be clear from the name (i.e. "Legislative" or "Joint" implies `chamber="legislature"`).*

It should scrape this [webpage of Senate Committees](https://www.legis.la.gov/legis/Committees.aspx?c=S), this [webpage of House Committees](https://www.legis.la.gov/legis/Committees.aspx?c=H), and this [webpage of Miscellaneous Committees](https://www.legis.la.gov/legis/Committees.aspx?c=M) to get:
- **name**
   - “Small Business”, “Agriculture”, etc.
- **chamber**
   - “upper”, “lower”, or “legislature” (when joint, etc.)
- **classification**
   - ex: "committee", "subcommittee"
- **parent**
   - *only if it is a subcommittee* - scraper should have a way to determine this
   - ex: parent="Natural Resources" when *sub*committee name="Forestry"
- **sources**
   - each added using `add_source()` method on instance of `ScrapeCommittee` type object
   - ex: home page for list of committees, specific page for that committee, etc.
- **members**
   - - each added using `add_member()`method on instance of `ScrapeCommittee` type object
   - *Attributes:*
      - **name**: “Jane Doe”, “John Smith”, etc.
      - **role** (where applicable): “Chair”, “Ranking Member”, etc.

### Useful scrapers for reference
An [old non-spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/la/committees.py) that may be helpful in understanding how we have captured the data in the past.

A [spatula-based scraper](https://github.com/openstates/openstates-scrapers/blob/main/scrapers_next/mo/committees.py) that also scrapes an HTML List Page (using `HtmlListPage` and `HtmlPage` spatula classes) for reference.
- As in the other spatula scraper, you will need to set the session variable separately (rather than depend on the `__init__.py`).

### Other useful resources
You can reference the [object models for committee scrapers](https://github.com/openstates/openstates-core/blob/main/openstates/models/committees.py) in the Open States Core repo.

Further documentation on running spatula scrapers in the command line can be found [here](https://docs.openstates.org/contributing/scrapers/#running-spatula-scrapers).

**Comment by kdmonroe** [comment]
I'll take this!

**Comment by chrisyamas** [comment]
Hi @kdmonroe, how quickly do you think you would have a Pull Request with a full scraper? This is the last jurisdiction left that needs a committee scraper written and we're eager to get to 100% coverage, so we're hoping to have this one done by Friday. However, no pressure if that's too fast of a turnaround for you! Just let us know either way :)

**Comment by kdmonroe** [comment]
Hey @chrisyamas - I can shoot for Friday! I'll let you know if I'm running behind.

**Comment by chrisyamas** [comment]
Thanks, @kdmonroe ! Don't hesitate to comment here with any questions you have or issues you may need help resolving in the process.

**Comment by kdmonroe** [comment]
@chrisyamas - I'm running behind! I would need an extra few days to complete this. if you'll allow extra time - could I chat with someone about writing CSS selectors? [this reference](https://jamesturk.github.io/aows/selectors/) page is helpful but I still have questions

otherwise I'd love to contribute to another scraper or issue that is not as time-sensitive! thanks.

**Comment by chrisyamas** [comment]
@kdmonroe A few extra days is all good. And I would be happy to chat with you about CSS selectors! The `spatula` library has its own `CSS` and `XPath` selectors, and while they take the same arguments as xpath and css selectors you may have seen in other web scraping approaches, they do use slightly different syntax outside of the arguments.

Send me an email at christopher@civiceagle.com and I would be happy to set up a Zoom for today or any time in the next couple days to talk specifics with you!

**Comment by chrisyamas** [comment]
Hi @kdmonroe, I'm glad we were able to sync over the weekend on this. Like I mentioned then, don't hesitate to reach out if you're encountering any challenges or have any further questions as you finish the scraper!

**Comment by kdmonroe** [comment]
@chrisyamas - I completed house + senate committees but struggling with the miscellaneous page. Some questions 

1. Several links on the parent page lead to ununiform pages - requiring different selectors. Is there anyway to define a selector based on the url? Or should I use a helper function to return the selector from a given link? Appreciate any help on how to approach these. Examples below - 
  - [State Bond Commission](https://www.treasury.la.gov/state-bond-commission)  
  - [Senate Select Committee on Women and Children](https://senate.la.gov/Sen_Committees/WomenChildren), 
  - [Public Retirement Systems' Actuarial Committee](https://www.legis.la.gov/Legis/BoardMembers.aspx?boardId=616)

 2.  [Joint Legislative Committee on the Budget](http://jlcb.legis.la.gov/) - membership details require navigating to an extra page. How could I structure this?

3.  How to handle a [404 error](https://www.doa.la.gov/Pages/IEB/index.aspx)? Can I redirect to the [working membership page](https://www.doa.la.gov/state-employees/interim-emergency-board/board-info/board-members/)?

**Comment by kdmonroe** [comment]
Also how should a [404 error](https://www.doa.la.gov/Pages/IEB/index.aspx)? Is there anyway I can redirect to the [working membership page](https://www.doa.la.gov/state-employees/interim-emergency-board/board-info/board-members/)?

**Comment by chrisyamas** [comment]
Hi  @kdmonroe, I think I'll be able to give you better guidance on some of this once I can see your code. can you push your most up-to-date changes to your forked repo and make a PR to [openstates-scrapers](https://github.com/openstates/openstates-scrapers)?

But quick answers:

1. I would create a dictionary of url_indicators and selectors that you can use in either the `CommitteeList` or `CommitteeDetail` class, but it depends on how much variety there is. For now, as long as you can get it to work for the standing committees (even if its not getting select committees, commissions, etc) then that's a good starting point for now. We can add the greater complexity later to get those additional committees with their uniform HTML pages.

2. You can just use a simple helper function for that one case like:
```
import requests
import lxml.html

def get_membership(url):
    response = requests.get(url)
    content = lxml.html.fromstring(response.content)
    # and then just go from there...
```
You can just call that function for a case like Joint Legislative Committee on the Budget to get the membership details.

3. [This page](https://github.com/jamesturk/spatula/blob/9ff3678740eec19ae528aafc5f4f12d41c2f35b8/docs/scraper-basics.md#:~:text=dev/staff/101-,Error%20Handling,-Now%20that%20we%27re) has details on how to add that into your spatula classes, if you scroll down to the Error Handling section.

**Comment by chrisyamas** [comment]
But the most important thing is to push the commits and make the PR as soon as you can.

**Comment by kdmonroe** [comment]
@chrisyamas - Opened a draft PR! I accidentally committed an extra file (it's deleted but I can redo the PR if needed). Thanks for your help, I'll work on completing these last items.

**Comment by kdmonroe** [comment]
@chrisyamas - Nearly finished. Some final questions... 

1. For the case requiring an additional page to get membership - I'm not getting any elements returned using the method you suggested. Using the selectors in a browser works... could [this page](https://jlcb.legis.la.gov/default_Members) have something blocking scraping? I can include what I have so far in the PR but the committee's membership will be empty. 
2. Membership of [State Bond Commission](https://www.treasury.la.gov/state-bond-commission) includes state officials like the governor and lieutenant gov. Should their roles be "member"? Should those titles be included or handled differently in `add_member()`?

**Comment by flooie** [comment]
@kdmonroe @chrisyamas I hope you don't mind, I took a stab at completing this issue.
