### ISSUE TITLE
virginia showing new districts, but new districts are not yet in effect

### ISSUE THREAD

**Issue by jmcclelland** [openstates/issues#913]
**Issue Description:**

The "Find your state legislator" tool is displaying district information today that will not go into effect until 2024.

**URL where this issue may be seen (API or OpenStates.org):**

https://openstates.org/find_your_legislator/?lat=37.56221&lon=-77.43734&address=2101%20Fendall%20Avenue,%20Richmond,%20VA,%20USA&state=

Shows Lower: 79, and Upper: 14

**Source URL of correct data if applicable:**

In contrast, the VA state tool:

https://whosmy.virginiageneralassembly.gov/index.php/legislator?search=2101%20Fendall%20Avenue,%20Richmond,%20VA,%20USA

Shows those districts as being correct starting in 2024, whereas now they should be Lower: 71 and Upper: 9

Thank you!

**Comment by johnseekins** [comment]
We believe we've resolved VA boundaries for the both chambers. Please close this issue if things are working again.

**Comment by jmcclelland** [comment]
Thank you! Looks good.
