### ISSUE TITLE
Legislator data not updated

### ISSUE THREAD

**Issue by koryp123** [openstates/issues#914]
We're pulling legislator data via API v3 and we're seeing a lot of states that are not yet updated with new legislator data.  
Just one example would be Valerie McDonnell in New Hampshire and also legislators in New Mexico.

Is OS still on top of the legislator data or is it more focused on legislation now?

**Comment by NewAgeAirbender** [comment]
We've been working to update Legislators across jurisdictions but have some bugs that are effecting how that data is being updated to our database. We're currently working on it and should have a fix this week, will update this when the accurate current Legislators are live.

**Comment by koryp123** [comment]
Got it, thank you for the update

**Comment by alexhackney** [comment]
Any update on this? Still seeing issues for WV. Looks like the openstates/people is right but the api is not returning current data.

Thanks so much for the effort here!
