### ISSUE TITLE
KS Approved Senate Districts Not in Effect Until 2024

### ISSUE THREAD

**Issue by JcfisherKLRD** [openstates/issues#920]
I am an analyst with the Kansas Legislative Research Department. It has come to our attention that when using the find my legislator feature openstates pulls the map data from the KS Senate Districts approved in 2022. Per 2022 SB 563, Sec 4. these districts do not go into effect until 2025 (Individuals will run for election using these maps in 2024). As a result when the feature is used the user is receiving incorrect information for their current Senate (Upper) member. We are requesting that Openstates use the 2012 approved data set until the 2022 maps take effect.

**Comment by JcfisherKLRD** [comment]
also see: https://github.com/openstates/issues/issues/902

**Comment by showerst** [comment]
@JcfisherKLRD we're working on loading proper data, but we could use some test addresses.

Do you have any cases you can provide of "101 anywhere street should be in district 12 until 2024, when it moves to district 15"? Anything along those lines so we can verify the underlying data sources for updates would help.

**Comment by JcfisherKLRD** [comment]
@showerst I am not able to provide specific addresses for testing. A general example would be the southern half of the city of Overland Park. Addresses in that area would be in the 37th Senate District using the 2012 boundary's. In the 2022 redistricting the area became part of the 35th Senate District.

**Comment by showerst** [comment]
@johnseekins here's a good test address --

```
712 Main St, Scott City, KS 67871

[lat] => 38.480357
[lng] => -100.906731
```

Pre-2025 Distrct: 33rd
2025 District: (which currently shows on openstates.org) -- 39th

https://ballotpedia.org/Redistricting_in_Kansas#District_maps for the side by side.

**Comment by johnseekins** [comment]
We believe we've resolved KS boundaries for the Senate. Please close this issue if things are working again.
