### ISSUE TITLE
Massachusetts state senators all mixed up: old and new district names, duplicate sld-ids

### ISSUE THREAD

**Issue by dscush** [openstates/issues#926]
Before https://github.com/openstates/openstates-geo/pull/28 went out, I had noticed that there were actually several more MA senate districts that were mixed up in https://github.com/openstates/openstates-geo/blob/main/configs/jurisdictions/ma.yml in addition to the two I mentioned in https://github.com/openstates/issues/issues/893 which @johnseekins fixed. I was getting ready to correct the rest of that file and throw a PR against the working branch for it when I noticed things seemed to have gotten worse, and then discovered that PR.

One example of a mixed up district from before the PR was for `latitude 42.1850814, longitude -71.6664777` which should get the Second Worcester district (`ocd-division/country:us/state:ma/sldu:2nd_worcester`), and should have `sld-id: sldu-25D08`. But that location gave me `ocd-division/country:us/state:ma/sldu:worcester_hampden_hampshire_and_middlesex` (which had the Second Worcester's `sld-id: sldu-25D08`) instead. 

Now, as of this PR, you have three duplicate `sld-id`s for a total of 43 senate districts (when there are only 40), which appears to be due to including some of the districts' old (pre-redistricting) names and some new ones. This seems to be causing a problem for the graphql API because, while Second Worcester district now has the correct `sld-id: sldu-25D08`, there's still the old record above it for the Worcester, Hampden, Hampshire, and Middlesex district with `sld-id: sldu-25D08`. But that's the old district name, so when I use that location, I don't get any senator in the response at all!

It also doesn't include all the new district names. For example, it has the new district name `ocd-division/country:us/state:ma/sldu:worcester_and_hampshire` (new name for Worcester, Hampden, Hampshire, and Middlesex) but it's missing the new district name `ocd-division/country:us/state:ma/sldu:norfolk_worcester_and_middlesex`.

So I'm not sure if that PR is intended to update things to use the current districts or keep them on the old ones, but it needs to pick a lane lol. If you want to tell me which direction to go in, I'd be happy to clean this file up and create a PR.

And for reference, [these](https://malegislature.gov/assets/redistricting/Senate%20Map%20Key-2021.pdf) are the correct `sld-id`s along with the old and new district names, which I would use to fix `configs/jurisdictions/ma.yml`.

**Comment by johnseekins** [comment]
@NewAgeAirbender I think this was a combination of problems:

1. https://github.com/openstates/openstates-core/pull/99/ we had a couple typos still in openstates-core
2. https://github.com/openstates/openstates-geo/pull/29 We had a few duplicate keys in the geo jurisdiction mappings

#1 needs to get merged and updated in #2 before it'll work correctly. But then we should be able to run the standard pattern.

I _think_ that fixes all the problems here.

**Comment by dscush** [comment]
Thanks for working on this! I see those PRs were merged two weeks ago, but I'm still getting the wrong (or missing) senators in the API. Do you have an idea of when this fix will be deployed?

**Comment by dscush** [comment]
Hi @johnseekins, these PRs were merged a month ago so I just wanted to follow up on this. I'm still getting the same wrong data in production.

**Comment by johnseekins** [comment]
Interesting that I used the mapping file you provided to set the districts to (what I thought was) the correct values.

We'll continue to work on this, but if you could give a specific mapping of `wrong district` to `right district`, or even just a list of the districts that are wrong/duplicated/etc. so we can properly dig in to cleaning up these records, that would be really helpful.

**Comment by dscush** [comment]
@johnseekins It's really weird because the data currently in [/configs/jurisdictions/ma.yml](https://github.com/openstates/openstates-geo/blob/main/configs/jurisdictions/ma.yml#L8) does seem to be correct. It makes me wonder if there's some kind of stale caching going on, or some tiny bug somewhere causing the data not to reprocess/update, so it keeps using previously processed data.

For examples, [this](https://openstates.org/find_your_legislator/?lat=42.30306&lon=-71.24204&address=433%20central%20ave%20needham%20ma&state=) is an address in Senator Becca Rausch's `Norfolk, Worcester and Middlesex` district, returning three different state senators. [This](https://openstates.org/find_your_legislator/?lat=42.206805&lon=-71.68385&address=2%20north%20st,%20grafton&state=) is an address in Senator Michael Moore's `2nd Worcester` district, returning no state senators. So it's not really a matter of mapping `wrong district` to `right district`. I really think [/configs/jurisdictions/ma.yml](https://github.com/openstates/openstates-geo/blob/main/configs/jurisdictions/ma.yml#L8) has them correct at this point, but something has prevented that data from being.

One last thing that _might_ be relevant is that [this commit](https://github.com/openstates/openstates-geo/commit/5479b8300643eb9b989cafc600c872c11da00660) changed the sld-id values from `sldu-250##` to `sldu-25D##`. I'm having a hard time following the full pathway of where all this geo data is coming from and going to so that's just a guess.

And again, thank you for working on this.

**Comment by johnseekins** [comment]
Do the inaccurate results stick to the upper chamber (senators only)? Or is it affecting both chambers?

The `sldu-250` vs. `sldu-25D` is largely due to the data returned from our data sources. Currently, the census data we're using adds `D` to upper chamber district names for...whatever reason.

**Comment by dscush** [comment]
I haven't checked all 160 state reps (lower chamber), but I've checked about 20 of them and haven't found any that are wrong yet.

**Comment by johnseekins** [comment]
@dscush I _believe_ we've resolved all district issues now. Is this still coming back incorrectly?

**Comment by dscush** [comment]
@johnseekins Sorry for the delay - it looks like it's working now! Thank you!
