### ISSUE TITLE
IA Bills info not aggregating 

### ISSUE THREAD

**Issue by mwhipple20** [openstates/issues#947]
Info for following is not coming up in bills search api.
HF 555
HSB 214 - renumbered to HF 623
SSB 1197

**Comment by NewAgeAirbender** [comment]
Thank you for flagging this, looks like the site has changed page layouts so we've updated the scraper & should have bill information shortly. Will close this ticket when the bills above are available.

**Comment by NewAgeAirbender** [comment]
Those bills are now available on the API. Thank you again.
