### ISSUE TITLE
Flordia State Senate out of Date

### ISSUE THREAD

**Issue by michaelnewmode** [openstates/issues#983]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:**
Florida State Senate out of date
_Examples:_  
Annette Taddeo Democratic 40 Senate
Jeff Brandes Republican 24 Senate

**URL where this issue may be seen (API or OpenStates.org):**
https://openstates.org/fl/legislators/?chamber=upper

**Source URL of correct data if applicable:**
https://www.flsenate.gov/Senators

**Comment by egrosshans** [comment]
I am having the same issue. Annette Taddeo Democratic 40 Senate and Jeff Brandes Republican 24 Senate are no longer Senators and should be replaced with Bobby Powell 24 Senate and Ana Maria Rodriguez 40 Senate

**Comment by NewAgeAirbender** [comment]
This has been updated, thank you for raising this issue!
